### ISSUE TITLE
Undo set a custom definition not works

### ISSUE THREAD

**Issue by And0k** [veusz/veusz#104]
Undo after change custom definition constant value is not works

**Comment by jeremysanders** [comment]
Are you sure? It works for me. You may have to undo more than once, as each time you set a field in the custom definition dialog it counts as a new operation.

**Comment by And0k** [comment]
I'm sure: I use this bug to undo zooming after set constant, and constant remains new. But it would be better to have separate zooming undo functionality

**Comment by jeremysanders** [comment]
Let me see whether I can work out what is happening...

**Comment by And0k** [comment]
It works in my new Veusz 2 installstion
