### ISSUE TITLE
Max OSX 10.9 Install Issue with Homebrew

### ISSUE THREAD

**Issue by steveehlert** [veusz/veusz#121]
So I am having some problems trying to build/install Veusz from source on Max OSX 10.9 system (I should note that the pre-compiled binary works perfectly). I used Homebrew to put pyqt and sip on my computer. There seems to be a library mismatch (similar to issue 48: https://github.com/jeremysanders/veusz/issues/48) but I am not well versed enough in these libraries to figure out where my Homebrew might be installing the libraries and where I should link them to. 

Compilation output is below.  Any insights as to how to work around this issue would be appreciated, as I would like to try and test out some ways to produce many plots through the API directly without going through the GUI. 

sehlert$ python setup.py build
running build
running build_py
running build_ext
building 'veusz.helpers.qtmml' extension
/usr/local/Cellar/sip/4.16/bin/sip -c build/temp.macosx-10.9-x86_64-2.7 -x VendorID -t WS_MACX -t Qt_4_8_4 -x PyQt_NoPrintRangeBug -x Py_v3 -I /usr/local/share/sip/PyQt4 -b build/temp.macosx-10.9-x86_64-2.7/qtmml.sbf veusz/helpers/src/qtmml/qtmml.sip
sip: Unable to find file "QtCore/QtCoremod.sip"
error: command '/usr/local/Cellar/sip/4.16/bin/sip' failed with exit status 1

**Comment by jeremysanders** [comment]
Hi - I don't have a Mac with homebrew to hand, but it looks like some of the sip configuration is wrong. setup.py includes the sip directory in the sip command above (/usr/local/share/sip/PyQt4). I suspect this is wrong, as your sip executable is in /usr/local/Cellar/sip/4.16/bin/sip. Somewhere on your system there should be a QtCoremod.sip file which should by in the QtCore subdirectory of the sip directory.

You can verify what sip thinks is its directory by running the following python commands:
    import sipconfig
    print sipconfig.Configuration().default_sip_dir

Perhaps you have an old sip installation which is being found first. You could try seeing in python what sipconfig.__file__ and sip.__file__ are in python after importing them.

By the way, you can use the API with the binary, by copying the embed.py file somewhere in your python path.

**Comment by jeremysanders** [comment]
Closing this as it's very old.
