### ISSUE TITLE
Export dialog enhancements

### ISSUE THREAD

**Issue by Sembazuru** [veusz/veusz#129]
I'm currently running Veusz v1.23.1 on Windows 7 Enterprise SP1 64bit (work's computer).

I really like the new multi-page graphical export feature, really simplifies my workflow when creating several plots for my reports from a single dataset.

I have two requests, ordered in priority:
1. **Non-volatility of output filename format.**
   Every time I use the multi-page graphical export the default filename is `<filespec>%PAGENUM%<format extension>`. But I want to use `<filespec>_%PAGENAME%<format extension>`. I'm sure others would like to use their own format. So, my enhancement request is to have either:
   - a setting to for the user to specif their desired default or
   - for the program to remember the last used format (like how many of the other parameters work).
2. **Enhanced subset of printed pages.**
   Currently one can only select current page, all pages, or a single range. It would be nice for the range format to be like other printing requestors in the system and take a string where one could enter complex page ranges. For example, "1-3,5,9" which would print pages 1 through 3 inclusively, page 5, and page 9.

**Comment by jeremysanders** [comment]
Sorry for the slow reply, These would be helpful to add.

**Comment by patrickstanley** [comment]
I am just checking in to see if anything has been done about number 1. It would be great to have it remember the last used format (i.e. %PAGENAME% instead of %PAGENUM%).

**Comment by jeremysanders** [comment]
The first issue should be fixed here:
https://github.com/veusz/veusz/commit/19b23dd1fcb9eec319e98947c99a0cb46ddec150

**Comment by jeremysanders** [comment]
Added arbitrary page list to be given
