### ISSUE TITLE
Minuit library missing in Ubuntu package, poor fit results

### ISSUE THREAD

**Issue by bmerle** [veusz/veusz#148]
The Veusz package for Ubuntu is doing a (much) poorer job fitting my data than the windows binaries. The reason is presumably that the minuit library has been included in the compiled windows program, but not in the Ubuntu version (tested: version 1.24). In the Ubuntu case, Veusz defaults to L-M fitting, which is unfortunately not able to satisfyingly cope with small numbers (<1) data. It fails for instance with the simple quadratic function y=a*x^2 when a<=0.0001 (tested for x=1,2,...50 in that case the error on a is already 5%). Would it be possible to include minuit in the Ubuntu package as well? Thank you and best regards.

**Comment by jeremysanders** [comment]
Sorry, it would be difficult to include minuit in the ubuntu package. Pyminuit has a complex build process and it would take a lot of time trying to get it to package (at least for me, as an inexperienced debian packager).

You can use the linux binary instead, which does include minuit.

Alternatively, have you tried changing your model to be something like y=1e-5*a*x^2 if appropriate?

In the future, I plan to improve the fitting in veusz, but I have some other priorities first. For example, it could optionally use scipy minimization rather than LM/minuit.

**Comment by bmerle** [comment]
Thank you! The linux binary works. FYI, the reason why I wished to have a working Ubuntu version is that we are trying to teach our students to use Veusz for their scientific projects. Since the computer labs are running Ubuntu at our university, the fitting issue is quite critical.

**Comment by simone-romiti** [comment]
> Thank you! The linux binary works. FYI, the reason why I wished to have a working Ubuntu version is that we are trying to teach our students to use Veusz for their scientific projects. Since the computer labs are running Ubuntu at our university, the fitting issue is quite critical.

Hi @bmerle , could you please give some details? Unfortunately I couldn't make the linux binary work.
I downloaded the linux binary from https://veusz.github.io/download/ , extracted the archive and ran the veusz.exe file. I still get the error "Minuit not available, falling back to simple L-M fitting", even with the file examples/fit.vsz

**Comment by jeremysanders** [comment]
It looks like the binary tar.xz hasn't got a working iminuit due to a pyinstaller bug. I can look at for the next release.

For the moment, I've tried making an iminuit package in the veusz PPA. You could try installing python3-iminuit from there. The xenial version hasn't had any testing done.

**Comment by simone-romiti** [comment]
I added your ppa, but I think I'd need the bionic version of python3-iminuit (I'm using Ubuntu 18.04.5 LTS). apt-get wasn't able to find it. Are you planning to release the bionic version too?

**Comment by jeremysanders** [comment]
I forgot bionic. Try it now.

**Comment by simone-romiti** [comment]
Thanks a lot, it works now!

**Comment by jeremysanders** [comment]
I've also worked out why the linux binary wasn't including iminuit. This should be fixed for the next release, so I'm closing this now.
