### ISSUE TITLE
Proposal: Migrate documentation to Sphinx

### ISSUE THREAD

**Issue by mythsmith** [veusz/veusz#166]
And set up a free auto doc building service like http://readthedocs.org. Auto documentation from code might easily be implemented (eg: tools plugin fileds, #153, commands, meaning of settings, etc).

**Comment by jeremysanders** [comment]
Seems a good idea. Just needs someone to do the work...

**Comment by jeremysanders** [comment]
Fixed in 2.0

**Comment by mythsmith** [comment]
Thanks! That's really nice!
