### ISSUE TITLE
Malicious reported by Symantec

### ISSUE THREAD

**Issue by MGRashed** [veusz/veusz#176]
Version 1.26.1 (latest) is being reported as risky file by Symantec, please have a look -
![prtscr capture](https://cloud.githubusercontent.com/assets/1528712/26236098/f2a8dc42-3cb1-11e7-9c24-13cbd1a49c38.jpg)

**Comment by jeremysanders** [comment]
I've asked symantec to whitelist this, though I've had no response.

**Comment by jeremysanders** [comment]
PS If anyone wants to pay annually for a signing certificate for windows please let me know.

**Comment by MGRashed** [comment]
Symantec does not block version 1.26 or earlier versions, it's happening only for 1.26.1.

**Comment by jeremysanders** [comment]
It's probably because of the new download location as the website has moved.

**Comment by MGRashed** [comment]
Well, I think Symantec has updated their database as per your request, it's not deleting/quarantining it now -

![prtscr capture](https://cloud.githubusercontent.com/assets/1528712/26348246/7f61ddba-3fef-11e7-8bfc-0ae0a9567a0b.jpg)

**Comment by jeremysanders** [comment]
Thanks. I'll close the issue now.
