### ISSUE TITLE
Veusz 1.26.1 won't plot dates propperly.

### ISSUE THREAD

**Issue by g-sob** [veusz/veusz#177]
Dear Jeremy,

I have just updated my Veusz to the latest version and now I can't plot any dates in x axis.

Please help :)
![image](https://cloud.githubusercontent.com/assets/27735649/26324139/f442c7cc-3f07-11e7-85bf-f29c9d6f52e3.png)
![image](https://cloud.githubusercontent.com/assets/27735649/26324220/48a79018-3f08-11e7-8e15-7769c5ad0fc1.png)
![image](https://cloud.githubusercontent.com/assets/27735649/26324239/5ca5384a-3f08-11e7-8bf7-d21e7c87421a.png)

**Comment by jeremysanders** [comment]
Did it work before? Have you changed the axis mode to datetime? Does the datebar example (under the help menu) work?

**Comment by g-sob** [comment]
Never tried to plot date in the old version (1.9). Yes, I have changed the
axis mode to datetime. Where is the help menu so I can find the datebar
example? :)

Guilherme Augusto N. Sobrinho

MSc. em Radioecologia - IRD/CNEN
Engenheiro Agrônomo - UFRuralRJ
(+55 21) 9 9324-9141 / 98913-5031
skype: guilherme-sobrinho
--
MSc. Tropical Radioecology
BSc. Agronomy

2017-05-23 3:22 GMT-03:00 Jeremy Sanders <notifications@github.com>:

**Comment by g-sob** [comment]
Hey, Jeremy! I got this: In the manual says that "Dates must be in ISO format YYYY-MM-DD"... so... I converted my date column to ISO format and specified this format on the "import data" window. It worked. :)
![export](https://cloud.githubusercontent.com/assets/27735649/26366303/f3cc976e-3fc0-11e7-8de7-08298c987fdc.jpg)

**Comment by jeremysanders** [comment]
Thanks.
