### ISSUE TITLE
Lines and labels slightly misplaced during export and at different zoom levels

### ISSUE THREAD

**Issue by piosl** [veusz/veusz#178]
Hi!
I have some problems with exporting to TIFF. Both lines and labels are slightly misplaced on exported image. There are also differences between 300 and 600 DPI TIF versions.
I tried both "relative" and "axis" positioning of line and label widgets but it doesn't change much. 

There are also problems with widget scaling (and I believe it is the origin of troubles) - there are differences with widget positioning at 1:1 and other zoom levels. I attach 2 screenshots: first one with 1:1 scaling, second one with three steps of Zoom in. 

(Windows 10 64-bit, Veusz 1.26.1, I can also test it on the latest Ubuntu.)
![image](https://cloud.githubusercontent.com/assets/2103496/26349175/4e7e4912-3faf-11e7-8d4e-75c10827f4f0.png)

![image](https://cloud.githubusercontent.com/assets/2103496/26349275/8deb8826-3faf-11e7-8e14-cf982afcbdfa.png)

**Comment by jeremysanders** [comment]
This is probably because in the rendering code Veusz zooms by scaling all the quantities, including the font size. Fonts don't behave the same when scaled as they are optimized for different pixels scales.

Veusz should probably choose a "proper" DPI to use for fonts on screen and when exporting, and do a paint device transformation instead to zoom. I'm not sure this will work, however.

**Comment by jeremysanders** [comment]
Hopefully the above commit should make the fonts and positions consistent between different zoom levels. It fundamentally changes the way Veusz does scaling.

**Comment by schoggi** [comment]
Hi,
I experience a similar thing, but with two keys next to each other having the same font ect.
GUI:
![image](https://user-images.githubusercontent.com/48128877/74274813-0a417200-4d13-11ea-8b24-3bd4ab38f38e.png)
tiff:
![image](https://user-images.githubusercontent.com/48128877/74274842-14fc0700-4d13-11ea-807d-666a7c29a7e8.png)
To get the tiff right, I shifted one key in the GUI:
![image](https://user-images.githubusercontent.com/48128877/74274897-28a76d80-4d13-11ea-8c96-50ebcc70a7ad.png)
and then I got in the following in the tiff file:
![image](https://user-images.githubusercontent.com/48128877/74274917-33620280-4d13-11ea-89b2-22e58e3f53ad.png)
The Formatting looks like this for the two:
![image](https://user-images.githubusercontent.com/48128877/74274942-4248b500-4d13-11ea-9c09-925f2ff7c9e8.png)

![image](https://user-images.githubusercontent.com/48128877/74274953-483e9600-4d13-11ea-8035-2f46c8ea2ac7.png)

**Comment by Cimiteriophiliac** [comment]
Can confirm it still exists, I'm having the same problem.
