### ISSUE TITLE
Custom definition as X/Y data in Plot Points

### ISSUE THREAD

**Issue by Sugestor** [veusz/veusz#184]
As I know, you can use %{{ }}% to refer to Python code. You can use it to refer to a custom definition variable in a text Label. It would be handy if you can directly refer to a custom definition as a value in the plot Points.

If I do it now with (or without the %{{ }}% ) i´ll get the following error: Unable to parse file: invalid Syntax (<string>, line 1)

**Comment by jeremysanders** [comment]
You can already do this without the %{{ }}% code. Expressions involving datasets and custom definitions can be entered as they are. Unfortunately you can't just enter the name of the definition, as Veusz checks whether this is a dataset. If you enter an expression like "dsname," or "dsname+zeros(1)" this should work.
