### ISSUE TITLE
Veusz v1.26.1 vrong fit

### ISSUE THREAD

**Issue by User32bit** [veusz/veusz#187]
The problem with fitting.
For example I try fit  x^2 from -5 to 5 by step 1 with function a+b*x.
True results y=10, but Veusz get y=0 (see fig)
[Veusz_v1.26.1_fit_bag.zip](https://github.com/veusz/veusz/files/1179993/Veusz_v1.26.1_fit_bag.zip)

![veusz_v1 26 1_fit_bag](https://user-images.githubusercontent.com/6133845/28671176-6644b528-72e4-11e7-90c7-83fc386f4da4.png)

**Comment by jeremysanders** [comment]
This probably should be in a FAQ, but veusz by default assumes fractional uncertainties on the data points when fitting. This breaks with some types of data (e.g. points near 0). Try fitting with error bars. If you don't have error bars, you can enter an expression like "myydata, 0.1" to add error bars of 0.1 when fitting to myydata.

**Comment by User32bit** [comment]
Thank you, add errors fix problem ;)
