### ISSUE TITLE
IOError: [Errno 2], Linux

### ISSUE THREAD

**Issue by andres-GHub** [veusz/veusz#188]
hi, 
When loading a .vsz file that does not contain a particular linked folder for my data, I get an "IOError: [Errno 2] No such file or directory: ..." (because I moved it somewhere else or deleted it). The issue is that now the whole .vsz file is now unusable, i.e., I can't access the rest of the data/plots etc. Perhaps having the error signal pop-up while still loading all other remaining folders (and highlighting the un-loaded data file in veusz) could be a possible solution (at the moment what I have to do is create a file with the particular directory and file in order for the .vsz file to open; which I then delete, first in veusz then the folder).
cheers

**Comment by jeremysanders** [comment]
It would be nice to fix this. To work around it, you could edit the vsz file in a text editor and remove the offending line.

**Comment by jeremysanders** [comment]
This should be fixed now.
