### ISSUE TITLE
Error valuues from a second dataset

### ISSUE THREAD

**Issue by MarkDurre** [veusz/veusz#189]
Would it, or is it, possible to have data errors from another dataset, e.g. a 1D spectrum imported from a fits file, and the errorbars from another fits file; then on XY plot widget have a field with X/Y error data. I know about the "X +- Y +-" standard import format, but it is a pain to have to export and munge text data from FITS files.
Cheers,
Mark

**Comment by jeremysanders** [comment]
Yes - you can enter `ds1, ds2` into the X or Y dataset field. Does this work for you?

**Comment by MarkDurre** [comment]
Excellent! Thank you
