### ISSUE TITLE
feature request: error handling during no datafile found

### ISSUE THREAD

**Issue by rsmarinho** [veusz/veusz#190]
I'd like to suggest a kind of error handling for the situation when a .vsz files points to a datafile that is not anymore on the directory tree. This king of error, for example.
![veusz](https://user-images.githubusercontent.com/5444241/29753835-0c50e9e8-8b7a-11e7-851b-3093158f0c8a.png)

**Comment by jeremysanders** [comment]
This would be nice to fix. The main problem that document loading happens as executing Python statements, so it's hard to fix things during that process. Some sort of wrapper around import statements might work, as currently happens for custom variable adding.

**Comment by jeremysanders** [comment]
Ok. I've fixed it.

**Comment by rsmarinho** [comment]
Thank you for the correction. =]
