### ISSUE TITLE
veusz broken after upgrade to python 3.6

### ISSUE THREAD

**Issue by wasimiqbal** [veusz/veusz#192]
I recently upgraded to fedora 26 and found that Veusz gives following error while trying to import data
or open data editor or trying to export plot. 

** ModuleNotFoundError: No module named 'DLFCN'**

After searching online I found that python 3.6 has dropped
module DLFCN, see https://docs.python.org/3.6/whatsnew/3.6.html

**Comment by jeremysanders** [comment]
What version of Veusz are you running and where did you get it from? Was it the binary from the Veusz website, the Fedora package or a build you made [yourself?

**Comment by wasimiqbal** [comment]
Thanks for quick reply.
I am using all packages from Fedora repo.
--------------------------------------------------------------------------------------------------------
Installed Packages
veusz.x86_64                                                                1.25.1-2.fc26    
python3.x86_64                                                             3.6.2-5.fc26

**Comment by jeremysanders** [comment]
Is there no more information than that, e.g. a stack trace? Veusz doesn't use DLFCN. It's likely due to one of the packages it depends on, e.g. PyQt.

**Comment by wasimiqbal** [comment]
If you tell ne how to get information that you need to trace the issue then perhaps I can do it. veusz was working great for me till I upgraded to Fedora 26.

**Comment by jeremysanders** [comment]
Normally Veusz prints it to the screen in a dialog box. Where did you see this error?

**Comment by jeremysanders** [comment]
It might be due to PyKDE, but Veusz doesn't explicitly load this:
https://bugzilla.redhat.com/show_bug.cgi?id=1456075
https://bugzilla.redhat.com/show_bug.cgi?id=1480727

**Comment by wasimiqbal** [comment]
No, Veusz is not showing  any box. It just does no do any thing when I click on import, export, data editor, preferences etc. I saw this error when I opened Veusz through a terminal.

**Comment by wasimiqbal** [comment]
Thanks, perhaps this will help me find a solution.
Thanks very much for Veusz. I am using it for all my scientific publication needs. I must say it is the best that I have used in Linux.

**Comment by jeremysanders** [comment]
I realised I have access to a F26 box. I don't see any problem if I open dialog boxes. I'm not sure what can be different on your system. Maybe the upgrade is in some weird state?

**Comment by wasimiqbal** [comment]
I have one more laptop with Fedora26 installed. 
I have not updated this laptop since last two weeks. I will check on that one. May be I am facing this issue after some recent uodate of some packages.

**Comment by wasimiqbal** [comment]
I just checked on my old laptop with Fedora 26 
and Veusz is working great. Perhaps I got this bug on my new laptop after I updated kde plasma packages yesterday. I will try to undo update and will see if it works

**Comment by wasimiqbal** [comment]
After I uninstalled python3-pykde4-4.14.3-17.fc26.x86_64, all dialogues are working again in Veusz.
Thanks for your suggestion.
