### ISSUE TITLE
Transparent background colors not rendered in PDF output using 11x17" page size

### ISSUE THREAD

**Issue by swearic** [veusz/veusz#197]
Version 2.0.1
Worked in version 1.27 but color was truncated - didn't extend the full width of the graph.

I have a grid of 4 points with error bar charts stacked horizontally
Two of the charts have background colors with transparencies set to 80 - 90%

When printing to Adobe PDF, the background colors do not get rendered.  All the other colors in the chart remain correct.

Can be reproduced by:
1. Menu->New
2. Format graph background as red with any nonzero (tried 5 - 90%) transparency
3. Print to Adobe PDF, using color and size of 11x17
4. Output will not have color
5. Print to PDF but using letter size
6. Output will have color

**Comment by jeremysanders** [comment]
How do you mean you're printing to Adobe PDF? Is this using Export->PDF, or sending to Adobe in the print dialog box? I tried transparency with a red background and exported as PDF and it seemed to work fine,

If it's something in the print dialog box, I suspect this is a bug introduced by the Qt update and not in Veusz. I don't know what it's doing differently.

**Comment by swearic** [comment]
Was using Print, not Export.  Using export seems to work fine.  I'm fine with export....
