### ISSUE TITLE
import csv: line contains NULL byte,  V2.0.1

### ISSUE THREAD

**Issue by bytelinker** [veusz/veusz#202]
Hello Jeremy Sanders,

Thank you providing this great pice of software! It's a lot fun to work with it!

Importing a csv File can cause errors, there will be a error message like "line contains NULL byte". It would be a great help, if a line number would be reportet, in order to find the error and reapir it.

Regards 
Bytelinker

**Comment by jeremysanders** [comment]
Thanks for the report. This patch should fix it.
