### ISSUE TITLE
Too few points in covariance ellipses

### ISSUE THREAD

**Issue by warrickball** [veusz/veusz#206]
I've just tried the covariance ellipse feature for the first time and discovered that the small number of points used makes the ellipse obviously not smooth. I thought they'd be at least as smooth as ellipse objects. Is it possible to either increase the number of points to an appropriate value or maybe add an option for the number of points to use (like functions)?

This is Veusz 1.27 running on Fedora 26. (I noticed Veusz 2.0 isn't in the Fedora 26 repository.)

![Simple covariance ellipse with C=0.9*np.eye(2).](https://user-images.githubusercontent.com/20858744/31629127-a6c05bb0-b2aa-11e7-8949-91df7a423611.png)

**Comment by warrickball** [comment]
Although I'm sure you'll find it as quickly as I did, I dug around in the code and found the relevant line. It's line 178 of `widgets/covariance.py`:

            x = N.linspace(0, N.pi*2, 25, endpoint=False)

I've hardcoded it to 100 for now.

**Comment by jeremysanders** [comment]
Thanks. This patch will probably do for the moment. I've added a setting for the number of line segments. Ideally I'd draw the ellipse with bezier curves, but it would only work for non-log axes, so would require special casing...
