### ISSUE TITLE
Slicing data in properties doesn't work with single element

### ISSUE THREAD

**Issue by warrickball** [veusz/veusz#207]
I've discovered that using slices of data (e.g. `x[0:8:2]`) doesn't work with single elements. If I try to plot `x[0]`, I get the error

    Error evaluating 'x[0]': None

The trivial workaround is to plot `x[0:1]`, which works fine, but I thought the single element would work too.

**Comment by jeremysanders** [comment]
Thanks - this patch appears to fix the problem.
