### ISSUE TITLE
Feature Request: folders for the data for grouping

### ISSUE THREAD

**Issue by jbaltrus** [veusz/veusz#210]
I was wondering whether Data-Veusz bar (and the corresponding data) can be grouped by creating folders for certain groups? Now I have all the data just listed there and if I have many datasets it really becomes cumbersome. Being able to group them within some subfolder (do not mix with grouping as ordering or filtering) would be much cleaner

**Comment by jeremysanders** [comment]
Have you tried tagging a dataset? Datasets can be viewed in tag groups.

**Comment by jbaltrus** [comment]
Thank you. I guess it partially does what I wanted then.
