### ISSUE TITLE
Scientific D notation in text data import yields text (not number) columns

### ISSUE THREAD

**Issue by srk** [veusz/veusz#214]
There seems to be a problem importing numbers (using 'Standard' tab) from a text file when one or more columns of numbers uses the sX.XXXXXXDsYY scientific notation, where s is a sign and X and y are digits, e.g.
0001  -0.38136473436721D+03
0002  -0.38136205411544D+03
0003  -0.38135344304051D+03

(Veusz 2.1, Windows 8.1).
Problem: the second column is detected as text, not numbers.

**Comment by jeremysanders** [comment]
Veusz only supports floating point which uses E/e rather than D/d, like Python.
