### ISSUE TITLE
data operations is broken in v. 2.1

### ISSUE THREAD

**Issue by slowphil** [veusz/veusz#215]
I wanted to multiply a data set by a constant and got this error report just as I selected the menu item:

Veusz version: 2.1
Python version: 3.5.4 (default, Aug 11 2017, 20:10:00) 
[GCC 6.3.1 20170216 (Red Hat 6.3.1-3)]
Python platform: linux
Numpy version: 1.13.1
Qt version: 5.9.1
PyQt version: 5.9
SIP version: 4.19.3
Date: mar., 07 nov. 2017 12:10:55 +0000

Traceback (most recent call last):
  File "veusz/windows/mainwindow.py", line 375, in _loadPlugin
  File "veusz/dialogs/plugin.py", line 40, in handlePlugin
  File "veusz/dialogs/plugin.py", line 88, in __init__
  File "veusz/dialogs/plugin.py", line 112, in addFields
  File "veusz/plugins/field.py", line 199, in makeControl
  File "veusz/setting/setting.py", line 1070, in makeControl
  File "veusz/setting/setting.py", line 265, in getDocument
AttributeError: 'FieldDataset' object has no attribute 'iswidget'

Frame _loadPlugin (File veusz/windows/mainwindow.py, line 375)
 self = <veusz.windows.mainwindow.MainWindow object at 0xf3a5614c>
  self.AllowNestedDocks = 2
  self.AllowTabbedDocks = 4
  self.AnimatedDocks = 1
  self.DrawChildren = 2
  self.DrawWindowBackground = 1
  self.ForceTabbedDocks = 8
  self.GroupedDragging = 32
  self.IgnoreMask = 4
  self.PdmDepth = 6
  self.PdmDevicePixelRatio = 11
  self.PdmDevicePixelRatioScaled = 12
  self.PdmDpiX = 7
  self.PdmDpiY = 8
  self.PdmHeight = 2
  self.PdmHeightMM = 4
  self.PdmNumColors = 5
  self.PdmPhysicalDpiX = 9
  self.PdmPhysicalDpiY = 10
  self.PdmWidth = 1
  self.PdmWidthMM = 3
  self.VerticalTabs = 16
  self.__dict__ = {'datatoolbar': <PyQt5.QtWidgets.QToolBar object at 0xf1269a04>, 'axisvalueslabel': <PyQt5.QtWidgets.QLabel object at 0x...
  self.__doc__ = ' The main window class for the application.'
  self.__module__ = 'veusz.windows.mainwindow'
  self.axisvalueslabel = <PyQt5.QtWidgets.QLabel object at 0xf11eddf4>
  self.console = <veusz.windows.consolewindow.ConsoleWindow object at 0xf11eda4c>
  self.datadock = <veusz.windows.datanavigator.DataNavigatorWindow object at 0xf11ed38c>
  self.datatoolbar = <PyQt5.QtWidgets.QToolBar object at 0xf1269a04>
  self.dbusdocinterface = <veusz.document.dbusinterface.DBusInterface object at 0xf1200c8c>
  self.dbuswininterface = <veusz.windows.mainwindow.DBusWinInterface object at 0xf120466c>
  self.dialogs = []
  self.dirname = '/home/pj/Ubuntu One/QPS/diamond/diamant grenoble/R(T)'
  self.document = <veusz.document.doc.Document object at 0xf12f83d4>
  self.documentsetup = True
  self.filename = '/home/pj/Ubuntu One/QPS/diamond/diamant grenoble/R(T)/R(T)1_Grenoble.vsz'
  self.formatdock = <veusz.windows.treeeditwindow.FormatDock object at 0xf11ed344>
  self.interpreter = <veusz.document.commandinterpreter.CommandInterpreter object at 0xf11fc4ac>
  self.maintoolbar = <PyQt5.QtWidgets.QToolBar object at 0xf12699bc>
  self.menus = {'data.ops.Join': <PyQt5.QtWidgets.QMenu object at 0xf126d854>, 'data.ops': <PyQt5.QtWidgets.QMenu object at 0xf126d6a4>...
  self.pagelabel = <PyQt5.QtWidgets.QLabel object at 0xf11ede3c>
  self.pickerlabel = <PyQt5.QtWidgets.QLabel object at 0xf11edd64>
  self.plot = <veusz.windows.plotwindow.PlotWindow object at 0xf12716ec>
  self.plotqueuecount = 0
  self.plotqueuelabel = <PyQt5.QtWidgets.QLabel object at 0xf11eddac>
  self.propdock = <veusz.windows.treeeditwindow.PropertiesDock object at 0xf11de53c>
  self.recentFileActions = {'filerecent4': <PyQt5.QtWidgets.QAction object at 0xf1240344>, 'filerecent3': <PyQt5.QtWidgets.QAction object at 0xf124...
  self.staticMetaObject = <PyQt5.QtCore.QMetaObject object at 0xf073f924>
  self.statusbar = <PyQt5.QtWidgets.QStatusBar object at 0xf11edd1c>
  self.treeedit = <veusz.windows.treeeditwindow.TreeEditDock object at 0xf11de344>
  self.viewwinfns = [(<veusz.windows.treeeditwindow.TreeEditDock object at 0xf11de344>, <PyQt5.QtWidgets.QAction object at 0xf1269104>, <fun...
  self.vzactions = {'file.saveas': <PyQt5.QtWidgets.QAction object at 0xf1262b6c>, 'data.ops.Subtract.Datasets': <PyQt5.QtWidgets.QAction o...
  self.windows = [<veusz.windows.mainwindow.MainWindow object at 0xf3a5614c>]
 handlePlugin = <function handlePlugin at 0xf12407c4>
 pluginkls = <class 'veusz.plugins.datasetplugin.MultiplyDatasetPlugin'>

Frame handlePlugin (File veusz/dialogs/plugin.py, line 40)
 mainwindow = <veusz.windows.mainwindow.MainWindow object at 0xf3a5614c>
 doc = <veusz.document.doc.Document object at 0xf12f83d4>
 plugin = <veusz.plugins.datasetplugin.MultiplyDatasetPlugin object at 0xf07423ec>
 pluginkls = <class 'veusz.plugins.datasetplugin.MultiplyDatasetPlugin'>

Frame __init__ (File veusz/dialogs/plugin.py, line 88)
 mainwindow = <veusz.windows.mainwindow.MainWindow object at 0xf3a5614c>
 title = 'Multiply: By constant'
 doc = <veusz.document.doc.Document object at 0xf12f83d4>
 reset = <PyQt5.QtWidgets.QPushButton object at 0xf074c02c>
 pluginkls = <class 'veusz.plugins.datasetplugin.MultiplyDatasetPlugin'>
 self = <veusz.dialogs.plugin.PluginDialog object at 0xf0738fa4>
  self.Accepted = 1
  self.DrawChildren = 2
  self.DrawWindowBackground = 1
  self.IgnoreMask = 4
  self.PdmDepth = 6
  self.PdmDevicePixelRatio = 11
  self.PdmDevicePixelRatioScaled = 12
  self.PdmDpiX = 7
  self.PdmDpiY = 8
  self.PdmHeight = 2
  self.PdmHeightMM = 4
  self.PdmNumColors = 5
  self.PdmPhysicalDpiX = 9
  self.PdmPhysicalDpiY = 10
  self.PdmWidth = 1
  self.PdmWidthMM = 3
  self.Rejected = 0
  self.__dict__ = {'gridLayout': <PyQt5.QtWidgets.QGridLayout object at 0xf074c80c>, 'fields': [], 'verticalLayout': <PyQt5.QtWidgets.QVBo...
  self.__doc__ = 'Dialog box class for plugins.'
  self.__module__ = 'veusz.dialogs.plugin'
  self.buttonBox = <PyQt5.QtWidgets.QDialogButtonBox object at 0xf074c89c>
  self.descriptionLabel = <PyQt5.QtWidgets.QLabel object at 0xf074c074>
  self.document = <veusz.document.doc.Document object at 0xf12f83d4>
  self.fieldGroup = <PyQt5.QtWidgets.QGroupBox object at 0xf074c1dc>
  self.fieldcntrls = []
  self.fields = []
  self.gridLayout = <PyQt5.QtWidgets.QGridLayout object at 0xf074c80c>
  self.mainwindow = <veusz.windows.mainwindow.MainWindow object at 0xf3a5614c>
  self.notifyLabel = <PyQt5.QtWidgets.QLabel object at 0xf074c854>
  self.plugininst = <veusz.plugins.datasetplugin.MultiplyDatasetPlugin object at 0xf07423ec>
  self.staticMetaObject = <PyQt5.QtCore.QMetaObject object at 0xf073fa04>
  self.verticalLayout = <PyQt5.QtWidgets.QVBoxLayout object at 0xf074c0bc>
 plugininst = <veusz.plugins.datasetplugin.MultiplyDatasetPlugin object at 0xf07423ec>
 descr = 'Multiply a dataset by a factor. Error bars are also scaled.'

Frame addFields (File veusz/dialogs/plugin.py, line 112)
 self = <veusz.dialogs.plugin.PluginDialog object at 0xf0738fa4>
 currentwidget = '/page2'
 layout = <PyQt5.QtWidgets.QGridLayout object at 0xf074c80c>
 field = <veusz.plugins.field.FieldDataset object at 0xf07429ac>
 row = 0

Frame makeControl (File veusz/plugins/field.py, line 199)
 self = <veusz.plugins.field.FieldDataset object at 0xf07429ac>
  self.__dict__ = {'default': '', 'document': <veusz.document.doc.Document object at 0xf12f83d4>, 'setn': <veusz.setting.setting.Dataset o...
  self.__doc__ = 'Field for selecting a datset.\n    Returns a string.\n\n    Note that the validity of dataset names is not checked\n   ...
  self.__module__ = 'veusz.plugins.field'
  self.__weakref__ = None
  self.default = ''
  self.descr = 'Input dataset'
  self.document = <veusz.document.doc.Document object at 0xf12f83d4>
  self.name = 'ds_in'
  self.setn = <veusz.setting.setting.Dataset object at 0xf074204c>
 currentwidget = '/page2'
 l = <PyQt5.QtWidgets.QLabel object at 0xf074c8e4>
 doc = <veusz.document.doc.Document object at 0xf12f83d4>

Frame makeControl (File veusz/setting/setting.py, line 1070)
 self = <veusz.setting.setting.Dataset object at 0xf074204c>
  self.__dict__ = {'parent': <veusz.plugins.field.FieldDataset object at 0xf07429ac>, 'datatype': 'numeric', 'onmodified': <veusz.setting....
  self.__doc__ = 'A setting to choose from the possible datasets.'
  self.__module__ = 'veusz.setting.setting'
  self.__weakref__ = None
  self._ref = None
  self._val = ''
  self.datatype = 'numeric'
  self.default = ''
  self.descr = ''
  self.dimensions = 1
  self.formatting = False
  self.hidden = False
  self.issetting = True
  self.issettings = False
  self.iswidget = False
  self.name = 'ds_in'
  self.nodetype = 'setting'
  self.onmodified = <veusz.setting.setting.OnModified object at 0xf1244d64>
  self.parent = <veusz.plugins.field.FieldDataset object at 0xf07429ac>
  self.readonly = False
  self.typename = 'dataset'
  self.usertext = ''
  self.val = ''
 args = (None,)

Frame getDocument (File veusz/setting/setting.py, line 265)
 self = <veusz.setting.setting.Dataset object at 0xf074204c>
 p = <veusz.plugins.field.FieldDataset object at 0xf07429ac>

**Comment by jeremysanders** [comment]
Yes - thanks. It's already fixed in the repository but I need to push out a release when I have time.

**Comment by slowphil** [comment]
fixed in 2.1.1. Thanks.
