### ISSUE TITLE
Some formats use hyphen instead of minus sign

### ISSUE THREAD

**Issue by egcarnio** [veusz/veusz#217]
Hello!
I've noticed that the formats "%g", "%e", and "%.2f" for the axes are using a hyphen instead of a minus sign, like in the other cases. Could you please switch to a minus in those cases as well, please?
Thank you for this wonderful software!

**Comment by jeremysanders** [comment]
Ok -  above should fix that. I intended to make the C formatting more "pure", but there's not much reason to do that.
