### ISSUE TITLE
PDF export is long

### ISSUE THREAD

**Issue by walafc0** [veusz/veusz#219]
Hi,

From two days, exporting into PDF cause me some trouble. During the export, Veusz is not showing any message and after a while, Ubuntu says that the application does not respond. If I do nothing and just wait for 2/4 minutes, the export eventually finished.

I am using Veusz 1.21.1 with Python 2.7.12 on Ubuntu 16.04. I tried to compile the latest Veusz version, the same thing happened. Veusz is "doing nothing" (or seems to), no error are showed, neither in the Veusz console or the terminal on Ubuntu.
Is there a possibility to compile/start Veusz in a debug mode to see what's happening during the export ?

Thanks.

**Comment by jeremysanders** [comment]
This is a very old version of Veusz and is no longer supported. Please upgrade.

There's no debug mode, except you could try running it in a console and seeing whether there are error messages.

**Comment by walafc0** [comment]
As I mentioned, the same thing happened with the latest version of Veusz that I compiled yesterday. I tried to run this version from the terminal and no error are reported. I forgot to mention that export in PNG and SVG are working as usual (I did not try the other).

**Comment by jeremysanders** [comment]
Well, if it's a particular file, you can send me the file and data. If it's everything, then it's likely to be something wrong with your linux setup.

**Comment by jeremysanders** [comment]
PS as Veusz uses CUPS, it might be a problem with your printing setup. Try the lpq command or similar and see whether there is a hang. Does the printing dialog hang when you open it?

**Comment by walafc0** [comment]
That was a CUPS issue, no default printer was set (reset for an unknown reason..). Thank you, everything works now!

**Comment by jeremysanders** [comment]
Great!
