### ISSUE TITLE
Crash with multiple input datasets

### ISSUE THREAD

**Issue by Sugestor** [veusz/veusz#220]
when using more than 3 input datasets to compute mean of datasets (or error) veusz will crash with the newst Version (2.1.1). 

[bugreport.txt](https://github.com/veusz/veusz/files/1509581/bugreport.txt)

**Comment by jeremysanders** [comment]
Thanks for the report. Sorry, but I can't reproduce the issue.  Would it be possible to make a test document and attach it here to demonstrate the problem?

**Comment by Sugestor** [comment]
Hi sry for the long delay. 
Here is a file I wrote with a python-script to get the following .vsc file, It works well on my colleagues pc (Version 1.23.2) but doesn't on my updates Version (2.1.1).

[Ausgabe.txt](https://github.com/veusz/veusz/files/1619390/Ausgabe.txt) I just renamed the .vsc in .txt

**Comment by jeremysanders** [comment]
Sorry, this is very old, but the data files are missing so I can't try this out.
