### ISSUE TITLE
Veusz.embed saves files which code is difficult to compare to files saved by using Veusz GUI because of different sorting of function's arguments

### ISSUE THREAD

**Issue by And0k** [veusz/veusz#224]
Example of same rows of two files. Second is saved by Veusz.embed (after modification of import data command in first):
DatasetPlugin('NumbersToText', {'ds_in': 'tEnd', 'format': '%VDd.%VDm.%VDY %VDH:%VDM', 'ds_out': 'txtEnd'})
DatasetPlugin('NumbersToText', {'format': '%VDd.%VDm.%VDY %VDH:%VDM', 'ds_in': 'tEnd', 'ds_out': 'txtEnd'})

or:
DatasetPlugin('PolarToCartesian', {'units': 'degrees', 'theta_in': 'Vdir', 'y_out': 'Ve', 'r_in': 'Vabs', 'x_out': 'Vn'})
DatasetPlugin('PolarToCartesian', {'x_out': 'Vn', 'theta_in': 'Vdir', 'units': 'degrees', 'r_in': 'Vabs', 'y_out': 'Ve'})

**Comment by jeremysanders** [comment]
The commit should fix the problem. We normally use a special function when writing a Python dict to sort the arguments, but this was missed for DatasetPlugin.
