### ISSUE TITLE
colorbar min and max values not working when using for marker (colored points)

### ISSUE THREAD

**Issue by wasimiqbal** [veusz/veusz#228]
I am trying to plot this one https://veusz.github.io/examples/coloredpoints.pdf
my problem is that when I use colorbar widget, its range is always 0 to 1 and not as shown in the plot in the link. When I manually set min and max for colorbar then color comes only between 0 and 1 and rest of the bar remains empty.

when I opened the source file for above plot I found following three lines below **To('xy1')**
Set('Color/min', 2.0)
Set('Color/max', 4500.0)
Set('Color/scaling', u'log')
My problem is that I am not able to set these values from GUI although when I add these lines manually in the source file it works great.

I have attached outputs with and without above lines.

![coloredpoints2](https://user-images.githubusercontent.com/31474442/35744138-d4ef67ac-083f-11e8-9271-88920c68d59a.png)
![coloredpoints](https://user-images.githubusercontent.com/31474442/35744139-d50725f4-083f-11e8-8620-64a07ee1c604.png)

Thanks

**Comment by jeremysanders** [comment]
You're probably setting it in the wrong place. The colorbar just shows the colors, it doesn't affect it. Go to the xy plotting widget and click on the "+" next to the dataset which gives the colors.

**Comment by wasimiqbal** [comment]
thanks for your reply.
I will check it and then will update. unfortunately my office is closed
now, i will be able to try it on Monday only. Sorry for delay. I myself
want to try it.

thanks.
have a good weekend.



On Feb 2, 2018 7:18 PM, "Jeremy Sanders" <notifications@github.com> wrote:

You're probably setting it in the wrong place. The colorbar just shows the
colors, it doesn't affect it. Go to the xy plotting widget and click on the
"+" next to the dataset which gives the colors.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/veusz/veusz/issues/228#issuecomment-362652382>, or mute
the thread

**Comment by wasimiqbal** [comment]
I tried what you said, perhaps I could not explain the problem well enough.
I am trying one of the example plots, the link of which I have given above.
I am using the same data points as in the example source file downloaded from the link.

The example is something like this,

there are three sets of data, **x** and **y** for xy plot and then another data set named **c** which is used to color points.
another set of data **sizef** is generated from expression and is used to scale those points.

my steps

1--- plot x and y data with circle marker and without lines.
2--- set color markers in xy widget properties to use data **c**  (please see the attached figure)
     at this point I expect that all markers should be having colours according to data in data set **c**
     but it does not happen.
Am I doing something wrong? 


Thanks,
![screenshot_20180205_105910](https://user-images.githubusercontent.com/31474442/35798721-ef38373a-0a63-11e8-977b-e7fc36c2894e.png)

**Comment by jeremysanders** [comment]
That should work. You need to click the + to the left of Color markers to set the range of c (default is 0 to 1). It's a bit hard to see in your colour theme. The colour map is set in the marker fill tab of formatting.

**Comment by wasimiqbal** [comment]
Thanks, I found the **+**.  how hidden it was. It would be great if the control panel opens by default 
when ever we select any data in **Color markers** dialogue 

![screenshot_20180205_111150](https://user-images.githubusercontent.com/31474442/35799578-7a31ea82-0a66-11e8-8b46-1408e742bc21.png)

Thanks,

**Comment by michijim** [comment]
the color bar is presumably how you make heat maps; it could use a adding that phrase to the examples, along with this hidden critical item for setting the scale; not in manual, couldn't guess from example till I found this entry.  
A strong supporter of yours missed this when recently publicizing veusz:
https://towardsdatascience.com/guide-to-creating-scientific-plots-in-veusz-cb843e68bd59  
said "no simple heatmap"; wish it was there as a z towers above a 2d histogram; or dynamically-ranged color map on points of 2d data set Jim Linnemann
