### ISSUE TITLE
rotate label widget?

### ISSUE THREAD

**Issue by deskoop** [veusz/veusz#234]
Hi, first of all I like this program a lot and hope to adopt it for many years.

Using the "barplot" example, I want to go from this (made with veuzs):
![fromthis](https://user-images.githubusercontent.com/36651277/36487780-7a7732c6-1700-11e8-87c8-c06272ec6990.jpg)

to this (edited in a graphic software, in this case inkscape):
![tothis](https://user-images.githubusercontent.com/36651277/36487809-8c64eaaa-1700-11e8-9901-db68774775ea.jpg)

How to produce the 2nd version using veusz?
For the horizontal "axis title" I just put a label with text "Time (days)". But how to do it for the vertical axis title ("Frequency")? I don't see any option to rotate a label (ie a label widget). I tried by using the y axis title (belonging to the top-left panel) but I can't position the title so far down as to reach the middle between top and bottom left panels. Does it make sense?

Any ideas? Thanks!

**Comment by jeremysanders** [comment]
Try the angle formatting setting for the label.

**Comment by deskoop** [comment]
Oh I'm a fool... I'm sorry, I was looking for it in the text properties section, my bad! 
Thanks a lot!!!

**Comment by jeremysanders** [comment]
Don't worry.

**Comment by deskoop** [comment]
One more if I may: in the 2nd version I also tried to put the bottom panels closer to the top panels (ie move them upwards). But at least with the mouse I can't (I can move them around but they don't go further up). Why?

**Comment by jeremysanders** [comment]
Maybe it's the internal margin setting of the grid, which might need to be 0, or the bottom margin of the top graphs is too large. The space is split equally by the grid widget, with an optional internal margin. The graph widgets decide how much space they get inside their fraction. You can select all the graphs together and edit their margins in one go.
