### ISSUE TITLE
Polar plots not working

### ISSUE THREAD

**Issue by Rapfod** [veusz/veusz#239]
Hi.
Have previously used Veusz 1.27 for polar plots. However, with version 2.2 (Mac OSX binary) the polar plots seem broken.
/Rapfod

**Comment by jeremysanders** [comment]
Seems fine to me. Can you say how they are broken?

**Comment by Rapfod** [comment]
Not sure exactly how, but the plot is somehow cropped in 2.2.
Adding .vsz file with polar plot, the data, and two screenshots of the plots. It's the same file, opened in Veusz 1.27 and 2.20.

![polar data 2_20](https://user-images.githubusercontent.com/37251970/37254220-64ee788a-253b-11e8-83ad-5f8bdf4682eb.jpeg)
![polar data 1_27](https://user-images.githubusercontent.com/37251970/37254221-6516e22a-253b-11e8-8364-bc6a0142ca95.jpeg)
[POLAR DATA (vsz and csv files).zip](https://github.com/veusz/veusz/files/1800394/POLAR.DATA.vsz.and.csv.files.zip)

**Comment by sahaskn** [comment]
For page zoom other than 1:1, each zoom in/out produces a different clipped figures in display(polar plot).

For xy plot with pattern fill, zooming in produces this.
![zoom](https://user-images.githubusercontent.com/26824040/37309303-8253ae44-260e-11e8-9f31-69552475975b.png)

**Comment by Boustin91** [comment]
I amhaving the same problem on ternary plots. Switching through the different layout options (left-bottom, bottom-right etc) make data points disappear. With more points I could see the plotting area is actually cropped. Reverted back to 2.1.1 and all was fine. May be a glitch that slipped through in 2.2 ?

**Comment by jeremysanders** [comment]
I think it may be due to the changes in the coordinate system introduced in 2.2. Qt must be not applying the scaling of the coordinate system to the clipping coordinates. I need to spend some time looking at this, though.

**Comment by Boustin91** [comment]
Okay thanks.
Need to say that I have been using the software for a while, including in scientific papers, and the results are brilliant.
Now MS Office is SVG compatible, it even gets into my daily presentations and documents.

Keep up the good work !

**Comment by Rapfod** [comment]
Perfect!
I am also using it for scientific papers and presentations with excellent results. 
A really nice piece of software, so many thanks from here as well.

**Comment by jeremysanders** [comment]
I think the bug is fixed with the above commit. Sorry for the delay, as it wasn't obvious why this was happening. I'll make a new release soonish.
