### ISSUE TITLE
NumPy npy plugin can not import datetime64

### ISSUE THREAD

**Issue by And0k** [veusz/veusz#241]

**Comment by jeremysanders** [comment]
For the h5py problem, do you mean the binary version? If you're running from source or using a unix/linux distribution package, it will depend on what version of hdf5 the distribution is using.

**Comment by And0k** [comment]
Yes, binary version, Windows, and last hdf5 the distribution

**Comment by jeremysanders** [comment]
Version 2.2.2 now includes HDF 1.10 in the Windows binary.

**Comment by jeremysanders** [comment]
Support for text and datetime64 data types now added in npy/npz
