### ISSUE TITLE
Virus detected in latest Veusz Windows .exe file.

### ISSUE THREAD

**Issue by tnilzon** [veusz/veusz#242]
Did a virus scan of the 'veusz-2.2.1-windows-setup.exe' file on https://www.virustotal.com/
The scan detected virus in the file. What can this be (I suspect it to be some miss-detection)?
See screen print of the virus scan result.
[VirusTotal.pdf](https://github.com/veusz/veusz/files/1840334/VirusTotal.pdf)

/Tomas Nilzon, Sweden

**Comment by jeremysanders** [comment]
This is a false positive. It's only one virus engine which claims a virus - I've contacted them to remove it. Virus engines often make mistakes and previous versions have had false positives in other engines.

**Comment by tnilzon** [comment]
OK, thanks Jeremy. That sounds revealing to know, and is what I
suspected.

Regards/ Tomas Nilzon, Sweden

**Comment by jeremysanders** [comment]
Seems to have been fixed now.

**Comment by tnilzon** [comment]
OK, grate.

Thanks/ Tomas N
