### ISSUE TITLE
Broken axes do not display correctly in v2.1.1+

### ISSUE THREAD

**Issue by susmijor** [veusz/veusz#244]
Hi,

The broken-axis widget does not display the axis scale correctly if "Min position" or "Max position" differ from their default values.

Below is the example.

Thanks,
Sergey

# Veusz saved document (version 2.2.1)
# Saved at 2018-04-06T10:29:02.562082

Add('page', name=u'page1', autoadd=False)
To(u'page1')
Set('hide', False)
Set('width', u'32cm')
Add('graph', name=u'graph1', autoadd=False)
To(u'graph1')
Set('Border/hide', True)
Add('axis', name=u'y', autoadd=False)
To(u'y')
Set('direction', u'vertical')
To('..')
Add('axis-broken', name=u'x1', autoadd=False)
To(u'x1')
Set('breakPoints', [0.2, 0.5])
Set('lowerPosition', 0.046)
Set('upperPosition', 0.939)
Set('breakPosns', [0.5])
To('..')
Add('axis-broken', name=u'x2', autoadd=False)
To(u'x2')
Set('breakPoints', [0.2, 0.5])
Set('otherPosition', 0.5)
To('..')
To('..')
To('..')

**Comment by jeremysanders** [comment]
Thanks for the bug report. The above change should fix the bug in the next release.
