### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by joukeHijlkema** [veusz/veusz#246]
Hi Jeremy. 
First of all, thanks a lot for this outstanding tool. I use it all the time.
There is, however, one thing I really would like. I normally make plots for French articles or reports but sometimes I need to reuse a graph in an English or German or Dutch text. I think it would be wonderful if I could define a certain number of labels in different languages and then just select the language to use.

Something like
if lang=="EN":
 Labels = {"P":"Pressure","T":"Temperature", ...}
elif lang=="FR"
 labels = {"P":"Pression","T":"Température",...}

and then be able to define lang and use Labels["P"] for a key text or axis label.

What do you think ?

Jouke

**Comment by jeremysanders** [comment]
I've added some functionality to do something like this. There's now a LANG function which returns the text corresponding to the user's language. In a label you can now do something like

    %{{ LANG({'de':'Druck','fr':'french translation','default':'Pressure'}) }}%

In a label. This is a bit cumbersome, though it works. I'll include it in the next release. The patch is at https://github.com/veusz/veusz/commit/c0206c2be7c4f49eba8f672ad2f88baae0e984a7

**Comment by jeremysanders** [comment]
I guess this lacks a way to choose the language. You can actually roll your own by using a label lile

    %{{ {'en':'ho','de':'foo'}[lang] }}%

And setting a custom definition for lang to be 'en' or 'de'.
