### ISSUE TITLE
Fonts looks very tiny in veusz versions greater than 2.1.101 

### ISSUE THREAD

**Issue by gadass** [veusz/veusz#250]
Dear all,

I'm having a little problem with the most updated binary versions of the veusz program. Basically, the program shows unreadable, tiny font sizes when I'm using the most updated versions of veusz, please, see the file "veusz-2.2_and_greater.png" attached.

 I'm running the program in a fresh install Ubuntu 16.04 (64 bits).  I found that the veusz-2.1.101 ("veusz-2.1.101.png") is the most updated version that I'm able to run without this problem. However, maybe you guys have some workaround to mitigate this issue in the updated version. 

Thanks in advance,

José Gadelha

![veusz-2 1 101](https://user-images.githubusercontent.com/38897885/39502153-14b5a60e-4d95-11e8-90ab-d1e260b4c50c.png)
![veusz-2 2_and_greater](https://user-images.githubusercontent.com/38897885/39502154-14fad210-4d95-11e8-9bdc-76a6540ad0b6.png)

**Comment by jeremysanders** [comment]
This is probably due to the implementation of High DPI support. I don't know what's wrong on your monitor setup or Qt settings. The fonts appear not scaled, but the UI elements are scaled. Perhaps they're somehow forced to be at fixed size? Maybe the monitor EDID information is incorrect?

There are Qt settings which affect the scaling - see http://doc.qt.io/qt-5/highdpi.html . You could try something from a terminal (if veusz is in the path) like

QT_SCALE_FACTOR=2 veusz

**Comment by jeremysanders** [comment]
By the way, you could also try the PPA version of veusz and see whether that works. It might be the version of Qt included with the veusz binary.

**Comment by gadass** [comment]
Hi Jeremy,

thank you for the fast response. So, I'm using a Thinkpad T460 notebook which has a Full HD (1920x1080) display and as you expected this issue happens only in this resolution. 

Using QT_SCALE_FACTOR=2 increase both the font and icon size, but the program becomes impossible to use, please, see attached. 

I followed your suggestion and add the repository version:

sudo add-apt-repository ppa:jeremysanders/ppa
sudo apt-get update
sudo apt install veusz

Unfortunately, this installs the veusz-1.21.1. Anyway, I manually download the 2.2.2 version (https://launchpad.net/~jeremysanders/+archive/ubuntu/ppa/+build/14546402) and now everything goes fine. Now, I'm even able to edit the GUI and fonts with qt5c app, =D.

Thank you very much for your help.

Cheers,

José Gadelha

![qt_scale_factor 2](https://user-images.githubusercontent.com/38897885/39532396-2218ac6a-4e03-11e8-8354-316c447d7de1.png)

**Comment by gadass** [comment]
Dear all,

I know this is an old post, but I was able to resolve this issue with my qt5 apps, including veusz-3.0. Modify qt setting with QT_AUTO_SCREEN_SCALE_FACTOR=0 and the program will run fine. More info can be found in https://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/

Hope this helps someone else too!

Cheers,

José Gadelha
