### ISSUE TITLE
Error bars with arithmetic on datasets

### ISSUE THREAD

**Issue by MarkDurre** [veusz/veusz#251]
I have noticed the following behaviour with error values on a simple plot. I attach example file:
(1) Plot xy1 has Xdata and Ydata (with errors) - all fine
(2) I create Ydata2 with Data > Operations > Add > Constants and add 2 to Ydata - all fine (xy2)
(3) I copy plot xy1 to xy3, then change the Y values to `Ydata+4`; the values plot OK, but the error bars disappear.
[ConstantAddIssue.vsz.zip](https://github.com/veusz/veusz/files/1990158/ConstantAddIssue.vsz.zip)

**Comment by jeremysanders** [comment]
Yes - expressions entered directly don't try to compute error bars (as in the create dataset dialog box). It's just a straightforward computation of a python expression operating on the data values. You can add multiple expressions separated by commas to compute the errors.

As it's a general python expression, it would be rather difficult to automatically compute error bars. Maybe it would be possible to work it out for simple cases and not for others.

Of course, it might be invalid to combine the errors in some datasets if the errors are correlated.
