### ISSUE TITLE
Add \hat

### ISSUE THREAD

**Issue by mmorandi** [veusz/veusz#252]
Proposed patch attached
[diff.log](https://github.com/veusz/veusz/files/1995589/diff.log)

**Comment by jeremysanders** [comment]
Looks good. I wonder if it should sit within the character bounding box so that it works in \frac, etc. It would look strange next to normal text, though.

**Comment by mmorandi** [comment]
Don't know how to do it, since qt & co are alien beasts for me. Right now the behavior matches that of \overline (i.e. it does definitely _not_ play nicely with \frac if \hat or \overline is at the denominator). I can try working on it if you can point me in the right direction....

**Comment by jeremysanders** [comment]
I'll merge the patch and we can improve it later if necessary. Thanks!
