### ISSUE TITLE
How to install this with python 3 instead of python 2 as dependence by apt?

### ISSUE THREAD

**Issue by renpj** [veusz/veusz#253]
Veusz is a very nice and friendly software to use, great thanks for the development team!
I'm trying to use ubuntu with python 3. But when I install veusz by apt command, it will install python 2 to solve the dependence issue. I don't want to install python 2. How can I solve this?
I'v tried to use the binary version, it works but I didn't find the way to use embed.py. I noticed that in the "INSTALL", it says one can add embed.py to PYTHONPATH for Win OS. But it failed for ubuntu OS. Can someone help me?
Thanks!

**Comment by jeremysanders** [comment]
Does the veusz executable work?

**Comment by renpj** [comment]
Yes, the executable works fine!

**Comment by jeremysanders** [comment]
I'm closing this as the package in the PPA is now Python 3.
