### ISSUE TITLE
Can you develop a 3D plotter in Veusz?

### ISSUE THREAD

**Issue by DaniyalKiani** [veusz/veusz#254]
We work with data that needs 3D plotting for visualization as shown in the picture. We can't use Veusz for such plots and have to revert to origin. Our lab uses Veusz otherwise for all our figures and plots. It would be very convenient if you could work towards developing a 3D plotting package. 

![urea](https://user-images.githubusercontent.com/39569661/40447424-80d1f48e-5ea0-11e8-9c57-17cc879dae5c.jpg)

**Comment by jeremysanders** [comment]
I've been working on 3D support for Veusz, which is mostly working but not released yet. That particular type of line plot isn't implemented, but there is a 3D surface plot, which is very similar and could be extended.

I expect to make an initial 3D release in the next few weeks.

**Comment by jeremysanders** [comment]
There's now a test release for 3D support: https://www.reddit.com/r/Veusz/comments/8o9dru/veusz_30_test_release/

Veusz can do something similar with the surface3d widget, turning off grid lines in one direction.

**Comment by jeremysanders** [comment]
Version 3 now released with 3D

**Comment by DaniyalKiani** [comment]
Jeremy,

This is great news ! However one quick issue: I upgraded to V3.0 from your
site but keep getting this error when i try to pull up a 3D plot example
document from the included library:




Any clues? I have already uninstalled and reinstalled the program.


Best,
Dan

**Comment by jeremysanders** [comment]
Sorry - I can't see the error. Can you try again?

**Comment by DaniyalKiani** [comment]
Does this work: ?

**Comment by jeremysanders** [comment]
No. Maybe attach directly on the bug tracker?

**Comment by jeremysanders** [comment]
If theres a bug, please report it separately.

**Comment by DaniyalKiani** [comment]
Jeremy,

I will report it again separately.

Best,
Dan
