### ISSUE TITLE
Arrowed lines look different in EPS/PS format

### ISSUE THREAD

**Issue by sahaskn** [veusz/veusz#255]
When exported in EPS/PS format (except SVG format), the arrows on the line look different than what it looks inside veusz program. 

Here is  vsz file. 

# Veusz saved document (version 2.2.2)
# Saved at 2018-05-24T23:39:10.605095

Set('colorTheme', u'default-latest')
Set('StyleSheet/Font/font', u'Calibri')
Set('StyleSheet/axis/autoRange', u'exact')
Set('StyleSheet/axis/TickLabels/size', u'12pt')
Set('StyleSheet/axis/MajorTicks/number', 4)
Set('StyleSheet/axis/MinorTicks/number', 10)
Set('StyleSheet/axis-broken/MajorTicks/number', 4)
Set('StyleSheet/axis-broken/MinorTicks/number', 10)
Set('StyleSheet/axis-function/MajorTicks/number', 4)
Set('StyleSheet/axis-function/MinorTicks/number', 10)
Set('StyleSheet/colorbar/autoRange', u'exact')
Set('StyleSheet/graph/Border/hide', True)
Set('StyleSheet/image/colorMap', u'spectrum')
Set('StyleSheet/image/colorInvert', True)
Set('StyleSheet/key/Text/size', u'13pt')
Set('StyleSheet/key/Border/hide', True)
Set('StyleSheet/key/keyLength', u'0.5cm')
Set('StyleSheet/key/marginSize', 0.25)
Set('StyleSheet/line/Line/width', u'1pt')
Set('StyleSheet/page/width', u'10cm')
Set('StyleSheet/page/height', u'10cm')
Set('StyleSheet/xy/marker', u'none')
Set('StyleSheet/xy/errorStyle', u'barends')
Set('StyleSheet/xy/PlotLine/width', u'1.5pt')
Add('page', name='page1', autoadd=False)
To('page1')
Add('graph', name='graph1', autoadd=False)
To('graph1')
Add('axis', name='x', autoadd=False)
Add('axis', name='y', autoadd=False)
To('y')
Set('direction', 'vertical')
To('..')
Add('line', name=u'array', autoadd=False)
To(u'array')
Set('arrowleft', u'arrow')
Set('arrowright', u'arrow')
Set('arrowSize', u'1.5pt')
Set('mode', u'point-to-point')
Set('hide', False)
Set('xPos', [0.243])
Set('yPos', [0.197])
Set('xPos2', [0.243])
Set('yPos2', [0.747])
Set('positioning', u'axes')
Set('Line/color', u'#000000')
Set('Line/width', u'2.5')
To('..')
Add('line', name=u'array1', autoadd=False)
To(u'array1')
Set('arrowleft', u'arrow')
Set('arrowright', u'arrow')
Set('arrowSize', u'1.5pt')
Set('mode', u'point-to-point')
Set('hide', False)
Set('xPos', [0.554])
Set('yPos', [0.199])
Set('xPos2', [0.554])
Set('yPos2', [0.749])
Set('positioning', u'axes')
Set('Line/color', u'#000000')
Set('Line/width', u'2.5')
To('..')
To('..')
To('..')

**Comment by jeremysanders** [comment]
Thanks for the report. This seems to be caused by the "miter limit" on the lines being too small, causing the PDF renderer not to make too sharp corners.

I've also taken the opportunity to move the arrow heads forward by default to avoid the line showing through the arrow head.

**Comment by jeremysanders** [comment]
Had to revert the previous change on moving the arrow heads, as this causes a gap with narrow lines.

**Comment by jeremysanders** [comment]
Ok, I found a better way of fixing this by using a flat cap on the line with the arrow head.
