### ISSUE TITLE
Help with plot line

### ISSUE THREAD

**Issue by onyema** [veusz/veusz#256]
![export1](https://user-images.githubusercontent.com/12125568/40575654-e6c0d334-613c-11e8-91f3-3e2aa3aedd92.png)

Hi Jeremy,
I have a set of data which gives a plot as shown above. I will like the plot lines to stop if it is meant it is going to join a data point that is lower than the previous data point. How can I perform that? Can I do it without splitting the dataset?

**Comment by jeremysanders** [comment]
Can you put "nan" values in your dataset in the breaks? This causes a line break.
