### ISSUE TITLE
Can not compile veusz (ubuntu 16.04)

### ISSUE THREAD

**Issue by sahaskn** [veusz/veusz#257]
Dear veusz-developer, thanks for this wonderful tool. 

I tried to compile the latest version of veusz and got the error message as:
"
veusz/helpers/src/qtloops/polylineclip.cpp: In function ‘bool doPolygonsIntersect(const QPolygonF&, const QPolygonF&)’:
veusz/helpers/src/qtloops/polylineclip.cpp:385:27: error: ‘const class QPolygonF’ has no member named ‘constLast’
       QPointF prevpt(poly.constLast());
                           ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
"

**Comment by jeremysanders** [comment]
constLast was introduced in Qt 5.6. It looks like it's Qt 5.5 on Ubuntu 16.04.

Are you able to modify "constLast" to "last" on line 385 of veusz/helpers/src/qtloops/polylineclip.cpp and see whether that fixes it, or use this patch to do it? It would be helpful to know if there are other problems.

**Comment by sahaskn** [comment]
Thanks @jeremysanders for explaining in details. After chaning consLast to last, it compiled successfully. Since in my windows 10 machine, Qt is 5.9 version, it complied without any changes. Thanks.

**Comment by jeremysanders** [comment]
Thanks - I've included the fix for the next release.
