### ISSUE TITLE
File open error

### ISSUE THREAD

**Issue by onyema** [veusz/veusz#258]
![veusz_file_openerror](https://user-images.githubusercontent.com/12125568/41074450-58ec49c0-6a5c-11e8-9f15-719619c0bbe0.PNG)

I can't seem to reopen a veusz file that once produced graphs for me after re-intallation of veusz

**Comment by jeremysanders** [comment]
There was a change in the 3d preview release off veusz that was reversed. Maybe you've hit this. You could open the file in a text editor and remove the line "Set('StyleSheet/xy/Color/data',[])".

**Comment by onyema** [comment]
Thanks Jeremy,
It did it!

**Comment by jeremysanders** [comment]
Great. You could also search and replace Color/data for Color/points
