### ISSUE TITLE
Properties column gone

### ISSUE THREAD

**Issue by WANGYCD** [veusz/veusz#259]
I updated to the latest version 3.0 but the properties column that I can adjust the scales, labels, and etc are gone. Don't know how to pull it up. Call help! Thank you.

**Comment by jeremysanders** [comment]
Can you click "View->Windows->Properties Windows"?

If this doesn't work, you could try deleting your Veusz preferences: see https://github.com/veusz/veusz/wiki/PreferencesFile

**Comment by WANGYCD** [comment]
Dear Mr. Sanders,

Got it and solve! Thank you!

Best,
Yi-Chung Wang
