### ISSUE TITLE
Export Error

### ISSUE THREAD

**Issue by McMurphy83** [veusz/veusz#262]
Dear veusz Team,

today I discovered a bug when I was trying to export my linegraph *emf (in an older version of veusz --> 2.0.1). Sadly I did not save the initial bug report... Instead of saving the bug report of the older veusz version, I upgraded to veusz version 3.0, hoping this would fix the problem.
With the current version of veusz however, the program will not even open the export dialogue anymore...

Can you help me exporting my linegraph(s)? :)

Thanks in advance

Best regards
Dennis
[bug report.txt](https://github.com/veusz/veusz/files/2114977/bug.report.txt)

**Comment by jeremysanders** [comment]
There have been some reports that old parts of veusz are left around by the uninstall of previous versions. Can you uninstall veusz, check that the Veusz directory in Program Files is empty, and reinstall again?

**Comment by McMurphy83** [comment]
Dear Jeremy,

thank you very much for your quick and helpful reply!

Problem 1: solved --> the export dialogue box opens up again after following your suggestion.
Problem 2: New error dialogue when exporting the linegraph as *emf file (veusz will export in bmp / jpg / tiff, etc. without problems.

Any idea how to export the linegraphs in emf format?

Thanks in advance

Best regards
Dennis
[bug report 2.txt](https://github.com/veusz/veusz/files/2115058/bug.report.2.txt)

**Comment by jeremysanders** [comment]
I'm glad the 1st problem is solved. Unfortunately there's probably a problem somewhere allowing "bad" data points to get to the EMF layer. Perhaps your document has some funny data values which are doing this?

If you attach your document (or send it to me privately), I can try to debug where the problem is occurring.

**Comment by McMurphy83** [comment]
Dear Jeremy, 

again, thank you very much. I would like to send you the data privately but I am not sure how.

Thanks in advance
Dennis

**Comment by jeremysanders** [comment]
Hi Dennis - It depends how big they are. If it's small (<10MB), just email the data files vsz file to jeremy@jeremysanders.net.

If it's large could you use something like dropbox and send me a link/share?

Jeremy

**Comment by jeremysanders** [comment]
Sorry for the very long wait, but I've been travelling. This looks like it's due to a broken axis part having zero length. I've added a check in the code (above), which should avoid this being drawn. I'll include it in the next release.
