### ISSUE TITLE
Scale in SVG

### ISSUE THREAD

**Issue by cherkasovn** [veusz/veusz#263]
Hi,
Veusz is a great tool - I really appreciate it. 
The problem comes from a 3rd-party Inkscape (SVG editor) who decided to make a mess with internal scaling. As a result, I can open SVG files exported from Veusz only in an older Inkscape (up to v0.91).

The newer Inkscape versions mess-up dimensions of the plots. For example, if you prepare 15x15cm image, the new Inkscape will open it as ~14x14cm image, while the old one will keep it correct. Because there seem to be no chance to roll-back this insanity for Inkscape, I wonder if it is possible to have an option in Veusz export to make the SVG files generated compatible with both old and new inkscape?

Regards,
Nikolay

**Comment by jeremysanders** [comment]
I assume it's due to this change from 90dpi to 96dpi: http://wiki.inkscape.org/wiki/index.php/Release_notes/0.92#Important_changes

Maybe writing the document size in physical units, rather than px would fix the problem. Alternatively, we could add an option for DPI (though this would only work for one or the other).

**Comment by cherkasovn** [comment]
Thanks Jeremy,
It is caused by the change in resolution, but document size in phisical units does not help. 
Build-in rescaling in inkscape creates a mess distorting fonts locations of many objects.
It would be great if you could make a check-box with 90/96 dpi for SVG export.

**Comment by jeremysanders** [comment]
Ok. I've added an option to change this. See commits up to: https://github.com/veusz/veusz/commit/7052aea14a40805a749b1a9a5b187d3cf986d2c4

**Comment by cherkasovn** [comment]
Thanks a lot Jeremy,
I will check and report once a new binary is available. I would struggle compiling the new code myself.

Thanks again,
Nikolay

**Comment by cherkasovn** [comment]
The DPI selection works well - the files generated are good both for the old and the new Inkscape.
Thanks !

**Comment by jeremysanders** [comment]
Great!
