### ISSUE TITLE
Compilation error in Win32

### ISSUE THREAD

**Issue by Pertrecho** [veusz/veusz#266]
Hello. I'm trying to compile Veusz 3.0.0 in Windows XP (32 bit), using Python 2.7.15, Qt 5.2.1, SIP 4.19.8 and PyQt5-5.10.1, and I get the following error:

\veusz-veusz-3.0.1\veusz\helpers\src\threed\properties.h(106) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

I've also tried with version 3.0.1, with the same results
What could be causing this?
Thank you.

**Comment by Pertrecho** [comment]
Also note that version 2.2.2 builds, installs and works perfectly with the same setup.

By the way, do you plan to include brief instructions on how to create a package for distribution? 
Thanks.

**Comment by jeremysanders** [comment]
Yes, Veusz 2.2.2 doesn't have that threed module, so this error is new. Which compiler are you using? I'm compiling with Visual Studio 17. The C++ code needs C++11 support. You could try changing auto on that line for double to see if that's the only problem.

I should document the process better on the wiki. I build it with the script support/veusz_windows_build_installer.py. What I have installed are

Visual Studio 17
Python 3.5 (binary from python website)
Numpy (I think this was installed via pip, so it's likely a binary)
Qt-4.11.1 (I build this by hand to disable the large space usage for icu)
PyQt/SIP (again built by hand)
Pyinstaller
NSIS installer maker

The main problem is pyinstaller and the location of qt.conf. Unfortunately I had to hack it and there's still some discussion on the pyinstaller bugs about qt5.

**Comment by jeremysanders** [comment]
Depending on what you are doing, Veusz can also be built in conda-forge: https://github.com/conda-forge/staged-recipes/pull/6175

**Comment by Pertrecho** [comment]
The idea is to build an installer that I can use to install Veusz in the old PC, without doing a full Qt/Python/etc. installation.

**Comment by Pertrecho** [comment]
Hi, i've tried replacing std::isfinite by !_finite and #include <float.h> in mmaths.h, but got several other errors. Then I tried compiling with:

Windows 7 Ultimate
Visual Studio 2012 Express (using VS2012 x86 Native Tools Command Prompt)
Python 2.7.15 (official binary)
Numpy 1.14.5 (via pip)
Qt 5.5.1 (official binary: qt-opensource-windows-x86-msvc2012-5.5.1.exe)
SIP 4.19.8 (from source)
PyQt5-5.10.1 (from source)
PyInstaller (via pip)

but got the exact same errors as before. Do you have any other suggestion that I can try to compile a 32-Bit version of Veusz? Thanks.

**Comment by jeremysanders** [comment]
Sorry - no. Someone with C++ knowledge would have to go through and try to remove any C++11 code unless you can use a newer compiler.

**Comment by jeremysanders** [comment]
Maybe this could help: http://adec.altervista.org/blog/setup-limited-c11-support-visual-studio-2012/

**Comment by Pertrecho** [comment]
OK, I'll try a proper compiler. Thanks for your help.
By the way, great work with Veusz!

**Comment by Pertrecho** [comment]
Hi, in case you want to close this issue, I wanted to let you know that Veusz did compile, install and run in Win32, with the following setup:

Windows 7 Ultimate 32 Bit
Visual C++ Build Tools 2015 Update 3
Qt 5.6.3 (official binary, last that supports XP)
Python 3.5.1 (official binary)
Numpy 1.14.5 (via pip)
SIP 4.18 (from source)
PyQt5 (official PyQt5-5.6-gpl-Py3.5-Qt5.6.0-x32-2.exe)
PyInstaller 3.3.1 (via pip)
NSIS 3,03 (official binary)

It just won't run in WinXP, as its version of kernel32.dll (5.1.2600.6532) does not have GetFinalPathNameByHandleW.

**Comment by jeremysanders** [comment]
That's a shame. I wonder which of the libraries required this symbol?
