### ISSUE TITLE
Old Gtk look with new version 3.0.1 in Windows 10

### ISSUE THREAD

**Issue by IgnacioMonge** [veusz/veusz#268]
Hi.
I've found that after the new update to Qt 5.11.1 for Windows build in version 3.0.1, Veusz looks like old GTk apps without any theme.
![image](https://user-images.githubusercontent.com/5716659/43359310-af1b7ad4-92a0-11e8-8cc0-48bf73186d82.png)

**Comment by jeremysanders** [comment]
I think it's because they've split the windowvista style into a separate plugin, which isn't being shipped in Veusz. I'll need to add this back for the next release:
https://stackoverflow.com/questions/49587418/qt-application-becomes-windows-old-styled-after-build-on-a-buildbot

**Comment by jeremysanders** [comment]
Does this fix the problem?
https://github.com/veusz/veusz/releases/download/veusz-3.0.1/veusz-3.0.1.1-windows-setup.exe

**Comment by IgnacioMonge** [comment]
It does, Jeremy.
Thank you for que quick fix.

Best regards,
Ignacio

Enviado desde Correo para Windows 10

De: Jeremy Sanders
Enviado: domingo, 29 de julio de 2018 8:34
Para: veusz/veusz
CC: IgnacioMonge; Author
Asunto: Re: [veusz/veusz] Old Gtk look with new version 3.0.1 in Windows 10(#268)

Does this fix the problem?
https://github.com/veusz/veusz/releases/download/veusz-3.0.1/veusz-3.0.1.1-windows-setup.exe
