### ISSUE TITLE
Smothless of Bezier spline is corrupted for some Graph margins and Min/Max axis values

### ISSUE THREAD

**Issue by band-a-prend** [veusz/veusz#271]
The problem is that for some values Graph margins and Min/Max axis values the Bezier spline becomes strange and looks like corrupted.

The attached file 'bezier_test.vsz' from [bezier_test.zip](https://github.com/veusz/veusz/files/2252991/bezier_test.zip) represets this behaviour.

To obtain smooth spline change 'graph1' - 'Bottom margin' from 2.5 to 5.5 for example. 

Also smoth splines could be obtained for initial graph by changing for 'y1' - 'Max' value from 0.0022 to 0.0015 - Blue line becomes more smothless but still yet strange.
Change of 'y2' - 'Max' value from 778 to 790 - Red line becomes normally smothed.

**Comment by jeremysanders** [comment]
Thanks for the report. I've made a change which fixes the problem in this case, though it would be nice to understand the code better (it was taken from another project).
