### ISSUE TITLE
multiple csv files with identical data headers

### ISSUE THREAD

**Issue by d3vr66** [veusz/veusz#278]
hi there!

in a conducted experiment I've made several temperature measurements with different experiment layouts. Each set of data is stored in it's own CSV file. I would like to make several pages in VEUSZ, showing the significant graphs. On importing, the new CSV data overwrites the existing (guess, because they are formatted equal with equal column names). A possibility to have data subsets would be much appreciated!

**Comment by jeremysanders** [comment]
Sorry for the delay. The prefix and suffix options in the import dialog are the intended way to make dataset names different in different imported files. These are added to the imported dataset names.
