### ISSUE TITLE
Can I do the same process like matplotlib.pyplot.contourf?

### ISSUE THREAD

**Issue by xichaoqiang** [veusz/veusz#281]
The countourf function in matplotlib is fill color between the coutour lines.
It is better than fill the square pixel with gradient color.
Can I get the same result in the Veusz ?

**Comment by jeremysanders** [comment]
You can fill between contour lines with a color, transparent color or a hatched area. See the "Contour fills" tab in the formatting for the contour plot.

**Comment by xichaoqiang** [comment]
![image](https://user-images.githubusercontent.com/30900789/48662772-bd47ff00-eac1-11e8-87c0-e494079eb133.png)
 How I get this result?

**Comment by jeremysanders** [comment]
With the image widget. You can place it behind the contour widget.
