### ISSUE TITLE
Function plotting wrong

### ISSUE THREAD

**Issue by af2005** [veusz/veusz#294]
I fitted a function to a dataset in Wolframs Mathematica. The output function was:

`0.44767/((x + 3.42243)**0.4105) *  1/(2.718281828**((10/3)*(x + 0.8334)**-0.758 + 0.00679) - 1) +0.102`

Veusz does not correctly plot this function (see images, black plot). E.g x=2000 should give 1.23 but in the plot it is above 1.3 (use log x axis to better show this)

Also note the number 59.8 on the y axis which is shown in the bottom left for some reason...

![screenshot from 2018-12-17 15-03-28](https://user-images.githubusercontent.com/10899721/50091979-20d26300-020d-11e9-8209-3f154234289d.png)

**Comment by mythsmith** [comment]
Are you sure 10/3 give what you think? Try 10.0/3

Il 17 dicembre 2018 15:06:44 CET, af2005 <notifications@github.com> ha scritto:
>I fitted a function to a dataset in Wolframs Mathematica. The output
>function was:
>
>`0.44767/((x + 3.42243)**0.4105) *  1/(2.718281828**((10/3)*(x +
>0.8334)**-0.758 + 0.00679) - 1) +0.102`
>
>Veusz does not correctly plot this function (see images, black plot).
>E.g x=2000 should give 1.23 but in the plot it is above 1.3 (use log x
>axis to better show this)
>
>Also note the number 59.8 on the y axis which is shown in the bottom
>left for some reason...
>
>![screenshot from 2018-12-17
>15-03-28](https://user-images.githubusercontent.com/10899721/50091979-20d26300-020d-11e9-8209-3f154234289d.png)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/veusz/veusz/issues/294

-- 
K9-mail,  Android

**Comment by af2005** [comment]
yes you are right. It should be 10.0/3 . Thanks. Any idea why the 59.8 is showing up?
