### ISSUE TITLE
confidence interval / Error band?

### ISSUE THREAD

**Issue by Red-Portal** [veusz/veusz#297]
Hi,
is there a way to draw a confidence interval without 'filling' manually between lines?

```julia
plot!(p, x_range, gp_means, ribbon=sqrt.(gp_vars) * 0.96,
        fillalpha=.5, label="gaussian process", lw=3)
```
Julia's `Plots` provide such functionality.
'riboon' fills a colored region above and below the y line.
and I was wondering if veusz already have such a feature.

**Comment by jeremysanders** [comment]
Hi - can you provide a picture of what this looks like? J

**Comment by Red-Portal** [comment]
![image](https://user-images.githubusercontent.com/18320033/50888729-a5de2000-1439-11e9-829c-947270c0e8af.png)

It shows like this

and you can provide
 ```julia
ribbon=[ mean + stddev_h , mean - stddev_h ]
```

for a confidence band asymmetric to the upper and lower region.

**Comment by jeremysanders** [comment]
Yes - you need points with error bars and to use the "fillvert" error bar style. You can add transparency in the fill options.

**Comment by Red-Portal** [comment]
You mean, I add three xy graphs and fill the region in between using 'fill' right?

**Comment by jeremysanders** [comment]
Sorry for the delay. No. not with multiple datasets. See the dataset_options example for a demonstration.

For example have an x dataset with
1
2
3
4

And a y dataset (with error bars)
2   1
4    1
9   1
16  1

Plot this, then choose an error style of fillvert. This will shade the region between the bounds of the error bars.

Alternatively, if you have datasets y1 and y2 you can plot

0.5*(y1+y2), 0.5*(y2-y1)

And choose an error style of fillvert and you should have the area between them filled.

**Comment by jeremysanders** [comment]
[example.txt](https://github.com/veusz/veusz/files/2750746/example.txt)

Rename this with vsz to load

**Comment by Red-Portal** [comment]
Thank you very much for the explanation.
