### ISSUE TITLE
Expressions in the Dataset field of Contour Widget

### ISSUE THREAD

**Issue by arichar6** [veusz/veusz#298]
I would like to be able to use expressions (e.g. "z + 1", where z is a 2D dataset) in the Dataset field for Contours. This currently works in the Image widget, but not Contours. I think that it might be because this item is a "setting.Dataset" (in addSettings method of the Contour class) instead of "setting.DatasetExtended" (in addSettings method of the Image class). I tired converting from Dataset to DatasetExtended, but couldn't figure out how to make it work. I changed it in a way that I thought should work, but the code then just ended up hanging when I tried to set the Dataset field of a contour. 

Is this something that could be changed, perhaps for a future release of Veusz?

**Comment by jeremysanders** [comment]
This will be fixed in the next release. Thanks for the report.
