### ISSUE TITLE
Extra symbols overlaid on wanted symbols in key

### ISSUE THREAD

**Issue by QL568A6** [veusz/veusz#301]
Version: 3.0.1.1
OS: Win10

For some reason, most but not all of the points in the key have an extra symbol underneath them. I've tried restarting Veusz, restarting my system, and creating a new graph. None of these helped.

![image](https://user-images.githubusercontent.com/25498543/51928470-4083ac00-23b3-11e9-9dc0-e91a65b73c36.png)

**Comment by arichar6** [comment]
Could those be the error bars? You can check by going to "Error Bar Line" in the Formatting panel, and checking the "Hide" checkbox. If those extra plus marks go away, then you know that is where they are coming from.

<img width="531" alt="image" src="https://user-images.githubusercontent.com/26064508/52227405-6ca0a080-287d-11e9-970f-9b8a03a6b82e.png">

**Comment by QL568A6** [comment]
That was it! (Hadn't checked my email this morning, but figured it out around 3:00pm)

Thank you!
