### ISSUE TITLE
min max values of plotted function differ from input

### ISSUE THREAD

**Issue by rodnikstjames** [veusz/veusz#302]
I need to plot two functions g(x) = 1.842*(x-0.0359)**2.145 and h(x) = 1.417*((x-0.0359))**1.751 in the range of x, 0.06 to 0.24. Though I gave these two as min and max x values in the properties of the function, the min and max of the plotted lines are visibly some other values. In the attached image 0.06 and 0.24 on x are marked by red vertical lines and the blue lines (functions), should end exactly on these red lines. But, as you can see they aren't. I like Veusz, but this seriously affects its credibility. Can this be corrected?

![image](https://user-images.githubusercontent.com/47322995/52210803-0e3fe600-28ae-11e9-8c86-030df60877d0.png)

**Comment by jeremysanders** [comment]
The min and max are those of the variable the function is being plotted as a function of, not the function. You could try plotting clip(myfunc, 0.1, 0.2) instead.

**Comment by jeremysanders** [comment]
It's probably because the function is evaluated in N steps (one of the settings). The min and max just select those steps between the min and max. Probably it should be more intelligent and use those as the bounds for the steps. Probably if you increase the number of steps it should approach what you want.

**Comment by rodnikstjames** [comment]
Jeremy,
Thank you. Increasing the number of steps solved the problem. I too think that the program should use the provided bounds for its steps out of the box as it is crucial. Perhaps you could implement it in the next update?
