### ISSUE TITLE
How to embed veusz with 64bit python?

### ISSUE THREAD

**Issue by stefaneidelloth** [veusz/veusz#304]
When I try to embed veusz with WinPython 3.7.1 64 bit
https://sourceforge.net/projects/winpython/files/WinPython_3.7/3.7.1.0/WinPython64-3.7.1.0.exe/download

I get a module not found error. With the 32bit version it works. 

=>Do I need to use 32 bit python to be able to embed veusz? Or do I miss something else (some kind of setting or so.)

**Comment by jeremysanders** [comment]
In theory it should work. I'd need more details about where the embed.py file is, whether it's in you python path. Is the Veusz the standard executable?

There's a possibility it's failing to find the veusz executable, but I'm not sure why you get module not found.

**Comment by stefaneidelloth** [comment]
Thank you. It seems I had an additional issue with relative paths. Now I included the absolute path to the Veusz installation directory to my python path. I use Eclipse with PyDev as IDE. Now I get

Traceback (most recent call last):
  File "D:\EclipsePython\workspace\HelloWorldExample\dataProcessing\veuszDemo.py", line 1, in <module>
    import embed as veusz
  File "D:\EclipsePython\App\Veusz\embed.py", line 48, in <module>
    import socket
  File "D:\EclipsePython\App\WinPython\python-3.7.1.amd64\lib\socket.py", line 49, in <module>
    import _socket
ImportError: DLL load failed: %1 ist keine zulässige Win32-Anwendung.

**Comment by stefaneidelloth** [comment]
Seems to be a PyDev bug. If I explicitly add Veusz to the path in my script with

import sys
sys.path.append('D:\EclipsePython\App\Veusz')

it also works with 64bit python.
