### ISSUE TITLE
1.17 breaks font selection on OS X

### ISSUE THREAD

**Issue by mroi** [veusz/veusz#31]
The font selection combo boxes in 1.17 no longer show all available fonts. They list the families, but not the different weights.

The example that I am missing is with the Gill Sans family that comes with OS X: 1.16 listed "Gill Sans" and "Gill Sans Light", but 1.17 only lists "Gill Sans". The "Light" weight is no longer accessible. Typing it in manually also does not work, the plot falls back to a replacement font (looks like Times). This makes a good number of fonts unavailable for Veusz 1.17 users. I tried this on both OS X 10.7 and 10.8 and they both show the problem.

**Comment by jeremysanders** [comment]
This is probably fixed as I've updated Qt in 3.3. Please reopen if there's still a problem.

**Comment by mroi** [comment]
The behaviour is still unchanged unfortunately. And I believe now it was a mistake (probably on Qt’s part) that it ever worked the way it did.

The right way to access all the stylistic font variants would be for Veusz to use Qt’s font property `setStyleName`. Available values can apparently be [obtained from `QFontDatabase`](https://doc.qt.io/qt-5/qfontdatabase.html#styles). Should I open a new issue as a feature request?

**Comment by jeremysanders** [comment]
If you can open up a bug that would be great. Do you have some reference on using QFontDatabase the way you suggest?

**Comment by mroi** [comment]
Sorry for the delay. I got tied up by other projects. I opened #520.
