### ISSUE TITLE
ValueError: "colorTheme" is not a setting

### ISSUE THREAD

**Issue by bradfc** [veusz/veusz#311]
I just acquired an Odroid N2 system on chip that uses ARM Cortex-A73 and runs Ubuntu 18.04 LTS.  I installed Veusz with apt-get.  I ported over a package of files from a Mac Mini that has run Veusz successfully.  When I try to run one (or any, they are similar) of my .vsz files on the N2, I get the following:
________________
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/veusz/document/loader.py", line 133, in executeScript
    cexec(compiled, env)
  File "/usr/lib/python2.7/dist-packages/veusz/compat.py", line 152, in cexec
    exec(code)
  File "<string>", line 1, in <module>
  File "/home/bkeister/g++/app/SiteRepair/Runs-3D3-N2/LA45A/surface010.vsz", line 7, in <module>
    Set('colorTheme', u'default-latest')
  File "/usr/lib/python2.7/dist-packages/veusz/document/commandinterface.py", line 374, in Set
    pref = self.currentwidget.prefLookup(var)
  File "/usr/lib/python2.7/dist-packages/veusz/widgets/widget.py", line 229, in prefLookup
    return obj.settings.getFromPath( parts[i:] )
  File "/usr/lib/python2.7/dist-packages/veusz/setting/settings.py", line 200, in getFromPath
    raise ValueError('"%s" is not a setting' % name)
ValueError: "colorTheme" is not a setting
________________

Not sure how to fix this.

**Comment by jeremysanders** [comment]
It's probably. because you're taking files from a newer version of Veusz and opening them on an older version. This isn't supported. Unfortunately Ubuntu 18.04 has a very old Veusz version provided. You'll need to compile a newer version.

As a work around you could try opening your vsz file in a text editor and remove the line which refers to colorTheme. There might be other compatibility issues, however.

**Comment by bradfc** [comment]
I forgot to check and indeed it's version 1, and I've been running version 3 (with 3D that I need).  I will try to build it, though I've tried before on another platform and got dependencies that I could not resolve.

**Comment by jeremysanders** [comment]
I'm trying to add some ARM binaries to the Veusz PPA. If this builds ok I'll let you know.

**Comment by bradfc** [comment]
That would be good.  I just started to build it, got the following error:
Traceback (most recent call last):
  File "setup.py", line 31, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'

...so I figured numpy wasn't installed, but upon running apt-get I got this:

python-numpy is already the newest version (1:1.13.3-2ubuntu1).

...so something is confused.

**Comment by jeremysanders** [comment]
Ok. It's now finished the build for arm64 or armhf for Ubuntu bionic / 18.04. You could try adding this PPA and updating: https://launchpad.net/~jeremysanders/+archive/ubuntu/ppa

**Comment by jeremysanders** [comment]
Sorry - it says the builds haven't been published yet. It might take an hour or so...

**Comment by bradfc** [comment]
No problem - I’m not in that kind of hurry!  

For now I’m still rather amazed with the Odroid N2: for about $100 I have a fully functioning machine that’s about half the speed of a Mac Mini, with 6 cores.  Eventually I’d like to get it outfitted with software packages, but in the meantime I can always run Veusz on the Mac.

I’m quite happy with Veusz and all its features!

Brad

**Comment by jeremysanders** [comment]
Should work now - let me know if it doesn't! The Odroid N2 sounds interesting.

**Comment by bradfc** [comment]
It's working - thanks!!
