### ISSUE TITLE
Generate Python code from the Veusz GUI

### ISSUE THREAD

**Issue by RTMaloney** [veusz/veusz#315]
Hi there,
is there any way we can generate a figure in the Veusz GUI, and then generate/ export the Python code so that we could then edit/reproduce in our IDE later (like you can do with Matlab figures)?
I can't find any way of doing that on the GUI.
Many thanks,

**Comment by jeremysanders** [comment]
The Veusz saved document format is a list of commands to recreate the plot. There's also the Load() API which can load a document for editing.
