### ISSUE TITLE
Cannot export to eps

### ISSUE THREAD

**Issue by jasonmold** [veusz/veusz#320]
The GUI does not allow me to select the EPS/PS option anymore. I used it a month ago just fine, and cannot understand what changed. I tried new files, old files, nothing works. 
I am using Veusz 3.0.1 on a MacOs 10.14

<img width="537" alt="Screen Shot 2019-08-02 at 6 13 57 AM" src="https://user-images.githubusercontent.com/50252996/62363211-d75d2c80-b4ec-11e9-97ca-656bc75958ff.png">

**Comment by jeremysanders** [comment]
Qt removed support for producing EPS, so now Veusz relies on ghostscript to be installed to make the EPS output. You should install this and (if necessary) point to the ghostscript executable in the preferences dialog.

**Comment by jasonmold** [comment]
Thanks! 
_port install ghostscript_ solved the issue
