### ISSUE TITLE
Reading Binary file and importing as columns of data

### ISSUE THREAD

**Issue by chelly85086** [veusz/veusz#322]
Jeremy,

Let me first say that Veusz is a very impressive plotting software and the part I like is that it can be customized for your needs. Thanks for developing it and putting it out for everyone to use

Now to the problem I am having:
I have a binary file with 30 columns of data. The data column names are in the header string which is in the first few lines of the binary file. The problem I am having is that I cannot import the data as 30 columns of data. It always imports as 1 dataset with one column of data. Your help is greatly appreciated I have attached a plugin file I wrote.

from veusz.plugins import *
import re

class ImportPluginTrial(ImportPlugin):
    """An example plugin for reading a set of unformatted numbers
    from a file."""

    name = "RFOG plugin"
    author = "Chellappan Narayanan"
    description = "Reads a list of numbers in a text file"

    # Uncomment this line for the plugin to get its own tab
    promote_tab='RFOG'

    file_extensions = set(['.bin'])

    def __init__(self):
        ImportPlugin.__init__(self)
        self.fields = [
            #ImportFieldText("name", descr="Dataset name", default="name"),
            ImportFieldInt("skip", descr="Number of lines to skip", default=15),
            ImportFieldCombo("datatype",items = ("float32", "float64",
                                "int8", "int16", "int32", "int64",
                                "uint8", "uint16", "uint32", "uint64"),
                             default="float64", editable=False),
            ImportFieldCombo("endian",items=("little", "big"), editable=False),
            ImportFieldInt("length", descr="Length (values)", default=-1)
            ]

    def getNumpyDataType(self, params):
        """Convert params to numpy datatype."""
        t = N.dtype(str(params.field_results["datatype"]))
        return t.newbyteorder( {"little": "<", "big": ">"} [
                params.field_results["endian"]] )

    def doImport(self, params):
        """Actually import data
        params is a ImportPluginParams object.
        Return a list of ImportDataset1D, ImportDataset2D objects
        """
        #f = params.openFileWithEncoding()
        f = open(params.filename,"rb")
        data = []
        skip = int(params.field_results["skip"])
        header = [next(f).decode('latin-1') for x in range(skip)]
        parts = header[9].split(':')
        numfields = int(float(parts[1].strip()))
        retn = f.read()
        f.close()
        FieldNames = [header[10][i:i+20] for i in range(0,len(header[10]),20)]
        FieldNames = [x.strip(' ') for x in FieldNames]
        FieldNames = ["Time" if x == 'Elapsed Time' else x for x in FieldNames]
        FieldNames = [('Ch'+str(i-1)) if j == '' else j for i,j in enumerate(FieldNames)]
        FieldNames.remove('\n')
        name = "  ".join(FieldNames[:numfields])

        try:
            data = N.fromstring(retn, dtype=self.getNumpyDataType(params),
                                count=int(params.field_results["length"]))
        except ValueError as e:
            raise ImportPluginException(_("Error converting data for file '%s'\n\n%s") %(params.filename, cstr(e)))

        data = data.astype(N.float64)
        L = int(len(data)/numfields)
        datlen = L*numfields

        #newdata = data.reshape(numfields,L)
        #dataList = list(N.transpose(data))
        #datamer = zip(FieldNames,dataList)

        return [ImportDataset1D(name, data)]

# add the class to the registry. An instance also works, but is deprecated
importpluginregistry.append(ImportPluginTrial)

**Comment by jeremysanders** [comment]
Hi - I sent you the below by email. Did you not get it?


You should return one ImportDataset1D object for each dataset you want to create. Therefore you should return a list of 30 ImportDataset1D objects at the end of the doImport function. I'd transform the data into a list of 30 lists, then make a list of 30 names and do something like:

    ..
    out = []
    for d, n in zip(data, names):
       out.append(ImportDataset1D(n, d))
    return out

**Comment by chelly85086** [comment]
No, I did not receive your earlier e-mail. Thanks for your help. As you can
already tell, I am new to python and I am using your software to learn.

Chelly
