### ISSUE TITLE
Conditional functions

### ISSUE THREAD

**Issue by dlmv** [veusz/veusz#324]
Is it possible to plot a conditional function?
For example, functions "**max(x,1)**" or "**x if x>1 else 1**" yield error:

> Error evaluating expression in function widget 'function1': 'The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()'

At the same time conditons without variables work: "**max(2,1)**" or "**2 if 2>1 else 1**" result in 2

**Comment by jeremysanders** [comment]
The expressions are evaluated in python, with the arguments as numpy arrays.

To do a conditional you need
    where(x>1, x, 1)

**Comment by dlmv** [comment]
Thank you, it works.
