### ISSUE TITLE
dropouts in 2D data used for contours

### ISSUE THREAD

**Issue by gary14lex** [veusz/veusz#326]
Hi Jeremy,
I could not function without Veusz!  Beautiful problem.  

I have come across a problem with 2D data sets do not appear to be created properly - every other column is zero.  The attached zip has a readme with a description of the problem and two folders with nearly identical calculations.  "turbulent" is correct but "thermal9" has the dropouts.  
[veusz.zip](https://github.com/veusz/veusz/files/3590493/veusz.zip)

**Comment by gary14lex** [comment]
These two plots show the scope of the problem.  Both have very similar data sets, only the values are different.  
[turbulent.pdf](https://github.com/veusz/veusz/files/3596597/turbulent.pdf)
[thermal.pdf](https://github.com/veusz/veusz/files/3596599/thermal.pdf)

**Comment by jeremysanders** [comment]
I'm travelling this week - I'll have to look at this when I return
