### ISSUE TITLE
[Veusz 3.1] ValueError: PyCapsule_GetPointer called with incorrect name

### ISSUE THREAD

**Issue by bvqbao** [veusz/veusz#336]
Hi,

I just updated veusz to version 3.1 and veusz refused to start with the following error:

```
Traceback (most recent call last):
  File "/usr/bin/veusz", line 11, in <module>
    load_entry_point('veusz==3.1', 'gui_scripts', 'veusz')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/veusz/veusz_main.py", line 32, in <module>
    from veusz import utils
  File "/usr/lib/python3/dist-packages/veusz/utils/__init__.py", line 22, in <module>
    from .textrender import Renderer, FontMetrics, latexEscape
  File "/usr/lib/python3/dist-packages/veusz/utils/textrender.py", line 30, in <module>
    from . import points
  File "/usr/lib/python3/dist-packages/veusz/utils/points.py", line 25, in <module>
    from ..helpers.qtloops import plotPathsToPainter
ValueError: PyCapsule_GetPointer called with incorrect name
```
I'm on Ubuntu 18.04.

Thanks,
Bao Bui

**Comment by jeremysanders** [comment]
How did you install it? Package, building, binary...?

**Comment by bvqbao** [comment]
I installed veusz via this ppa:

https://launchpad.net/~jeremysanders/+archive/ubuntu/ppa

**Comment by jeremysanders** [comment]
Which distribution do you have?

I'd suggest trying "apt remove *veusz*" to remove everything, then reinstall with 'apt install veusz'.

The packaging has been moved to closer to the debian one.

**Comment by bvqbao** [comment]
I'm on Ubuntu 18.04 Bionic.

I have tried to purge veusz and its dependencies and reinstalled it but the error remains.

Maybe there are some conflicts in terms of dependencies? With the above error, do you know which dependency I should check first?

**Comment by zboraon** [comment]
Same error here

**Comment by jeremysanders** [comment]
Hmmm... I'm using disco where it works ok. I just made a new bionic virtual machine. It seems fine there too.

Do you have anaconda or some other PyQt installed? This could interfere with the installed one.

You could also try the command `locate qtloops` to see whether there is an old installation of veusz somewhere.

**Comment by jeremysanders** [comment]
It might be useful to see

    locate sip | grep -F .so

too

**Comment by bvqbao** [comment]
I have python-pyqt5 (5.10.1+dfsg-1ubuntu2) installed. I removed it and reinstalled veusz, still no helps.

```
sudo apt install veusz
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  python3-numpy python3-pyqt5.qtsvg python3-veusz python3-veusz.helpers
Suggested packages:
  gfortran python-numpy-doc python3-nose python3-numpy-dbg python3-astropy python3-h5py
The following NEW packages will be installed:
  python3-numpy python3-pyqt5.qtsvg python3-veusz python3-veusz.helpers veusz
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 3,106 kB of archives.
After this operation, 16.5 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 python3-numpy amd64 1:1.13.3-2ubuntu1 [1,943 kB]
Get:2 http://ppa.launchpad.net/jeremysanders/ppa/ubuntu bionic/main amd64 python3-veusz.helpers amd64 3.1-1~ppa1~bionic1 [225 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic/universe amd64 python3-pyqt5.qtsvg amd64 5.10.1+dfsg-1ubuntu2 [26.8 kB]
Get:4 http://ppa.launchpad.net/jeremysanders/ppa/ubuntu bionic/main amd64 python3-veusz all 3.1-1~ppa1~bionic1 [472 kB]
Get:5 http://ppa.launchpad.net/jeremysanders/ppa/ubuntu bionic/main amd64 veusz all 3.1-1~ppa1~bionic1 [440 kB]
```

And this is the output of `locate qtloops`:

```
/usr/lib/python3/dist-packages/veusz/helpers/qtloops.cpython-36m-x86_64-linux-gnu.so
```

And `locate sip | grep -F .so`:

```
/home/baobui/.local/lib/python3.6/site-packages/PyQt5/sip.so
/usr/lib/python2.7/dist-packages/sip.x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/sip.cpython-36m-x86_64-linux-gnu.so
/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.16/sipix_blink2.so
/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.16/sipix_web2.so
```

**Comment by jeremysanders** [comment]
Hi 

> And `locate sip | grep -F .so`:
> 
> ```
> /home/baobui/.local/lib/python3.6/site-packages/PyQt5/sip.so
> ```

It looks like you have a version of PyQt5 and sip locally built. Can you delete the directory ` /home/baobui/.local/lib/python3.6/site-packages/`?  (this might break any other locally-built PyQt5 apps)

**Comment by jeremysanders** [comment]
Sorry - I made a mistake - make sure you have PyQt5 at the end of that path, as in my edited comment

**Comment by jeremysanders** [comment]
Actually, `pip3 uninstall PyQt5-sip PyQt5` might be safer.

**Comment by bvqbao** [comment]
Ok. The local sip lib installed on my machine is the problem. I just renamed the local PyQt5 directory and veusz can start now.

Thank you for your helps.

**Comment by zboraon** [comment]
> Actually, pip3 uninstall PyQt5-sip PyQt5 might be safer.
This worked for me also. Thank you Jeremy.

**Comment by jeremysanders** [comment]
Great!

**Comment by tetukowski** [comment]
> Actually, `pip3 uninstall PyQt5-sip PyQt5` might be safer.

Hi Jeremy,  I've tried this solution, it works, unfortunately there's another python package that doesn't work because of this uninstallation. Is there any other way around? It happens both  in ubuntu 18.04 & 20.04. 
I really want to try this software. Thanks

**Comment by jeremysanders** [comment]
@tetukowski You should probably use a python virtual environment to put your pip-installed packages in. This will keep them separate from the system packages. Alternatively, you can install veusz using pip (this requires having the right build setup, however). I don't think there's any other option.

**Comment by tetukowski** [comment]
@jeremysanders, thanks for your reply. Unfortunately I don't know anything about virtual environment. Before posting previous question, I have tried to install using `sudo pip3 install veusz`, because I saw it on pypi.org, but it failed (long red colored message). Is there any guide for 'build the right setup'? This seems to be a nice software, but my skill on Linux is really limited.

**Comment by tetukowski** [comment]
@jeremysanders. I tried to use the venv. Now it works fine. I will try your software. Thanks for the help!
