### ISSUE TITLE
how to plot vertical line in veusz?

### ISSUE THREAD

**Issue by bsmile001** [veusz/veusz#345]
Is there a function which draws a vertical line at a give x location in veusz? If not, how can I possibly do that? Many thanks!

**Comment by bsmile001** [comment]
just figured out we can plot a line using a line widget and there, specify range of plotting.

**Comment by jeremysanders** [comment]
Yes - you can also plot a function, x(y)=some number

**Comment by bsmile001** [comment]
oh, that's so good solution! Will you reopen the post I posted? I was
thinking I found the solution and closed it. I would like to add your
solution there.

But I do have a question towards your suggestion, how to specify
parameters to the function widget in case I would like to use x(y)? I
tried it but with error saying name y is not defined.

Thanks!
Jon

**Comment by jeremysanders** [comment]
Oh, it will be searchable even if closed. You have to change the variable in the function from x->y, then enter your value as the function.
