### ISSUE TITLE
Curve fitting residual

### ISSUE THREAD

**Issue by SergeyRa** [veusz/veusz#353]
**_Hello!_**

I found Veusz very useful in curve fitting, but was a little bit surprised by a non-standard way Veusz treats uncertainties of imported data during fitting procedure.

In the figure below the same dataset was imported:
(a) with no vertical errors specified;
(b) with all vertical errors set as 1;
(c) with vertical errors set as a square root of value;
(d) with vertical errors set to be equal to value itself.

The ways (b) and (c) are those generally used to perform non-weighted and Poisson-weighted fitting; the way (d) is not something I used or meet before. However, after performing Gaussian fitting for these datasets (see figure below), I found that in case when data uncertainties are not explicitly specified, Veusz uses exactly the strange (d) way to treat data uncertainties. One can see, that the resulting fitting is not the best possible.

![Fit](https://user-images.githubusercontent.com/42113408/71412844-046bd080-2682-11ea-8c95-ccc9f686cb73.png)

**Comment by jeremysanders** [comment]
Thanks- yes it's an issue for many kinds of data.

The current default is a fraction of y (5% if I remember, correctly). This is ok for some kinds of data. In particular, I originally used it for plotting data in log-log space, where this is the norm.

Maybe a simple fix would be to add a switch to change the default errors (if none are specified) to the above.

I've intended for a while to rewrite the fitting routines to be more user friendly, but haven't had the time.
