### ISSUE TITLE
PNG Export takes too long

### ISSUE THREAD

**Issue by StSav012** [veusz/veusz#354]
When I use veusz 3.1.1 to plot some three XY lines of 1M points each, it draws within a couple of seconds. However, when I ask it to export the plot as PNG (have not checked other formats yet), it takes at least 15 minutes for 4th page of such plots. It seems, the more images I want to export, the slower it gets. Now it's already half an hour for the 7th page. What's to check?

**Comment by jeremysanders** [comment]
That's strange. It should the same code doing the drawing in the PNG and on the screen. You could try bringing up the console window and typing

   Export('out.png', page=0, dpi=100)

Where the page number is a zero-indexed page number (pagenumber-1). Does that take as long?

**Comment by mythsmith** [comment]
If you are exporting plots with milions points, I suggest to also monitor the memory/swap usage.


Il 25 dicembre 2019 19:42:20 CET, Jeremy Sanders <notifications@github.com> ha scritto:
>That's strange. It should the same code doing the drawing in the PNG
>and on the screen. You could try bringing up the console window and
>typing
>
>   Export('out.png', page=0, dpi=100)
>
>Where the page number is a zero-indexed page number (pagenumber-1).
>Does that take as long?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/veusz/veusz/issues/354#issuecomment-568921677

-- 
K9-mail,  Android

**Comment by StSav012** [comment]
@jeremysanders, it does take the same time. However, for me, it takes 2.2592 seconds to export a page at DPI = 100, but 107.4 seconds for DPI = 300 that I need for my report to look clear. Shouldn't it take just 9 times more time, i.e. some 20 seconds? 

@mythsmith, the memory is more than enough.

BTW, is there a way to move https://github.com/veusz/veusz/blob/09faf0fb77e9721b0b74f67e23040c9523e5d3ed/veusz/document/export.py#L217 to a new thread or (better) a new process? The Veusz interface hangs during exporting.

**Comment by jeremysanders** [comment]
@StSav012 : Yes - I'd expect 9x as long, if memory is no issue. I can have a go trying to replicate the issue. If you can make a simplified testcase, that would be helpful.

It might be possible to move the code to another thread, at least for the bitmap output. Veusz already does that for rendering to the screen, by first saving in a compact vectorized format, then passing to another thread. The problem here is that the document needs to be consistent when rendering, so some output needs creating in the main thread.

**Comment by mythsmith** [comment]
I have a doubt about the 9x duration. How does Veusz decides if a point is actually visible or not? 
Suppose you have 1mln points within -1 and 1 in both x and y. If you plot them in a scale -100/100 they will appear as a single point and I imagine veusz will discard most of them. 
But if you plot them in the correct scale (-1/1), or you increase the resolution so much that they become distinguishable, then veusz will need to distinctly plot each of them. 
If some mechanism of this sort is involved in veusz or in Qt, I would not expect times to be proportional to resolution, but roughly exponential until all points become visible.

**Comment by jeremysanders** [comment]
I've just committed some code which does the exporting in separate threads. If you can build from source, feel free to try it out.

**Comment by jeremysanders** [comment]
Closing this as we now export different pages in different threads.
