### ISSUE TITLE
Bug: undefined variable

### ISSUE THREAD

**Issue by StSav012** [veusz/veusz#356]
Source:
https://github.com/veusz/veusz/blob/7e8a479729ca5d9ba599b79f797cdbc5346f9192/veusz/veusz_main.py#L93

I should be `tracebackobj`, not `trackbackobj`.

There are typos in comments around the line, too.

**Comment by jeremysanders** [comment]
Thanks for the report. This fixes the bug, and now implements showing the exception dialog if it occurs in a different thread.
