### ISSUE TITLE
Bug: typo

### ISSUE THREAD

**Issue by StSav012** [veusz/veusz#357]
Source:
https://github.com/veusz/veusz/blob/7e8a479729ca5d9ba599b79f797cdbc5346f9192/veusz/utils/dates.py#L198

It should be `=`, not `==`.

And what's the reason for
https://github.com/veusz/veusz/blob/7e8a479729ca5d9ba599b79f797cdbc5346f9192/veusz/utils/dates.py#L40
? It breaks `ctime` values.

**Comment by jeremysanders** [comment]
Thanks for finding the typo - that's fixed.

The epoch date is different to make it more accurate for times around now. You should be trivially able to convert between different epochs.
