### ISSUE TITLE
Bug: default argument is mutable

### ISSUE THREAD

**Issue by StSav012** [veusz/veusz#358]
Source:
https://github.com/veusz/veusz/blob/7e8a479729ca5d9ba599b79f797cdbc5346f9192/veusz/setting/setting.py#L1471

Default argument values are evaluated only once at function definition time, which means that modifying the default value of the argument will affect all subsequent calls of the function.

Change the function to
```python
    def __init__(self, name, val, widgettypes=None, **args):
        """Choose widgets from (named) type given."""
        Setting.__init__(self, name, val, **args)
        if widgettypes is None:
            widgettypes = {}
        self.widgettypes = widgettypes
```

Same here:
https://github.com/veusz/veusz/blob/7e8a479729ca5d9ba599b79f797cdbc5346f9192/veusz/setting/setting.py#L1799

Solution:
```python
    def __init__(self, name, value, settingsfalse=None, settingstrue=None,
                 **args):
        """Enables/disables a set of settings if True or False
        settingsfalse and settingstrue are lists of names of settings
        which are hidden/shown to user
        """

        if settingstrue is None:
            settingstrue = []
        if settingsfalse is None:
            settingsfalse = []
        self.sfalse = settingsfalse
        self.strue = settingstrue
        Bool.__init__(self, name, value, **args)
```

**Comment by jeremysanders** [comment]
Thanks for the suggestion. I'm pretty sure these are currently safe, as the values are never modified.
