### ISSUE TITLE
Some tutorial icons incorrect

### ISSUE THREAD

**Issue by davidhbrown** [veusz/veusz#360]
Several of the tutorial icons are incorrectly displayed as the Blank Page icon. The first is seen where you're asked to activate the Line tab to change the color of the x**2 function
![image](https://user-images.githubusercontent.com/749520/71561775-fda9d880-2a48-11ea-8d64-bd7b37413536.png)
(Version 3.1, Windows.)

**Comment by jeremysanders** [comment]
Thanks for the report. I've fixed the bug for the next release.
