### ISSUE TITLE
Bug: `init_fragments_size` decreased not enough

### ISSUE THREAD

**Issue by StSav012** [veusz/veusz#363]
Change
https://github.com/veusz/veusz/blob/fc70a611d41ab862186484208c97276922545801/veusz/helpers/src/threed/scene.cpp#L621
into
```c++
while(init_fragments_size > 65536)
```
to keep `init_fragments_size` value reasonable even in `fragments.size()` is much larger than `65536`.

**Comment by jeremysanders** [comment]
Is this a problem in practice? Probably `init_fragments_size = min(fragments.size(), 65536)` would be better than the loop.

**Comment by StSav012** [comment]
Indeed, it would be. As you might know, I deal with large datasets, so I want the software I use to be the best possible. Thanks a lot for the great piece of software.
