### ISSUE TITLE
Scatter Plots that Overlap

### ISSUE THREAD

**Issue by CrimpOn** [veusz/veusz#365]
I LOVE this graphing program!

I am comparing two measuring instruments.  Each produces a data file of time/quantity, where time goes from 0-24 in thousandths of a second and quantity from 45 to 125.  Quantities are integers.  Plot one is red.  Plot 2 is blue. When the values overlap, I cannot distinguish which is "on top".  What I would like is for a third color when they overlap.  i.e. different = red or blue.  overlap = black.
My "workaround" is to add 0.5 to every value in data file 2 so that they cannot overlap.  This obviously would not work if the data was not confined to integers.
Did I miss a method to give overlapping symbols a third color?

**Comment by mythsmith** [comment]
You can play with transparency. You will see the combined color when they overlap. Transparency is also very useful to have and idea of the variation of density of the data points.


Il 11 gennaio 2020 01:48:41 CET, CrimpOn <notifications@github.com> ha scritto:
>I LOVE this graphing program!
>
>I am comparing two measuring instruments.  Each produces a data file of
>time/quantity, where time goes from 0-24 in thousandths of a second and
>quantity from 45 to 125.  Quantities are integers.  Plot one is red. 
>Plot 2 is blue. When the values overlap, I cannot distinguish which is
>"on top".  What I would like is for a third color when they overlap. 
>i.e. different = red or blue.  overlap = black.
>My "workaround" is to add 0.5 to every value in data file 2 so that
>they cannot overlap.  This obviously would not work if the data was not
>confined to integers.
>Did I miss a method to give overlapping symbols a third color?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/veusz/veusz/issues/365

-- 
K9-mail,  Android

**Comment by CrimpOn** [comment]
That is a GREAT solution.  Thanks!

**Comment by jeremysanders** [comment]
Thanks - closing now.
