### ISSUE TITLE
Bug: typo: too many ‘e’s

### ISSUE THREAD

**Issue by StSav012** [veusz/veusz#369]
https://github.com/veusz/veusz/blob/eeec1e2e5abf2fa69b71c517142bd08581f2d1a9/veusz/widgets/polygon.py#L36

And what's the variable for?

**Comment by jeremysanders** [comment]
Thanks very much for the bug report.

This variable (without the typo) says whether the widget type should be createable by the user. Currently the only effect is to decide whether to make a stylesheet for the widget type. With this typo, no stylesheet was created. The stylesheet holds the settings in Edit->Default styles.
