### ISSUE TITLE
'Glass sphere' interactive rotation of 3-d plots?

### ISSUE THREAD

**Issue by srk** [veusz/veusz#373]
Excellent program, extremely flexible!
Would it be possible, when viewing the Properties of a 3-D graph or scene, to activate a 'glass ball' or 'trackball'-style interactive means to freely rotate the view by mouse-dragging, and have this reflected immediately in the Rotation value slider widgets?

**Comment by jeremysanders** [comment]
Yes - I mean to add something like this, but it's not trivial to add - I need to think about the 3D maths some more...

**Comment by jeremysanders** [comment]
Done in the latest release
