### ISSUE TITLE
Properties, Formatting, Editing etc windows only appear tabbed, and not stacked

### ISSUE THREAD

**Issue by brianluff** [veusz/veusz#375]
When I first installed Veusz the Formatting etc windows appeared as in the documentation, stacked vertically to the left of the plot window. I tried having them free-floating, but didn't like them that way. Now I can't get them to go back to how they were (even after reinstalling).  I can drag them into the right area, but each one occupies the whole of the sub-window so each one can only be seen by clicking its tab. It was far preferable to have them stacked from top to bottom of the window so they were all on show at the same time.  If anyone has overcome this problem, I'd be interested to know how to return to the status quo ante. (I'm using Ubuntu 18.04.4)

**Comment by jeremysanders** [comment]
If I have a tabbed properties window, I'm able to drag the title at its top away, to make it free floating or below/above another window.

If this doesn't work, you could try deleting your preferences file: `~/.config/veusz.org/veusz.conf` . This will delete other settings, however.

**Comment by jeremysanders** [comment]
To only delete the windows setting, you can delete the line with `geometry_mainwindowstate` from the preferences file. Note Veusz shouldn't be running if you modify or delete this file.

**Comment by brianluff** [comment]
Thanks so much for taking the time to answer this. Your first suggestion solved my problem immediately. It's easy when you know how!  I'll remember the other two tips of course.
