### ISSUE TITLE
sip -b option 

### ISSUE THREAD

**Issue by mchatzikos** [veusz/veusz#378]
Hello,
I am trying to install veusz on a Centos 7 machine, but I get the following error:

`running build_ext

    building 'veusz.helpers.threed' extension

    /path/to/bin/sip5 -c build/temp.linux-x86_64-3.7 -n PyQt5.sip -t Qt_5_14_0 -t WS_X11 -I /path/to/share/sip/PyQt5 -b build/temp.linux-x86_64-3.7/threed.sbf veusz/helpers/src/threed/threed.sip

    usage: sip5 [-h] [-V] [-a FILE] [--abi-version VERSION] [-B TAG] [-c DIR] [-D]
                [-e] [-f] [-g] [-I DIR] [-j FILES] [-n NAME] [-o] [-P] [-r]
                [-s SUFFIX] [-t TAG] [-w] [-x FEATURE] [-X ID:FILE] [-y FILE]
                [FILE]

    sip5: error: unrecognized arguments: -b veusz/helpers/src/threed/threed.sip

    error: command '/path/to/bin/sip5' failed with exit status 2
`

I have checked the sip5 documentation, and there is no `-b` option.  See [here](https://www.riverbankcomputing.com/static/Docs/sip/legacy_command_line_tools.html#sip5).

What is the best way forward?

Thanks.

**Comment by jeremysanders** [comment]
I don't know. I'm only using sip4, which works ok. It still seems to be the one shipped in linux distributions. I haven't found any resources explaining what has changed and how to upgrade. The Riverbank people seem to want to make it harder and harder to use. If anyone wants to spend some time investigating this, please do.

**Comment by jeremysanders** [comment]
Veusz now supports sip5 in current development. This should work ok in the next release.
