### ISSUE TITLE
Shorter axis lines?

### ISSUE THREAD

**Issue by Red-Portal** [veusz/veusz#379]
Hi! I'm really enjoying `veusz`, thanks for the great package!
I'm curious though if we can use shorter axes like the example below.

![2020-02-21_11-42](https://user-images.githubusercontent.com/18320033/74999664-97b55c80-549f-11ea-9a47-3f982d4af190.png)

This is the default style of JASP and I find it pretty cool.

**Comment by jeremysanders** [comment]
Have a look at the isolated axes example. You can define the endpoints of axes as a fraction of the total plot size (or drag the marker at the end).

**Comment by Red-Portal** [comment]
@jeremysanders Thanks, I'll take a look.
