### ISSUE TITLE
Changing order of plotters in key

### ISSUE THREAD

**Issue by uba00** [veusz/veusz#380]
Dear Veusz Developer,

A modification in Key widget so that the plotters widget can be ordered according to user defined ordering. 

The result is :
![image](https://user-images.githubusercontent.com/41398547/75214856-834dba00-5754-11ea-82a8-1393abc106bb.png)

The file is: 
[key.py.txt](https://github.com/veusz/veusz/files/4248091/key.py.txt)

Thanks for wonderful software "Veusz"!

**Comment by schoggi** [comment]
I would it find really useful to have freedom in arranging the order of keys

**Comment by schoggi** [comment]
This is so because the Fill feature of Plots forces me to have a certain order, see example below, and this order is not the one I prefer in the Key.

![image](https://user-images.githubusercontent.com/48128877/75661920-8245ec80-5c6e-11ea-87bc-9cea3b3a808f.png)

**Comment by jeremysanders** [comment]
Thanks for the suggestion and fix. I put in a similar fix to the source code, allowing the order to be defined by a comma-separated list.
