### ISSUE TITLE
Background color when exporting to png?

### ISSUE THREAD

**Issue by schoggi** [veusz/veusz#385]
Hi,
when I export a page to png, the background color seems to stay transparent although I set it to, say, white. When exporting to the other bitmap formats, choosing a backgrond color works fine. 

Is this a bug?

Regards,

Pietro

**Comment by jeremysanders** [comment]
Probably not. Most formats don't support transparency, unlike PNG. Try setting the alpha channel in the colour dialog to 255, rather than 0.
