### ISSUE TITLE
Support for tilde in text label

### ISSUE THREAD

**Issue by uba00** [veusz/veusz#390]
Dear Jeremy and Veusz developers, 

It will be good to have  a support for a command similar to \tilde. I had modified  in textrender.py to support the feature but with \wtilde command.

![image](https://user-images.githubusercontent.com/41398547/76946625-53688100-68d2-11ea-91bc-5172c8c4d29c.png)

[changes.py.txt](https://github.com/veusz/veusz/files/4348155/changes.py.txt)

**Comment by jeremysanders** [comment]
Thanks very much for the suggestion and implementation. I've put a version in with minor changes to the repository for the next release.
