### ISSUE TITLE
wrong svg width and height - veusz 3.2 export

### ISSUE THREAD

**Issue by guerreiro-osorio** [veusz/veusz#391]
after update to version 3.2, svg export is not setting the correct width and height

where I had:
<svg width="1771.65px" height="944.88px"

now I have:
<svg width="17716.53px" height="9448.81px"
but as all svg elements are positioned as before, the image ends up very small at the top left corner

After editing the svg file to enter previous width and height, the svg image showed OK

**Comment by jeremysanders** [comment]
Thanks for the report. I've put a fix in for this. I'll try to make a 3.2.1 bug fix release soon.
