### ISSUE TITLE
FIltering based on flags

### ISSUE THREAD

**Issue by MarkDurre** [veusz/veusz#394]
Hi,
I've been having a look at the Filter Data functionality. I was wondering if there is a method of filtering a dataset based on another e.g. filter y where flag=1, assuming that y and flag were datasets of the same length e.g.
y       | flag
-------|-----
1.9     | 0
2.5     | 1
13.8   | 2
59.6   | 1
39.3   | 0

etc.
would only plot the 2.5 and 59.6 values. This would enable subset plotting.

**Comment by jeremysanders** [comment]
Yes - you can just go to data filter, enter an expression flag==1, and choose your datasets to be filtered. Enter a suffix or prefix for the output datasets.

It might be nice to have a filter built into the plot widget, however.

**Comment by MarkDurre** [comment]
Thanks for that, I was looking in Data>Operations>Filter rather than Data>Filter.
Cheers
