### ISSUE TITLE
Scientific notation numbers recognised as text and imported as nan

### ISSUE THREAD

**Issue by DeSjeik** [veusz/veusz#400]
Version: 3.2.1
Operating System: macOS 10.14.6

I am trying to import a .csv file into Veusz.
A MWE of what I am trying to do is:
file.csv:
x (numeric),y (numeric)
1.1E1,1.2E3

This should yield 2 1D datasets
x: 11
y: 1200

However it yields the following
x: nan
y: nan

**Comment by jeremysanders** [comment]
I can't reproduce this problem on my test system. Are you sure you haven't changed the CSV import settings to use a different delimiter? Try repeating after pressing the reset button.

**Comment by DeSjeik** [comment]
Thanks for your reply! 
As you can see, the following happens:
<img width="647" alt="Screenshot 2020-04-24 at 20 32 44" src="https://user-images.githubusercontent.com/2302007/80245430-f303f680-866a-11ea-8f31-4ad20575023c.png">
Selecting Data

<img width="749" alt="Screenshot 2020-04-24 at 20 33 19" src="https://user-images.githubusercontent.com/2302007/80245459-031bd600-866b-11ea-998e-dd9afbe29de4.png">
Imported as nan.

For now, I have now managed to circumvent this problem by writing a CSV Import plugin using `pandas`.

**Comment by jeremysanders** [comment]
I've tried the same settings as you and it still works for me. I suppose it's either the Mac OS version (I'm running an old one) or the locale. Can you try selecting "English" under Locale->Numerics?

**Comment by DeSjeik** [comment]
Switching locale to English solved it!
Strange though, since my system is set to EN/US
