### ISSUE TITLE
Ubuntu PPA: package is missing for focal (Ubuntu 20.04 LTS "Focal Fossa")

### ISSUE THREAD

**Issue by DoctorRover** [veusz/veusz#404]
In the Veusz PPA (https://launchpad.net/~jeremysanders/+archive/ubuntu/ppa), the package is missing for the recently released Ubuntu 20.04 LTS "Focal Fossa". It is impossible to install Veusz from packages for previous releases because of broken dependencies.
Please add the package for focal. This is especially important as this release if LTS.
Thank you!

**Comment by jeremysanders** [comment]
Thanks for letting me know. I've added a focal version. Can you try it out and let me know if there's a problem?

**Comment by DoctorRover** [comment]
I have just successfully installed Veusz in Ubuntu 20.04.
Thank you for fixing the issue so quickly! :)
And thank you for creating Veusz! It is a great tool to make high quality publication-ready plots :)

**Comment by fightthepower** [comment]
@jeremysanders @DoctorRover 
I am getting this error when I tried to install it in ubuntu 18.04

```
W: Failed to fetch http://ppa.launchpad.net/jeremysanders/ppa/ubuntu/dists/bionic/main/i18n/Translation-en  Could not connect to ppa.launchpad.net:80
```

**Comment by jeremysanders** [comment]
@fightthepower : maybe it's a temporary problem with ubuntu's servers. Maybe try again later?
