### ISSUE TITLE
Cannot load space separated csv file from command line

### ISSUE THREAD

**Issue by bhanudaysharma** [veusz/veusz#412]
I tried loading a data file (with {space} as the delimiter) using following command, but VEUSZ imported that data as text and merged all columns in one single column. 
```
ImportFileCSV('E:/test/output.csv', readrows=False, dsprefix='', dssuffix='', linked=False, encoding='utf_8', renames={})
```
So, is there any way to specify delimiter while reading csv file using command line?

I assume the cause of this problem is the wrong delimiter because I was able to read this file properly after changing the delimiter to the comma using the following python commands: (future visitors to this thread who are new to the python like me may find it handy).

```
import csv

reader = csv.reader(open("input.csv", newline=None), delimiter=' ')
writer = csv.writer(open("output.csv", 'w'), delimiter=',')
writer.writerows(reader)
```

**Comment by jeremysanders** [comment]
This is not properly documented, but you can add `delimiter=' '` on your command line. If you import through the GUI, then save, you should see the options. I should add this to the manual. The name {space} is specific to the GUI and is translated to a space character.

**Comment by jeremysanders** [comment]
I have changed the documentation here: https://github.com/veusz/veusz/commit/4b8a2f22e641ca141d3737dc0e24242b866f4682

**Comment by bhanudaysharma** [comment]
@jeremysanders  I have seen the changes. Thank you for the update.  It would be great if we can mention that the user need not to provide all the arguments. We can mention the default values of these arguments in the manual. and then state that if not specified, the VEUSZ takes default values of these arguments. 

Thank again.
