### ISSUE TITLE
Is there a way to load a script containing commands from VEUSZ command line?

### ISSUE THREAD

**Issue by bhanudaysharma** [veusz/veusz#413]
I have several input files to be processed. I need to plot their data in a common fashion. Therefore, I loaded one of these files and set up the plot. Now, if I use the GUI, I just need to import the next file and it's data replaces the previous data, and the plot gets updated automatically. Then I just need to export the plot to a file. 

I wish to do this second part (i.e., importing new file and exporting the image file) from the command line in a batch mode. So, I use the following commands: 
```
ImportFileCSV('E:/Simulations/test/output.csv', readrows=False, dsprefix='', dssuffix='', linked=True, encoding='utf_8', renames={})

Export('E:/Simulations/test/filename.pdf', color=True, page=0, dpi=100, antialias=True, quality=85, backcolor='#ffffff00', pdfdpi=150, svgtextastext=False)
```

Is there any way that all these commands can be placed in a file and later can be executed by calling that file?

Although, I am able to do it by editing the saved .vsz file in a text editor and then pasting these commands in the end of the .vsz file, is there a way that VEUSZ can load a file containing only these commands?

I have tried the 'Load('filename.vsz')' command, but that requires a complete .vsz file.

**Comment by jeremysanders** [comment]
You can do

    exec(open("./filename").read())

from the command line. Alternatively, you could write a "Tools plugin" which is some Python code which attaches to the menu and allows you to automate tasks. These can pop up windows for parameters.

**Comment by bhanudaysharma** [comment]
Thanks @jeremysanders . It worked.  Is it possible to collect all such question under one label, may be "How to's". I have checked that there are currently two labels on VEUSZ's github repo: '3D' and 'packaging'
