### ISSUE TITLE
Key widget: Title color is always black

### ISSUE THREAD

**Issue by BrainStormCenter** [veusz/veusz#414]
Greetings, 

FYI: Although the color of text in a key can be changed, there is no option to change the color of the title in either the properties or formatting tabs of the key widget. 

Cheers,
Jason

**Comment by bhanudaysharma** [comment]
@BrainStormCenter I checked it and you are right. But as a makeshift solution, you can use 'Text Label' widget to manually place the title over the key box. Just make sure that you keep this widget above the 'Plot Key' in the tree, and uncheck the 'hide' checkbox in the background tab of the 'formatting'.

**Comment by BrainStormCenter** [comment]
Thanks for letting me know about the workaround. 
Cheers,
Jason

**Comment by jeremysanders** [comment]
Should be fixed in the next release.
