### ISSUE TITLE
Bar chart group pattern different from stacked bar chart

### ISSUE THREAD

**Issue by peterg1t** [veusz/veusz#417]
Hi,
First of all I would like to say that Veusz is one of the best scientific software for data processing. Intuitive and powerful there are not many alternatives to it. The issue I'm reporting concerns the fill styles of bar charts. While in grouped mode every bar can be filled with a different style as the following image shows.
![image](https://user-images.githubusercontent.com/8771255/82955071-41a6f800-9f6b-11ea-9124-57925792b471.png)
When changing the mode to stacked there is a overlay between the different columns hinting that the pattern is not stacked. I would expect to each box to have their individual pattern.
![image](https://user-images.githubusercontent.com/8771255/82955179-7b77fe80-9f6b-11ea-90c5-ce7d780dcb39.png)
If i switch them all to solid I get the correct individual colors for each box
![image](https://user-images.githubusercontent.com/8771255/82955314-cbef5c00-9f6b-11ea-9629-f8afba7b7fc7.png)
Each box in stacked correctly with their individual colors, but this does not happens with the fill patterns.
Thank you very much for this wonderful software.

Pedro

**Comment by bhanudaysharma** [comment]
It would be great if you could upload a sample data file to reproduce this chart. However, did you try to play with the transparency of objects? Though I am not sure whether this will work or not.

**Comment by peterg1t** [comment]
[Geom-issue-Veusz.zip](https://github.com/veusz/veusz/files/4693533/Geom-issue-Veusz.zip)

Hi Bhanuday,
Here is a file with the data to reproduce this. Changing the mode from stacked to grouped allows you to see the problem. In grouped each bar has a unique pattern while as in stacked the patterns overlay to other bars. I did not fin a transparency option for the fill.
Best regards, 
Pedro

**Comment by bhanudaysharma** [comment]
If this is what you want, then you can go to second tab in 'formatting' and then click on 'two dots' (find them in right-hand side). Then you need to uncheck 'back-hide' checkbox. 

![Geom-submit-Veusz_01](https://user-images.githubusercontent.com/55601693/83106121-9072a000-a0d9-11ea-917e-139548dc6f7a.png)

**Comment by peterg1t** [comment]
Aha! That does it. It is that in my version I cannot see the dots. The button has the same color as the background and makes it invisible! but if I click on the empty space based on your picture the menu does indeed appear. I'm using version  3.1-2.fc32 for Fedora Workstation. I will close this issue. Thanks for your help!

![image](https://user-images.githubusercontent.com/8771255/83155240-43cd9b80-a0be-11ea-8fd2-9c0f4f5afab4.png)
