### ISSUE TITLE
Feature request: Add more functionality to "Zoom into graph"

### ISSUE THREAD

**Issue by matheger** [veusz/veusz#421]
Currently, the "Zoom into graph" tool in the main window toolbar does exactly what it says - it lets you zoom into a chosen area in the graph. However, it also does _exclusively_ what it says, meaning that once you've zoomed in you lack any interactive tools to pan the graph, zoom out, or reset to previous zoom steps. I feel that this is sorely missing.

Basically, my suggestion is to implement a similar set of tools as we already have for zooming the entire page.

**Comment by jeremysanders** [comment]
A workaround is to use the "undo" functionality to undo the previous steps.

**Comment by bhanudaysharma** [comment]
I don't know which version you are using. But I am using Veusz 3.2.1 on Windows 10 Laptop. In this version there are options for Zoom in or zoom out. Moreover, I can use two-finger gesture to zoom in or zoom out (by increasing/decreasing the distance between these two fingers) as well as can pan the graph by moving two fingers keeping the distance between them constant. 


![veusz scroll](https://user-images.githubusercontent.com/55601693/84187824-3b0e9980-aab0-11ea-945d-fd3d12c73d32.gif)

**Comment by matheger** [comment]
@bhanudaysharma This moves the page, not the data inside the graph.

**Comment by kaugummiheld** [comment]
@bhanudaysharma Like @matheger said, it's about the feature to zoom/pan inside a graph. It's precisely the button to the zoom button you showed.  
I get that most of this functionality could be done with the page zoom, like you showed, but there are use cases where you want it like @matheger was describing.

**Comment by kaugummiheld** [comment]
I just saw that #136 deals with exactly this. What is the opinion on this solution?

**Comment by matheger** [comment]
I don't understand how that pr deals with this issue... care to explain?

**Comment by mjo68** [comment]
Can somebody please be assigned to this issue? I fully agree with Matheger that it would help a lot. I use the zoom graph function frequently to zoom into a specific time series area of interest. The inability to zoom-out (other than using undo) makes it cumbersome, e.g. when you make a change after you zoom in you also have to undo that change in order to return to the original un-zoomed graph.

**Comment by jeremysanders** [comment]
Everyone contributing to the project is a volunteer, so it's not possible to assign someone or make promises about adding features. I'm happy to help someone if they'd like to work on this issue.

**Comment by mjo68** [comment]
> Everyone contributing to the project is a volunteer, so it's not possible to assign someone or make promises about adding features. I'm happy to help someone if they'd like to work on this issue.

I wish I had programing experience, I'd do it immediately.

**Comment by jeremysanders** [comment]
I've implemented some new graph zoom functionality:

* The zoom button also works when clicking or by drawing a rectangle. Clicking zooms in on the clicked point.
* There's a new zooming out button. Clicking zooms out around the clicked point.
* There's a new graph recenter button. Clicking moves the axes to centre on the point clicked.
* There's a new graph reset button. Clicking resets the axes to 'Auto'

**Comment by jeremysanders** [comment]
Now available in the 3.3.1 release.

**Comment by mjo68** [comment]
Brilliant. Thanks Jeremy, super useful!

**Comment by matheger** [comment]
Thank you, Jeremy! Very nice addition.

I'd have another suggestion for the new "zoom out" behaviour - basically, to make the user draw a rectangle (like for "zoom in") and rescale the current graph contents to that rectangle. Would that be possible? Should I open a new issue for that?

**Comment by jeremysanders** [comment]
@matheger I think that would be technically difficult, as 1) it could only work if the rectangle was drawn on the page, not off the page itself, and 2) it would be hard to work out which graph was being zoomed out (if there was more than one)

**Comment by matheger** [comment]
Fair enough. The new functionality is very helpful already, so I'm looking the gifted horse in the mouth here anyway. :)
