### ISSUE TITLE
Suggestion: Easy shortcut for Show/Hide

### ISSUE THREAD

**Issue by kaugummiheld** [veusz/veusz#424]
Hello at all! 

I'd like to give a little life-improvement suggestion at least for me: 
I usually explore data visually by simply plotting, discarding noise and outliers etc. I'd find a shortcut for toggling hide and show for a selected object in the Editing widget more than useful.
If I remember correctly, in OriginLab you could do this by selecting e.g. a graph and pressing [space] and I'd love the same feature within Veusz. 

At all: Please write if you'd like it too. Or if not, why that. Thanks!

**Comment by bhanudaysharma** [comment]
I think a small checkbox in front of the name of widget would also do the job.

**Comment by jeremysanders** [comment]
Thanks for the suggestion. The user will be able to use Ctrl+[ and Ctrl+] for hiding and showing the selected widgets in the next release.
