### ISSUE TITLE
More options in barends

### ISSUE THREAD

**Issue by Leonardo-Velasco** [veusz/veusz#428]
Hi,

I wonder if it can it be possible to add an option to remove the lower end in error style (A), to get a bar like in the attached file (B).

Thanks!

![A](https://user-images.githubusercontent.com/68272416/87403017-a1f60580-c5bc-11ea-9bce-b93071c2991d.jpg)

![B](https://user-images.githubusercontent.com/68272416/87403390-17fa6c80-c5bd-11ea-9389-8e0738ced639.jpg)

**Comment by bhanudaysharma** [comment]
I don't know whether it is currently possible with veusz. But if it is not, then I can suggest you two possible work-arounds.-
1. Edit the final image in an image editor as you might have done to create this second image.
2. For your personal viewing purpose, you can use any value of lower error and ignore it. Then, when you create the publication-ready graph, just copy-paste the same bar-plot-widget in the same graph and hide it's error bars. Then you move this second widget above the first widget in the 'editing-veusz' pane. In this way, the second widget will cover the first widget and your lower error bounds will be covered-up by the bar chart.

**Comment by Leonardo-Velasco** [comment]
> I don't know whether it is currently possible with veusz. But if it is not, then I can suggest you two possible work-arounds.-
> 
> Edit the final image in an image editor as you might have done to create this second image.
> For your personal viewing purpose, you can use any value of lower error and ignore it. Then, when you create the publication-ready graph, just copy-paste the same bar-plot-widget in the same graph and hide it's error bars. Then you move this second widget above the first widget in the 'editing-veusz' pane. In this way, the second widget will cover the first widget and your lower error bounds will be covered-up by the bar chart.

Thank you for your comments. Yes, using a vectorial editor of the svg file such as Inkscape is a good option. However, I would like to see this possibility implemented in Veusz.

**Comment by jeremysanders** [comment]
I've merged a commit to add some top and bottom half error bar styles which should fix this issue. This will be in the next release. Thanks for the suggestion.
