### ISSUE TITLE
Line Styles Affect Arrow Heads

### ISSUE THREAD

**Issue by matheger** [veusz/veusz#429]
Adding a line using the "Shape" elements, giving it an arrow head, and setting a non-solid line style affects the outline of the arrow head as well. I'd expect it to remain a solid outline.

![arrow](https://user-images.githubusercontent.com/34485360/88122453-e3bb1900-cb85-11ea-99bd-25bebf86f732.png)

**Comment by jeremysanders** [comment]
Thanks for the report. This will be fixed in the next release.
