### ISSUE TITLE
Veusz fails to start if Plugin has some error or missing.

### ISSUE THREAD

**Issue by funky12** [veusz/veusz#43]
Hi,

Trying to load a plugin in the latest version, the issue is that if plugin has the indentation error or any error, the Veusz fails to start, and if plugin is removed or changed location then also. 

1) When plugin has errors

![image](https://f.cloud.github.com/assets/5168119/1052252/21cc7590-10da-11e3-887e-5bcb93fc8398.png)

2) If plugin is missing

![image](https://f.cloud.github.com/assets/5168119/1052240/f51726bc-10d9-11e3-816b-56f3af5201b6.png)
!

This lets the user not to start the tool as it preempts

**Comment by jeremysanders** [comment]
This is fixed now.
