### ISSUE TITLE
Bug: Calculation boxplot

### ISSUE THREAD

**Issue by kaugummiheld** [veusz/veusz#449]
Hey, 
I stumbled upon what I assume is a bug in the calculation procedure of the boxplot quantities by Veusz, i.e. the lower and upper quartile aka the edges of the box. While the calculation of median seems to be fine, as middle value in the ordered array or the average of the two most middle value in case of a even numbered dataset, I found some weirdness in the quartiles. 

Since I wasn't sure I found a (unfortunately german) [Wikipedia article](https://de.wikipedia.org/wiki/Interquartilsabstand_(Deskriptive_Statistik)) with a formula which I didn't found on the english article: 
![Screenshot_20200925_161430](https://user-images.githubusercontent.com/61326100/94277743-43e58700-ff4a-11ea-9b86-dd39bd84a064.png)
("ganzzahlig" means whole-numbered or integer)
I read it as: Only for the case where the quartile would be exactly in the middle (from the ordering perspective) of two value the average is taken, otherwise the next bigger value is taken. 

###  Examples: 
My set is `1,2,3,4,5`. 
The median is of course `3` and since `n*0.25 = 1.25` is non-integer the quartiles should be `2` and `4`, right? 
This is exactly what Veusz is presenting me: 
![boxplot-5elements](https://user-images.githubusercontent.com/61326100/94278322-f4538b00-ff4a-11ea-9b11-8195433431a5.jpg)

My set is now `1,2,3,4,5,6`. 
The median should be calculated as average of 3 and 4 (`3.5`) and since `n*0.25 = 1.5` is non-integer the quartiles should be `2` and `5`, right? 
![boxplot-6elements](https://user-images.githubusercontent.com/61326100/94278558-43012500-ff4b-11ea-97e8-f4b55dc4ebde.jpg)
The median is correct, the quartiles are somehow non-integer and are therefore not in the original dataset. Am I missing something here?

I was having a look into this since the whiskers of my dataset seems to be off. I had a dataset roughly like `2,6,6.1,6,6,6.1,6,6` and would assume that 2 would be markes as an outlier, since it should be way outside the `1.5*ICR` (difference between upper and lower quartiles), but it isn't: 
![boxplot-dataset](https://user-images.githubusercontent.com/61326100/94279259-27e2e500-ff4c-11ea-9e0f-c2b4ed8acd4c.jpg)

I would be really glad if someone could help me here out. Either by confirming that this is indeed a bug or by explaining to me where my error of logic lies. :neutral_face: 
Thanks in advance! :+1:

**Comment by kaugummiheld** [comment]
Update: 

I found an [online boxplot calculator ](http://www.alcula.com/calculators/statistics/box-plot/) and ran my data through it: 
`` 1.880961, 6.328371, 6.458574, 6.53204, 6.535456, 6.567634, 6.567826, 6.646693 ``

Here the two boxplot images: 

Online tool:
![image](https://user-images.githubusercontent.com/61326100/94559625-d2674a80-0261-11eb-9a59-07984f4bfaf2.png)

Veusz:
![ringFET-analysis](https://user-images.githubusercontent.com/61326100/94559930-3be75900-0262-11eb-8900-2a6873562ca1.jpg)

**Comment by jeremysanders** [comment]
According to English wikipedia, there's no commonly agreed way to calculate this: https://en.wikipedia.org/wiki/Quartile

Currently Veusz uses the numpy percentile function to calculate this, which uses linear interpolation.

**Comment by kaugummiheld** [comment]
Thanks for having a look. :+1: 

_(I'm no native speaker, so please be patient with me when I try to explain my thoughts.)_ 

I had a look at the [numpy.percentile function](https://numpy.org/doc/stable/reference/generated/numpy.percentile.html) and there seems to be an option for choosing the interpolation procedure. One could implement an option for that in the Veusz gui, but that all doesn't even seem to be the problem in that case. 
The quartile values seems to be rather accurate (compare the upper and lower edge of the box in the boxplot for the two graphs above). But the plotting of the fences/whisker and therefore identification of outliers seems to be off.

When I read the wikipedia article you cited, the `1.5*IQR` option (default in Veusz) seems the standard. 

For my case: 
```
>>> data = np.array([1.880961,6.328371,6.458574,6.53204,6.535456,6.567634,6.567826,6.646693])
>>> Q1,Q3 = np.percentile(data,25),np.percentile(data,75)
>>> Q1, Q3
(6.42602325, 6.5676820000000005)
>>> IQR = Q3 - Q1 
>>> Q1 - 1.5*IQR , Q3 + 1.5*IQR
(6.213535125, 6.7801701250000015)
```
As far as I understand it, these are the maximum and minimum allowed values for whiskers, respectively.
(In my case, 6.32.. and 6.64.. since that are the most extreme points of my dataset inside the `Q1 - 1.5*IQR , Q3 + 1.5*IQR` range.)
That means all datapoints outside that should be identified and marked as outliers, shouldn't they? But that seems not the case (cf. last plot above). So I think the problem lays somewhere here.

**Comment by kaugummiheld** [comment]
I had a look into the `widgets/boxplot.py`-file over the weekend and played a little bit with different datasets. 

I think there's an error in the definition of the botwhisker (in 1.5IQR mode):
```
elif whiskermode == '1.5IQR':
            iqr = self.topquart - self.botquart
            eltop = N.searchsorted(cleaned, self.topquart+1.5*iqr)-1
            self.topwhisker = cleaned[eltop]
            elbot = max(N.searchsorted(cleaned, self.botquart-1.5*iqr)-1, 0)
            self.botwhisker = cleaned[elbot]
```

### Example 1: 

Previous dataset (cf. comment above)
`data = N.array([1.880961,6.328371,6.458574,6.53204,6.535456,6.567634,6.567826,6.646693])`
results in 
```
median: 6.533748,
botquart: 6.42602325, 
topquart: 6.5676820000000005, 
mean: 5.939694375
```
With `iqr = 0.1416587500000004` the bounds should be 
```
topbound: 6.7801701250000015 = topquart - 1.5*iqr
lowbound: 6.213535125 = botquart - 1.5*iqr
```
The whisker denote the most extreme (max/min) values of the original dataset inside these bounds: 
```
[1.880961,<6.328371>,6.458574,6.53204,6.535456,6.567634,6.567826,<6.646693>]
```
And now what the code gives us: 
```
eltop = N.searchsorted(cleaned, self.topquart+1.5*iqr)-1  >> 7
self.topwhisker = cleaned[eltop] >> 6.646693 (the right one)
elbot = max(N.searchsorted(cleaned, self.botquart-1.5*iqr)-1, 0) >> 0 (one index too low)
self.botwhisker = cleaned[elbot] >> 1.880961 
```
**Assumption:** The elbot is -1 off. Since one should be rounding up and not down, the `-1` in the code seems to be wrong. 

### Example 2:

Mirrored dataset with other extreme (top outlier):
`data = N.array([6.328371,6.458574,6.53204,6.535456,6.567634,6.567826,6.646693,12.880961])`
results in 
```
median: 6.551545,
botquart: 6.5136734999999994, 
topquart: 6.58754275,
mean: 7.314694375
```
With `iqr = 0.07386925000000044` the bounds should be 
```
topbound: 6.698346625000001 = topquart - 1.5*iqr
lowbound: 6.402869624999999 = botquart - 1.5*iqr
```
The whisker denote the most extreme (max/min) values of the original dataset inside these bounds: 
```
[6.328371,<6.458574>,6.53204,6.535456,6.567634,6.567826,<6.646693>,12.880961]
```
And now what the code gives us: 
```
eltop = N.searchsorted(cleaned, self.topquart+1.5*iqr)-1  >> 6
self.topwhisker = cleaned[eltop] >> 6.646693 (the right one)
elbot = max(N.searchsorted(cleaned, self.botquart-1.5*iqr)-1, 0) >> 0 (one index too low)
self.botwhisker = cleaned[elbot] >> 6.328371 
```
**Assumption:** Same as above.

### Proposed change: 

Changing line 90 from 
```
elbot = max(N.searchsorted(cleaned, self.botquart-1.5*iqr)-1, 0)
```
to 
```
elbot = max(N.searchsorted(cleaned, self.botquart-1.5*iqr), 0)
```
should fix the problem.
