### ISSUE TITLE
The 'logarithmic' mode for the X axis does not seem to work.

### ISSUE THREAD

**Issue by taghoter** [veusz/veusz#450]
First of all, lots of thanks for your wonderful program.

I think I have found a bug concerning the logarithmic mode for the X axis, that seems not to work. For the Y axis it does work, but for the X it seems it does not. I attatch two pictures for comparing the case I've found.

Greetings.

![Screenshot_20200928_121315](https://user-images.githubusercontent.com/9280127/94425733-52b77e00-0184-11eb-98dc-fd577766f796.png)
![Screenshot_20200928_121336](https://user-images.githubusercontent.com/9280127/94425747-58ad5f00-0184-11eb-82ef-6e6fbf75072d.png)

**Comment by jeremysanders** [comment]
Thanks for the report.

There's likely something else causing the problem in the document, as log x axes work normally. If you can upload an example vsz file with the problem that would be great.

**Comment by taghoter** [comment]
I am using these data. I find especially strange what the x axis looks like in these pictures. It might happen I am not seeing something...

I attatch a 'csv' file compressed as a zip, since it does not allow me to attatch the csv file itself.

Thanks a lot and greetings.


[grf04b.zip](https://github.com/veusz/veusz/files/5292123/grf04b.zip)

**Comment by jeremysanders** [comment]
The data does what I expect. The data only have a narrow range (80 to 100). A log scale between a narrow range looks almost exactly the same as a linear scale. If you plot log(x) on a linear scale instead of x on a log scale you should see the same affect.

**Comment by jeremysanders** [comment]
I'm closing this now, but please reopen if you think there is still a bug.
