### ISSUE TITLE
Get current console path

### ISSUE THREAD

**Issue by matheger** [veusz/veusz#454]
Is there a way to get the current path of the console window? I can of course change the path with the `To()` command, but sometimes I just want to see what location I am in. If this functionality already exists, it doesn't seem to be very well documented in the manual. Otherwise I would suggest adding it.

**Comment by jeremysanders** [comment]
I don't think it exists, unfortunately. One workaround is to use the new API which keeps track of the current location:

     >>> Root.page1.graph1.path
     '/page1/graph1'

**Comment by jeremysanders** [comment]
Thanks - this is fixed in the next release. The `CurerentPath()` function should return the current widget path.
