### ISSUE TITLE
Additional color maps

### ISSUE THREAD

**Issue by Dobrodzieju** [veusz/veusz#458]
Dear All,
After quite a long hiatus I have (re)discovered Veusz. It looks very promising,
thanks to the continuous efforts of the developers team. Thank you very much.
Let me join to this list by contributing several additional color maps, 
which I have adopted from gnuplot/matplotlib sites: parula, viridis,
plasma, magma, inferno, moreland. See the attached zip file.
[custom-pal.zip](https://github.com/veusz/veusz/files/5430623/custom-pal.zip)

**Comment by jeremysanders** [comment]
Thanks very much for the contribution. These should be in the next release.
