### ISSUE TITLE
Feature Suggestion: A NetCDF import

### ISSUE THREAD

**Issue by Swanekamp** [veusz/veusz#461]
NetCDF is a popular data format and it would be great if there was a built-in import feature in VEUSZ.

**Comment by jeremysanders** [comment]
I'm happy if someone wants to implement this. Probably they should look at the hdf5 layer. I've never worked with NetCDF.

However, isn't NetCDF a layer on HDF5? Does the HDF5 import work?

**Comment by ssgromov** [comment]
Use the netCDF v.4 format which is natively supported by HDF import plugin. Version 3 is anyway too old now.

**Comment by jeremysanders** [comment]
@ssgromov : thank you for the information. I'll close this bug in that case.
