### ISSUE TITLE
Question: How to use a column as errors for another column?

### ISSUE THREAD

**Issue by StSav012** [veusz/veusz#462]
Dear developers,

I have CSV files that get updated by an external application. So, I can't edit them permanently. In the files, one column is the error for another. The columns are not sequential, neither they are labelled somehow. So, how to tell Veusz to use, for instance, dataset `data[col5]` as the symmetrical errors for `data[col2]`?

And how to perform simple arithmetic actions over a dataset to calculate its errors?

A similar (and unanswered) question is [here](https://www.reddit.com/r/Veusz/comments/6akam0/error_bars_in_xy_plots/).

**Comment by MarkDurre** [comment]
This is easy, just put in 
data[col5], data[col2]
See this answer => https://github.com/veusz/veusz/issues/189

**Comment by StSav012** [comment]
Oh, thanks! I must have missed that issue. I wish the information to be included into the manual.
