### ISSUE TITLE
Participate in iminuit v2.0 beta?

### ISSUE THREAD

**Issue by HDembinski** [veusz/veusz#464]
Dear veusz team,

I am about to finish a major rewrite of iminuit, version 2.0, that replaces Cython as the tool to wrap C++ Minuit2 with pybind11, which is going to solve several issues that the legacy code had. All the good things that this will bring are listed on top of this PR:
scikit-hep/iminuit#502

Switching to the new version of iminuit should be completely transparent to you, since the new version passes the comprehensive suite of unit tests of iminuit-v1.x. However, I would like to use this opportunity to finally remove interface that has been successively marked as deprecated in versions 1.3 to 1.5.

Therefore my two question to you:

* Did you take note of the deprecation warnings in iminuit and did you keep up with the interface changes?
* Are you interested in trying out a Beta release of v2.0 to work out any possible bugs in the new version before the release?

Best regards,
Hans, iminuit maintainer

**Comment by korintje** [comment]
@jeremysanders
Thanks for the review and merge!
I assume that we can close this issue now?

**Comment by jeremysanders** [comment]
Ok!
