### ISSUE TITLE
function boundary and text box size

### ISSUE THREAD

**Issue by michijim** [veusz/veusz#466]
Hi Jeremy,
attached file has 2 problems for me
1) The function lines start and stop before min and max
boundaries for functions 1, 2, and 3 were 3.16,10  10, 31.6,   31.6, 56.2 but there are big gaps between the lines
the functions are const * x**-2.2  (slightly different const for each function)

2) I can't seem to change the text label box to make multiple line label; typing more just runs the label off the plot and I haven't figured out if I can reshape the text box.

Thanks for terriffic software
[3 bins.pdf](https://github.com/veusz/veusz/files/5514760/3.bins.pdf)

Jim (physics/astrophysics professor)

**Comment by jeremysanders** [comment]
Hi Jim, here are some possible solutions:

1. You could try increasing the number of steps plotted (see formatting settings for function) for the functions from 50 to a larger number and see whether that helps.

2. Currently it uses LaTeX style formatting, so a line break is `\\`

**Comment by michijim** [comment]
thanks for your kindness to this veusz newby; much better now!

Working on HAWC, hawc-observatory.org

Jim
________________________________
