### ISSUE TITLE
font color error in tutorial

### ISSUE THREAD

**Issue by fabricix** [veusz/veusz#470]
**The issue**
The font in the tutorial canvas area is not working fine. I can not read the text on it:
![image](https://user-images.githubusercontent.com/22794916/99253356-5dd77380-27ef-11eb-82b3-dba527f8a046.png)

**Program version**: 3.0.1 and 3.2.1

**The system**
Operating System: KDE neon 5.20
KDE Plasma Version: 5.20.3
KDE Frameworks Version: 5.75.0
Qt Version: 5.15.1
Kernel Version: 5.4.0-52-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i7-5500U CPU @ 2.40GHz
Memory: 15,6 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 5500

**Comment by jeremysanders** [comment]
Maybe something to do with your dark mode? Is it possible to try it with a light mode to see whether that works?

**Comment by fabricix** [comment]
yes, in light mode the font is right. An observation is that the entire program work fine with the dark mode, but the tutorial canvas does not. I see the box canvas of this dialog has a different scroll bar too.

**Comment by hgoumner** [comment]
Hello, a bit off topic, but how did you change the theme / implement the dark theme? It looks great :)

**Comment by fabricix** [comment]
hi @hgoumner it is simply the Breeze Dark windows color in KDE neon (5.20) with KDE Plasma (5.20.3).

**Comment by hgoumner** [comment]
Thanks for the quick reply :) Unfortunately, I use Mr. Gates' operating system so I can't change the theme like that. Maybe one day there'll be a Veusz-internal dark theme available.

**Comment by jeremysanders** [comment]
The above should fix the dark theme in the help window. I also fixed the splash window and made some of the icons better. Further work is needed on the other icons.

**Comment by fabricix** [comment]
hi, I tested this in version 3.3.-0~ppa1~focal1 and the issues continues.

**Comment by jeremysanders** [comment]
@fabricix This is only changed in the development source code, not in any releases.
