### ISSUE TITLE
Import multiple csv dataset 

### ISSUE THREAD

**Issue by fabricix** [veusz/veusz#472]
When I import multiple datasets, each one defined by a csv file, the new imported dataset replace the previous one. So I always have only one data set in the workspace. Is this an correct behavior?
How can I do to load multiple csv dataset (particle-p1.csv, particle-p2.csv, particle-p3.csv, ...) with same fields (time, u) to plot them in the same axis? 
For example:
![image](https://user-images.githubusercontent.com/22794916/99703904-6ee5e600-2a76-11eb-9e11-290180d04908.png)

Version: 3.2.1

**Comment by bhanudaysharma** [comment]
This is a known/designed issue/feature. You can use Prefix and Suffix
options given in import dialogue box to add multiple datasets with same
headers.

**Comment by jeremysanders** [comment]
Yes. I'll close this now.
