### ISSUE TITLE
Windows download fails in 3.2.1 veusz

### ISSUE THREAD

**Issue by michijim** [veusz/veusz#473]
![99483540-6bdede80-292c-11eb-8f06-2772e0d8480c](https://user-images.githubusercontent.com/74225168/99867873-85ca2c80-2b8b-11eb-8bef-33fb0575497a.png)
windows 3.2.1 binary install fails on a bunch of QT files
3.2 also fails
unfortunately the attempted installs removed a working 3.0, but I was able to reinstall it from the repository.

Thanks,
Jim Linnemann

**Comment by jeremysanders** [comment]
I'm no Windows expert, but it looks like there's a permission problem on the Veusz directory. I suggest uninstalling it, and manually deleting the Veusz directory in `C:\Program Files (x86)`. You can then try reinstalling.

**Comment by michijim** [comment]
I tried reinstalling 3.2.1 today -- and it worked successfully, first deleting v3.1, so didn't get to try manual deletion of veusz directory.

the only thing between I know of was a dell upgrade on miscellaneous things for my laptop, so I have no explanation.

**Comment by jeremysanders** [comment]
Great. I'll close this then.
