### ISSUE TITLE
Permanent plugin error in console window

### ISSUE THREAD

**Issue by Dobrodzieju** [veusz/veusz#484]
If , for example,  Data>Operation>Add>Constant... is started and Output dataset name field is left empty,
a pop-up window with error message shows-up, as expected. However, if **Input dataset** field is left empty,
then the red "Unknown dataset" message is printed to console window. Moreover, after canceling plugin operation
which generated error, console with this message permanently pops up again and again, each time any other operation,
non related to plugins, is performed. I use win10 and V3.3.1.

**Comment by jeremysanders** [comment]
There probably should be a check to stop this being created, but you can right click on the dataset and choose delete to stop the error.

**Comment by jeremysanders** [comment]
Thanks for the report. This will be fixed in the next release.
