### ISSUE TITLE
can I use math function to process data on the axis to plot?

### ISSUE THREAD

**Issue by bsmile001** [veusz/veusz#485]
I am trying to use arctangent to get angles out of the slope to plot, but it seems veusz does not recognize it, how can I possibly proceed with it?

**Comment by jeremysanders** [comment]
Please be clearer what you have tried. There is an arctan(x) function in veusz.

**Comment by bsmile001** [comment]
Thanks for your quick response. It seems my data is too small, thus
arctan renders very close results to itself and I thus didn't notice
the change.

**Comment by jeremysanders** [comment]
glad it's solved
