### ISSUE TITLE
limiting plotting range of a specific xy figure

### ISSUE THREAD

**Issue by bsmile001** [veusz/veusz#488]
In case there are multiple xy figures to plot in a plot, the overall range of plotting is controlled by x, but what if I would only plot part of a figure in one of the xy figures, is there a way to do that besides to edit data in the source data file of that xy figure? In the gnuplot, we can use something like 

a>b?f(a):1/0

to filter out the interesting part to plot.

**Comment by jeremysanders** [comment]
You can select a subset of the data using a filter to make a new dataset. You can also use an expression selecting a subset, e.g. xdata[xdata>6], ydata[xdata>6], or use a where expression where(xdata<6, xdata, -1)

**Comment by bsmile001** [comment]
Thanks, I tried to use where expression to help and put it into the xdata box

where(vMpHF>35,vMpHF,-1)

but it still shows a flat curve for vMpHF<35 at 1.5 on my plot. How to understand it? Should I specify ydata box as well? If so, how can I match the ending (x,y) accurately?

**Comment by jeremysanders** [comment]
You need to filter both to get this to work (you need the same number of elements in x and y). I'm not sure what you mean about the ending x, y. Do you mean something like `where(vMpHF>35, ydata, -1)`?

I should add a separate filter expression box to make this easier.

**Comment by jeremysanders** [comment]
Closing this now
