### ISSUE TITLE
Question: How to manually specify the x axes tick labels on an image plot?

### ISSUE THREAD

**Issue by fjeng** [veusz/veusz#503]
I want to plot a spectrogram with x, y, and z axes. Both the x and y are 1D vectors and the z is a 2D dataset. I used an image plot and created a graph (shown below). The results of this image plot were exactly what I wanted, with one exception. On this image plot, the x axes values should start from 25 and ends at 225 (instead of starting from 0 and ends at 200). Is there a way to accomplish that?

<img width="351" alt="Screen Shot 2021-02-14 at 8 25 06 PM" src="https://user-images.githubusercontent.com/7614286/107900671-b3670d80-6f0f-11eb-98a0-fdfb9b48dd29.png">

**Comment by korintje** [comment]
Isn't it enough to simply select the x-axis or y-axis and manually set the max and min values?
Sorry if I cannot catch what you mean in the question.

**Comment by jeremysanders** [comment]
How was the data imported? It's usually possible to set the x/yrange there.

**Comment by fjeng** [comment]
I have prepared the following data for the image plot that I want to create. 
- x is a linear vector from 25 to 225 (i.e., 201 columns).
- y is a linear vector from 1 to 1000 (i.e., 1000 rows).
- z is a 2dData and a 1000x201 numeric matrix (i.e., 1000 rows x 201 columns). 

Even though I have prepared the x, y, and z data, only the z data was used when creating this image plot. That is, when creating an image plot, I was only asked to import the z data (i.e., a 1000x201 matrix) and the resultant figure was showed as above. When this image plot was just created, the min and max of x labels are set as "auto" (i.e., the default values). If I change the min and max of the x labels to be 25 and 225, respectively, the image plot becomes something like this here.

![image](https://user-images.githubusercontent.com/7614286/108797485-48de4f00-7559-11eb-8dcb-a675f560155c.png)

For clarity, I have marked the areas of problems with red circles. As you can see now, the first 24 columns of data are truncated from the image plot, and any columns after 201 are filled with white space. 

I think the main issue may be related to the fact that I am unable to specify the x and y values when creating an image plot. Again, when creating an image plot, I was only asked to import a 2dData and that was it. I could not find anywhere to specify the x and y vectors.

**Comment by korintje** [comment]
I'm sorry for misunderstanding what you intended.

1. If the spacing of x and y vectors are constant, the situation is simple. You can specify the 2D data-set span by setting the coordinate range A to B in the "Import data window". Note that the range is inclusive, so a 1 pixel wide image with A=0 and B=1 would have the pixel centre at 0.5. The pixels are assumed to have the same spacing.
![image](https://user-images.githubusercontent.com/30950088/108806182-5391f600-75e4-11eb-9037-9d1dc93ef8aa.png)

2. If you have x and y vectors which have non-constant spacing, I'm not sure the best practice. I just know you can achieve that by run a command in the console like below:
```
SetData2D("ncs-z", GetData("z")[0], xcent=GetData("x")[0], ycent=GetData("y")[0])
```
, where "ncs-z" is the new 2D data-set name, "x" and "y" are imported 1D data-set, and "z" is imported 2D data-set.
I think there may be a better way.

@jeremysanders 
If there are any mistakes in my explanation, I would be glad if you point it out.

**Comment by fjeng** [comment]
Yes! It WORKED!!! Thank you SO MUCH!!!

![image](https://user-images.githubusercontent.com/7614286/108938862-cddf6c00-761e-11eb-8c24-bc7d94bf0def.png)
