### ISSUE TITLE
3D polylines in 3D plot?

### ISSUE THREAD

**Issue by srk** [veusz/veusz#508]
Is there an obvious way (there may be, and I'm just missing it) to put one or more 3D paths in a 3D plot, where a '3D path" is an ordered sequence of point (x,y,z) locations, joined by lines from one point to the next?

**Comment by jeremysanders** [comment]
The point3d widget draws points and optional lines. You can set the maker symbol to 'none', go to the line settings and make sure line is not hidden. This should draw a polyline between your points. See the 3d_points example.

**Comment by srk** [comment]
aha, lines hidden by default. Great ,closing!
