### ISSUE TITLE
enable selection of font styles and weights

### ISSUE THREAD

**Issue by mroi** [veusz/veusz#520]
Fonts sometimes offer more style options than just the binary bold and italic options. Different weights (thin, light, regular, bold, black) or styles (italic, oblique, roman, small caps) can be offered by the installed font. Qt exposes those style options with a font property `setStyleName`. Available values can apparently be [obtained from `QFontDatabase`](https://doc.qt.io/qt-5/qfontdatabase.html#styles).

I would welcome, if Veusz could offer these styles to users by exposing the respective font settings and passing them to Qt.

If anyone reading this is familiar with `QFontDatabase`, an example usage would be appreciated. An open problem is how to make this style property interact with the existing bold and italic options, which should probably be kept for compatibility.

**Comment by jeremysanders** [comment]
I think I've implemented this. I've added a FontStyle associated with the chosen font. This is a drop down box allowing the style to be chosen (of the selected font). By default it uses the default style (and therefore applies the current bold/italic setting). I've not tested on MacOS yet.

**Comment by jeremysanders** [comment]
It seems to work on MacOS for me.

**Comment by mroi** [comment]
Thanks for investing time in this. I tried to build `master` on macOS, but was not successful. It finished building, but I get unresolved symbols around PyQT when launching.

So unfortunately, I could not test this yet. I will definitely test it when there is a new release.
