### ISSUE TITLE
ImportFile2D() got an unexpected keyword argument 'renames'

### ISSUE THREAD

**Issue by fjeng** [veusz/veusz#522]
I created an image plot by importing a 2D dataset named "eeg_150ms" a few days ago. Yesterday, I renamed this dataset to be "nV_150ms".  Also, the .vsz file was working properly yesterday. However, when I tried to open this .vsz file this morning, Veusz could not open this .vsz file and gave me an error message (shown here).

![image](https://user-images.githubusercontent.com/7614286/114318662-0b6b5c00-9adc-11eb-82a9-12cf57a69e1e.png)

What did I do wrong? What should I do to correct this mistake, so that I can open this .vsz file?

Any comments or suggestions will be appreciated!

**Comment by jeremysanders** [comment]
Thanks fort he report. This is a bug - the rename feature wasn't properly implemented for 2D datasets. There will be a fix in the next release.

In the meantime as a workaround, you could try to open the ".vsz" file with a text editor, find the line with ImportFile2D and remove the part of the line which says `renames={....},`

**Comment by fjeng** [comment]
Thank you SO MUCH for your prompt response. Greatly appreciated!!! I followed your instruction and recovered my .vsz file. Thanks again!!!
