### ISSUE TITLE
[WIP] I create Flatpak for Veusz

### ISSUE THREAD

**Issue by kevinsmia1939** [veusz/veusz#523]
Hello,

I am creating Flatpak package for Veusz.
https://github.com/flathub/flathub/pull/2252

There are some issue with sip not finding QtCore when building Veusz.
`
sip: Unable to find file "QtCore/QtCoremod.sip"`

**Comment by korintje** [comment]
I found the issue now, and would like to know the current situation.
The problem of `sip: Unable to find file "QtCore/QtCoremod.sip"` has been already solved, and the current problem is building [iminuit](https://github.com/scikit-hep/iminuit/issues)?

**Comment by kevinsmia1939** [comment]
> I found the issue now, and would like to know the current situation.
> The problem of `sip: Unable to find file "QtCore/QtCoremod.sip"` has been already solved, and the current problem is building [iminuit](https://github.com/scikit-hep/iminuit/issues)?

Hello,

Yes, QtCoremod.sip issue has been fix.
Veusz can be build and run.
But fail to build iminuit that Veusz need for good curve fitting feature.

**Comment by korintje** [comment]
Is this pull [request 507](https://github.com/veusz/veusz/pull/507#issue-580916004) related to the problem?
Support for iminuit 2.x.x has just recently been merged into Veusz, and yet not included in the latest Release (Veusz-3.3.1).

**Comment by korintje** [comment]
I checked the detailed error message you reported, and understood it may be related to [iminuit](https://github.com/scikit-hep/iminuit/issues/642) itself, rather than veusz. Thanks.

**Comment by kevinsmia1939** [comment]
> I checked the detailed error message you reported, and understood it may be related to [iminuit](https://github.com/scikit-hep/iminuit/issues/642) itself, rather than veusz. Thanks.

Yes, I have trouble building iminuit in Flatpak environment. Veusz itself is fine.

**Comment by kevinsmia1939** [comment]
Hello,
I manage to build Veusz now.
https://github.com/flathub/flathub/pull/2252

Please try it out. Could you also see if iminuit is doing the curve fitting correctly?

Setup Flatpak according to your distro.
https://flatpak.org/setup/
Then use this to install
`flatpak install --user https://dl.flathub.org/build-repo/44935/io.github.veusz.Veusz.flatpakref`

**Comment by jeremysanders** [comment]
I assume we can close this now?
