### ISSUE TITLE
Feature Request: Portable Version / Installation without admin privileges

### ISSUE THREAD

**Issue by kamaing** [veusz/veusz#524]
Hi,

I like to use Veusz in my organization, but I do not have admin privileges.
Is there a possibility to install without admin privileges or use a portable version?

Can you tell me how to get or create such a version?

**Comment by jeremysanders** [comment]
I don't think there should be any portability problems with the Veusz installation. The installer just copies the files and sets up file associations. If you don't care about the associations, you can just copy the installed files.

You should be able to install the program to somewhere where you have admin access, zip or copy the files to some other location, then use them from there on any computer.

**Comment by jeremysanders** [comment]
PS This is what the NSIS installer file looks like: https://github.com/veusz/veusz/blob/master/support/veusz_windows_setup.nsi
