### ISSUE TITLE
Cannot open the Veusz after trying to plugin with excel data importing

### ISSUE THREAD

**Issue by LimJunXian** [veusz/veusz#528]
![Untitled](https://user-images.githubusercontent.com/35997025/116042265-c8df7d00-a6a0-11eb-9d4b-ca3df5985162.png)

**Comment by jeremysanders** [comment]
You can reset the settings by deleting your preferences file.
https://github.com/veusz/veusz/wiki/PreferencesFile

Please contact the plugin author for problems with the plugin.

**Comment by LimJunXian** [comment]
Thank you so much! Problem solved!
Yes, I will contact the plugin author as well.
