### ISSUE TITLE
Windows drive letters break "Python path" setting

### ISSUE THREAD

**Issue by matheger** [veusz/veusz#531]
When adding a custom Python path entry that contains a drive letter and following colon in "Preferences" -> "External", the program splits the path definitions on all colons. This can be verified by restarting Veusz, then using the console to check `import sys; sys.path`.

I guess something in the code assumes a Unix format, where the path variable is indeed separated by colons...? - Also, I checked in the `external_pythonpath` key in the registry, but it correctly reflects what I entered in the Preferences dialogue. It seems to me that the error must occur when parsing that setting.

**Comment by jeremysanders** [comment]
The code currently assumes it can break on a colon, like on Unix. As a workaround you could try a UNC style path, like `\\localhost\c$\my_dir`. Maybe it could be changed to either allow colons to be escaped, or to not break on colons within `[A-Z]:\`.

**Comment by jeremysanders** [comment]
Should be fixed in the next release
