### ISSUE TITLE
2D import fails

### ISSUE THREAD

**Issue by Flo-vsz** [veusz/veusz#532]
Hallo everybody,

I thank you all in advance for the great software and all the support to users.

I have a problem with importing 2D data in Veusz.
My goal is to produce a contour image as the "contour.vsz" example. There the matrix is 100x100. 
In my case the matrix would be 60x60., here i will display only a substet of it (4x4):
0.55	0.55	0.55	0.55
0.45	0.45	0.45	0.45
0.9	0.9	0.9	0.9
0.45	0.45	0.45	0.45
as you can see the image should be a bar-code like.
I'm using the import 2D tool. 
-when importing from .txt, error report: "xcent must be ascending or descending" if "grid points at edges" is flagged. or error report "no data could be imported for dataset" if I unflag it and try to set with numbers e.g. (x 0-1, y 0-1), or others.
- when importing from .csv gives the same errors.
According to other solved issues i read, I am following these instructions, but even a simple 4x4 2D dataset isn't going through. 
Am I doing mistakes in setting the matrix?
I tried also with headers, but probably i'm not entering them correctly. What would be the appropriate headers for a 60x60 matrix?

**Comment by jeremysanders** [comment]
If I put the data in a file it seems ok for me.

Choose Text mode. Do not choose grid points at edges. Enter a name for the dataset in the "Datasets box". Click Import.

Try the reset button first if you have a problem.

**Comment by Flo-vsz** [comment]
Thanks Jeremy!
I menaged to get the image i wanted.. Apparently i was wrong also for using " ; " instead of " , " or " space " in the .txt (as actually the manual reports for 2d..) :)
Since the topic is open, if i may ask..how do different grid point at edges affect the image? and how to set the linked color bar with a log scale?

Again thanks a lot and congratulation for the outstanding program!

**Comment by jeremysanders** [comment]
The grid points along the edges give the coordinates of the pixels on the axes. This allows you to have irregular pixels sizes. They need to be in order though. Alternatively, you can give the range in x and y of the data in the header (see the manual).

If you go to the image widget, you can choose log scaling. The colour bar just shows what the image widget is displaying - it doesn't control it.

Hope that helps!

**Comment by Flo-vsz** [comment]
Yeah great, thanks! 
with grid point at edges (from the import panel) i can set them as min and max only, am i correct?
About headers, i read the manual, but i didnt get those for 2d, how to write them. e.g. xcent A B   ycent A B    should they be on the header of any columns (as xcent 0.5     xcent 1.5   ...... ) or just at the first header? and should it be contained in one "cell" only or in 2 adjacent (horizontally) cells?  (as for x and symmetric errors)

**Comment by jeremysanders** [comment]
If your grid points are at the edges, you should do something like this
```
     1    2    3    4
10   0.55 0.55 0.55 0.55
20   0.45 0.45 0.45 0.45
30   0.9  0.9  0.9  0.9
40   0.45 0.45 0.45 0.45
```
(spaces are just for formatting and are ignored)

If you want to use the headers it's just like
```
xrange 1 4
yrange 10 40
0.55 0.55 0.55 0.55
0.45 0.45 0.45 0.45
0.9 0.9 0.9 0.9
0.45 0.45 0.45 0.45
```

Alternative headers are
```
xedges 0 1 2 3 4
ycent 0.5 1.5 2.5 3.5
```
(that would set the edges of the pixels (here 4 pixels) for for the X coordinates, and the pixel centres for the y coordinates)

**Comment by Flo-vsz** [comment]
great, these examples are so helpfull, i get it now. (i have to say, the program is very sharp and after all intuitive, well done!)

**Comment by Flo-vsz** [comment]
I would like to ask one last thing about colorbar..
As you said earlier, on image widget there is scaling.
On an x y plot instead, i am not able to display it out the 0-1 range. I'd like to set a graph as the coloredpoints.vzs example.
I would like it in log scale as the example (but where to flag it is grey). 
when i set the range x min max, colorbar get blank. In my case the dataset meant for color isn't in the 0 1 range (as for the example, where the color is in a 0 3000 range). Also my points don't get colored (i tried editing my color dataset, and when in the 0 1 range only, they get colored).

How is possible to get colored point out of the 0 1 range?

![Cattura](https://user-images.githubusercontent.com/84096303/118127149-9f8d5380-b3f9-11eb-903c-8660cd819f7b.PNG)
![Cattura1](https://user-images.githubusercontent.com/84096303/118127298-cc416b00-b3f9-11eb-98a0-923fa2421512.PNG)

**Comment by jeremysanders** [comment]
Don't change the range on the colorbar. Click the little "+" next to the Color setting on your XY plotter. There you can set the range and scale.

**Comment by Flo-vsz** [comment]
oohh so easy. wow

Jeremy I dont know how to thank you, your help is so much appreciated!

**Comment by jeremysanders** [comment]
Ok. Closing!
