### ISSUE TITLE
Linux Mint: installs, but does not run: No module named 'veusz'

### ISSUE THREAD

**Issue by jbeale1** [veusz/veusz#536]
I have a "fitlet 2" brand Linux Mint box, which I gather is based on Ubuntu Bionic from the apt update repositories listed.

The 'veusz' package installs without any obvious error, but it does not run. It is not clear to me from the error:  **No module named 'veusz'** what the actual problem is.

```
$ sudo apt install veusz
Reading package lists... Done
Building dependency tree       
Reading state information... Done
veusz is already the newest version (1.21.1-1.3).
0 upgraded, 0 newly installed, 0 to remove and 205 not upgraded.

$ veusz
Traceback (most recent call last):
  File "/usr/bin/veusz", line 23, in <module>
    import veusz.veusz_main
ModuleNotFoundError: No module named 'veusz'
```

```
$ uname -a
Linux john-fitlet2 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jbeale1** [comment]
**UPDATE:** in my case, the workaround is to edit the first line of /usr/bin/veusz and replace
**#! /usr/bin/python**   with  **#!/usr/bin/python2**
because my system default is Python 3.6.9 and I guess the module is only for Python 2.x

**Comment by jeremysanders** [comment]
I would file a bug with linux mint. It's a very old version of veusz, by the way.
