### ISSUE TITLE
Option for not interpreting text as LaTeX

### ISSUE THREAD

**Issue by MPSMPS** [veusz/veusz#542]
Hi, I really like veusz. For me only missing thing for good plots is that the text is rendered with latex according to my settings of the document. Therefore, I would like to enter full latex commands as e.g. labels ($u_\mathrm{V}$). An option in veusz to interpret the text only as text and not LaTex would be cool. If this option is present I can then use inkscape to split the svg into a PDF for graphical data and a .pdf_tex file and render it on my own with my own settings.

Or is there any other option I am missing to let LaTeX render my commands?

Thanks and regards
Mathias

**Comment by korintje** [comment]
I think `ESCAPE` expression is helpful for you.
(https://veusz.github.io/docs/manual/introduction.html)

<Example>
"""
%{{ESCAPE("$u_\mathrm{V}$")}}%
"""

**Comment by MPSMPS** [comment]
@korintje Oh, thank you very much. I saw the ESCAPE expression before but I did not get it to work. I thought I maybe misinterpreted something. If I remember correctly if did not include the " around the expression.

Thx for the hint. Up to now it works flawlessly.
