### ISSUE TITLE
[Feature request] NetCDF import: convert data points matching 'missing_value' attribute to NaNs

### ISSUE THREAD

**Issue by ssgromov** [veusz/veusz#546]
Hi Jeremy,

It would be great if the NetCDF import filter could convert the data points that are saved as missing (e.g. equal to the `missing_data` attribute, also often populated using `_FillValue` attribute of a variable) with NaNs in Veusz. 

Currently I can only filter the data using workarounds, which is cumbersome...

Unfortunately, NetCDF does not have a representation of NaNs in data containers :(

Thanks

**Comment by ssgromov** [comment]
OK, marked as a feature request. 

@And0k, is it possible to implement that in .vsz directly? E.g.

```
ImportFileHDF5(...)
<whatever expression to convert -1e+33 to NaNs>
```

**Comment by And0k** [comment]
@ssgromov , I mean feature request for loading HDF5 attributes is needed. So when loading array x it has attribute x._FillValue = -1e33. So then you can use expression to set it to NaN:
```python 
where( x == _FillValue, NaN, x)
```

**Comment by ssgromov** [comment]
Tested with v3.4.99, works! Many thanks @jeremysanders !!!
