### ISSUE TITLE
Wrong font names in SVG export

### ISSUE THREAD

**Issue by DJGoossens** [veusz/veusz#551]
Hi

I am exporting to SVG using the option for editable text. It's really handy, and much appreciated. I am using Open Sans as the font, and running the precompiled binary on Debian 11.

Regular Open Sans shows up in the Veusz font list as "Open Sans [1ASC]" (see attached image) . The "[1 ASC]" part is included in the font name in the SVG file, and so when other programs (eg Eye of MATE, the viewer I am using, or a web browser, etc) open it, they cannot find the font. 

SVG export without editable text works fine, but the editable alternative is really valuable to us.

Some fonts with [bits in square brackets] seem to work, but not Open Sans. 

I find that if I open the SVG in a text editor and  delete " [1 ASC]" from the font name, it views correctly. Now, I think this is a Veusz issue and not related to my font installation, because Veusz is using the same fonts, installed recently, as the viewing program, and all viewing programs are behaving as you would expect.

All the fonts were just downloaded from Google in the same bundle, but you can see that a couple (Regular, bold italic] have these square brackets after them, and some don't.

![fontname1](https://user-images.githubusercontent.com/12536752/131080016-7f1a1977-bfb7-473a-8b29-dd4df3917075.png)

**Comment by biojames** [comment]
I can confirm this issue. My (Linux) system has two implementations of a font and Qt distinguishes them by [foundry]. The [foundry] designation in the exported .svg file results in the font not being properly rendered by Google Chrome, Inkscape or LibreOffice. The relevant atrribute in the .svg file is "font-family=", and there is no attribute I can find called "font-foundry" so I think there is good justification for explicitly excluding this information.

**Comment by jeremysanders** [comment]
I've added some code to remove parts of font names which look like "whitespace[foundry]". It seems to work for me on a font on my Linux system which has a foundry name.

**Comment by korintje** [comment]
I've also confirmed that it works well on my Win10 and WSL (Ubuntu 20.04) environments.
+1 for the new code 👍.
