### ISSUE TITLE
Veusz does not work with python 3.10

### ISSUE THREAD

**Issue by Fellypao** [veusz/veusz#563]
Dear developers,

Veusz builds fine against python 3.10. However, it does not run. It returns the following error:
_____________________
fellype@plasma:~$ veusz 
Traceback (most recent call last):
  File "/usr/bin/veusz", line 33, in <module>
    sys.exit(load_entry_point('veusz==3.3.1', 'gui_scripts', 'veusz')())
  File "/usr/lib64/python3.10/site-packages/veusz/veusz_main.py", line 369, in run
    app.startup()
  File "/usr/lib64/python3.10/site-packages/veusz/veusz_main.py", line 267, in startup
    self.splash = makeSplash(self)
  File "/usr/lib64/python3.10/site-packages/veusz/veusz_main.py", line 69, in makeSplash
    font.setPointSize(font.pointSize()*1.5)
TypeError: setPointSize(self, int): argument 1 has unexpected type 'float'

**Comment by korintje** [comment]
How about changing line 69 in the file veusz/veusz_main.py like below?

```veusz_main.py
font.setPointSizeF(font.pointSize()*1.5)
```
or
```veusz_main.py
font.setPointSize(int(font.pointSize()*1.5))
```

Even if these modifications were effective, I have no idea why this bug became problematic at Python 3.10...

**Comment by jeremysanders** [comment]
Actually, thinking about this, I'm using the latest PyQt5 and sip and didn't encounter this problem, so it likely seems related to Python 3.10. I'm not sure why. I probably should do some testing with Python 3.10 before the next release to make sure there aren't similar bugs.
