### ISSUE TITLE
Tutorial hangs after entering function x**x

### ISSUE THREAD

**Issue by heliophagus** [veusz/veusz#573]
As the title says, the tutorial hangs after reaching the function example. I enter x**x, & the graph of the function appears. BUT, the NEXT button now has no effect, so I cannot continue with the tutorial. I am using the latest Win10 on a machine with 32 GB of RAM, if that's relevant. So much of Veusz is totally different from other scientific plotting packages I've used that I'd really appreciate being able to run the tutorial past this point.

**Comment by jeremysanders** [comment]
I think the tutorial has something like `x**2` not `x**x`. Probably Python is going crazy with memory usage computing `x**x` which some large value of `x`. Can you check you entered the correct thing?

**Comment by heliophagus** [comment]
Many thanks for the suggestion! I will check on that and get back to you
after I return to that computer.

John

**Comment by heliophagus** [comment]
Yes indeed! Thanks for the correction. I feel like an idiot but fortunately I'm used to that.

I just want to add a quick "THANK YOU" for responding so quickly. So many software packages are orphaned or abandoned. It's great to see a powerful, useful program that has powerful, useful - and patient! - support. I will try not to ask any more stupid questions.

John
