### ISSUE TITLE
[bug] Exsiting plugins show import error at Veusz 3.4

### ISSUE THREAD

**Issue by korintje** [veusz/veusz#575]
Existing plugins (Import, Tool, and Dataset), which work well until Veusz 3.3.1, do not work at Veusz 3.4. 

Typical structure is like below (example: https://github.com/korintje/SPAImportPlugin_for_Veusz/blob/main/spa_import.py):
```sample.py
# This does not work

from veusz.plugins import *

class ImportPluginExample(ImportPlugin):

    def __init__(self):
    """some initialization porcess"""

    def doImport(self, params):
    """Actually import data"""

importpluginregistry.append(ImportPluginExample)
```
This type of plugin files raise an error message like below when selected:
```
Traceback (most recent call last):
  File "veusz\dataimport\dialog_plugin.py", line 104, in pluginChanged
  File "veusz\dataimport\dialog_plugin.py", line 96, in getSelectedPlugin
  File "<string>", line 13, in __init__
NameError: name 'ImportPlugin' is not defined

Frame pluginChanged (File veusz\dataimport\dialog_plugin.py, line 104)
 self = <veusz.dataimport.dialog_plugin.ImportTabPlugins object at 0x0000019B0AB1D708>
  self.DrawChildren = 2
  self.DrawWindowBackground = 1
  self.IgnoreMask = 4
  self.PdmDepth = 6
  self.PdmDevicePixelRatio = 11
  self.PdmDevicePixelRatioScaled = 12
  self.PdmDpiX = 7
  self.PdmDpiY = 8
  self.PdmHeight = 2
  self.PdmHeightMM = 4
  self.PdmNumColors = 5
  self.PdmPhysicalDpiX = 9
  self.PdmPhysicalDpiY = 10
  self.PdmWidth = 1
  self.PdmWidthMM = 3
  self.__dict__ = {'dialog': <veusz.dialogs.importdialog.ImportDialog object at 0x0000019B0AB4A288>, 'uiloaded': True, 'promote': None, 'p...
  self.__doc__ = 'Tab for importing using a plugin.'
  self.__module__ = 'veusz.dataimport.dialog_plugin'
  self.dialog = <veusz.dialogs.importdialog.ImportDialog object at 0x0000019B0AB4A288>
  self.fields = [(<PyQt5.QtWidgets.QLabel object at 0x0000019B0708BEE8>, <PyQt5.QtWidgets.QLineEdit object at 0x0000019B0708BF78>), (<Py...
  self.filefilter = None
  self.filetypes = ()
  self.gridLayout_5 = <PyQt5.QtWidgets.QGridLayout object at 0x0000019B0AB175E8>
  self.groupBox_2 = <PyQt5.QtWidgets.QGroupBox object at 0x0000019B0AB17828>
  self.horizontalLayout = <PyQt5.QtWidgets.QHBoxLayout object at 0x0000019B0AB17A68>
  self.label_24 = <PyQt5.QtWidgets.QLabel object at 0x0000019B0AB179D8>
  self.pluginDescr = <PyQt5.QtWidgets.QLabel object at 0x0000019B0AB178B8>
  self.pluginParams = <PyQt5.QtWidgets.QGroupBox object at 0x0000019B0AB17678>
  self.pluginPreview = <PyQt5.QtWidgets.QTextEdit object at 0x0000019B0AB17708>
  self.pluginType = <PyQt5.QtWidgets.QComboBox object at 0x0000019B0AB17948>
  self.pluginchoicewidget = <PyQt5.QtWidgets.QWidget object at 0x0000019B0AB17AF8>
  self.plugininstance = <veusz.plugins.importplugin.ImportPluginExample object at 0x0000019B06AF0208>
  self.promote = None
  self.resource = 'import_plugins.ui'
  self.staticMetaObject = <PyQt5.QtCore.QMetaObject object at 0x0000019B06FCA358>
  self.uiloaded = True
  self.verticalLayout_7 = <PyQt5.QtWidgets.QVBoxLayout object at 0x0000019B0AB17798>
  self.verticalLayout_8 = <PyQt5.QtWidgets.QVBoxLayout object at 0x0000019B0AB1D318>
 index = 6

Frame getSelectedPlugin (File veusz\dataimport\dialog_plugin.py, line 96)
 self = <veusz.dataimport.dialog_plugin.ImportTabPlugins object at 0x0000019B0AB1D708>
 selname = 'OMNIC SPA import'
 names = ['Numpy NPY import', 'Numpy NPZ import', 'QDP import', 'Binary import', 'Example plugin', 'Gnuplot 2D data import plugin...
 idx = 6
 p = <class 'veusz.document.doc.ImportSPA'>

Frame __init__ (File <string>, line 13)
 self = <veusz.document.doc.ImportSPA object at 0x0000019B06ED5388>
  self.__dict__ = {}
  self.__doc__ = 'A plugin for reading Thermo Scientific OMNIC SPA file.'
  self.__module__ = 'veusz.document.doc'
  self.__weakref__ = None
  self.author = 'Takuro Hosomi'
  self.description = 'Read a spectrum from Thermo Scientific OMNIC SPA file'
  self.file_extensions = {'.SPA', '.spa'}
  self.name = 'OMNIC SPA import'
  self.promote_tab = None
```
This behaviors were reproduced multiple OSs (Ubuntu, Windows, and MacOS) and also occurs with self-built program.

I have found a work around. 
The files become to work well, by importing modules in each method instead of the global section.
 (example: https://github.com/korintje/SPAImportPlugin_for_Veusz/blob/main/spa_import_34.py). 
```sample2.py
# This will work

from veusz.plugins import ImportPlugin, importpluginregistry

class ImportPluginExample(ImportPlugin):

    def __init__(self):
    from veusz.plugins import ImportPlugin
    """initialize"""

    def doImport(self, params):
    from veusz.plugins import ImportDataset1D
    """Actually import data"""

importpluginregistry.append(ImportPluginExample)
```

However, I think such behaviors are not intended. Such way becomes messy especially when users use some large classes.
So I reported it as a bug.

**Comment by jeremysanders** [comment]
Thanks very much for the report. It works ok for me when I test under linux built from source. Can you tell me what operating system you're using, and is this one of the binary packages?

**Comment by korintje** [comment]
Thank you very much for your reply!
I faced the error under the following environments and packages.

1. Windows 10 Pro 64 bit(21H2) + binary package (https://github.com/veusz/veusz/releases/download/veusz-3.4/veusz-3.4-x64-windows-setup.exe) or built from the latest source

2. Ubuntu 20.04 (WSL) + binary package (https://github.com/veusz/veusz/releases/download/veusz-3.4/veusz-3.4-linux-x86_64.tar.xz) or built from the latest source

I prepared a simpler example plugin like below to reproduce the error.

``` example2.py
from veusz.plugins import *

class ImportPluginExample(ImportPlugin):

    name = "Example plugin 2"
    author = "Test"
    description = "Reads a list of numbers in a text file test"

    file_extensions = set(['.example2'])

    def __init__(self):
        ImportPlugin.__init__(self)
        self.fields = [
            ImportFieldText("name", descr="Dataset name", default="name"),
            ImportFieldCheck("invert", descr="invert values"),
            ImportFieldFloat("mult", descr="Multiplication factor", default=1),
            ImportFieldCombo("subtract", items=("0", "1", "2"),
                             editable=False, default="0")
            ]

    def doImport(self, params):
        f = params.openFileWithEncoding()
        data = []
        mult = params.field_results["mult"]
        sub = float(params.field_results["subtract"])
        if params.field_results["invert"]:
            mult *= -1
        for line in f:
            data += [float(x)*mult-sub for x in line.split()]

        return [ImportDataset1D(params.field_results["name"], data)]

# add the class to the registry. An instance also works, but is deprecated
importpluginregistry.append(ImportPluginExample)
```

What I did:
1. "Edit" → "Preferences" → "Plugins" → "Add" → Select example2.py
2. Quit and restart Veusz
3. "Data" → "Import" → "Plugins" → Plugin: "Example plugin 2" → Error

**Comment by korintje** [comment]
I checked another environment and reproduce same error.
3. macOS bigSur 11.6 (on intel core i5) + + binary package (https://github.com/veusz/veusz/releases/download/veusz-3.4/veusz-3.4.0.1-AppleOSX.dmg)

**Comment by jeremysanders** [comment]
How strange. I've tried your latest example with the binary package on Windows 8.1, Windows 10 (21H1) and Ubuntu 21.10 and I don't see any problems.

I wonder what the difference is? Could it be something to do with locale settings, or spaces in paths or something obscure like that?

If someone else could try to reproduce this, it would be great.

**Comment by korintje** [comment]
Thank you again for checking it.
Yes, it's strange. I hope it is just a local problem of mine...
Anyway, I will continue to try to find out the cause.

**Comment by Dobrodzieju** [comment]
I have also this problem. None of my plugins works. This must be related to the first line, which is:
`import veusz.plugins as plugins`
Veusz 3.4  generates the following error message:

Traceback (most recent call last):
  File "veusz\windows\mainwindow.py", line 389, in _loadPlugin
  File "veusz\dialogs\plugin.py", line 37, in handlePlugin
  File "<string>", line 24, in __init__
NameError: name 'plugins' is not defined
...
I use win10 and conda install.

**Comment by korintje** [comment]
My co-researchers also experience this issue without exception so far.

I found the part that seemed to be causing this problem: `Document.loadPlugins` method. 
https://github.com/veusz/veusz/blob/6c37f1455a64bcc6a446bc8d1b11be85e3f08bff/veusz/document/doc.py#L352-L365
In this method, the classes in the user-created plugins are defined in `veusz.document.doc` module, whereas the default import plugins are defined in `veusz.plugins.importplugin` module (can be checked by `print(importpluginregistry[-1].__dict__)`). I think classes under `veusz.plugins` cannot be imported in the class defined in `veusz.document.doc`.

The user-created plugin classes can be defined in `builtins` by just giving a blank hashmap as the second argument of `exec()`, like below (e4e946baa7703ffa334d0befe3b730a79419c31c).
```
    exec(f.read(), {}) 
```
I don't think this is the best practice, but anyway it seems to work well. It would be cleaner to use something like `Importlib`. 

@Dobrodzieju
Could you check my modified code (e4e946baa7703ffa334d0befe3b730a79419c31c) work also in your environment?

**Comment by korintje** [comment]
I confirmed that the issue does not occur before commit 'Remove Python 2 support ' (https://github.com/veusz/veusz/commit/035801459c612c83523664ebf4c9b0035a448d7e). So, at least we can say that this issue relates to this commit.

**Comment by Dobrodzieju** [comment]
@korintje
Your modified code works also in my Miniconda3 environment. Thank you very much !
BTW, I have also the "stand-alone" version of Veusz 3.4, installed with windows installer. 
However, I have no idea where to find doc.py file, which belongs to this version. It is
somewhere well hidden, probably together with the common for both version config file.

**Comment by jeremysanders** [comment]
I can't reproduce this bug, and I'm not sure why there should be a difference in behaviour with an empty environment and the local one in that function. Perhaps it's something to do with Python's module loader. It is correct that the 'Remove Python 2 support' commit did remove the empty environment used in the exec. 

I've therefore made the change suggested. It's probably better, anyway, to ensure a clean environment for the exec.

Please feel free to close this if this is a fix. The source code can't be modified in the Windows binary. Maybe some kind of workaround to delete all the non-builtins in globals() would do the job in the plugin.

**Comment by korintje** [comment]
Thanks for the immediate fix. 
As you says, it is confusing also for me that the condition to reproduce this bug is still not clear. 

Anyway, I have confirmed that the fixed code works well on Ubuntu, Window, and mac OS in my environments.
So, I will close this issue. Thank you.
