### ISSUE TITLE
Problem with line and broken axis

### ISSUE THREAD

**Issue by Dobrodzieju** [veusz/veusz#583]
The problem shows up when point-to-point line is inserted in "axes" position mode and  when one of the axes
is defined as "broken". Error message contains the following:
...
...\lib\site-packages\veusz\widgets\line.py", line 174, in _computeLinesPointToPoint
    if N.all( N.isfinite(v) ):
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
...

**Comment by jeremysanders** [comment]
Thanks for the report.  The above patch should fix the crash. The broken axis won't actually break the line, however. This would require further work on the line widget to add some missing interface. I suggest using the xy point widget instead if you want breaks.
