### ISSUE TITLE
sin(x) or cos(x) looks choppy if max of x axis is set to more than 60

### ISSUE THREAD

**Issue by shticktical** [veusz/veusz#589]
![image](https://user-images.githubusercontent.com/47024235/161424273-b5c89ee7-fb4e-445f-b441-0f6bd405a0af.png)
Is there a way to get around this behavior, or is it a bug?
[Manjaro Linux, Veusz 3.4]

**Comment by jeremysanders** [comment]
You just need to increase the number of steps in the function settings.

**Comment by shticktical** [comment]
Thank you for the tip, but I still can't figure out where exactly I can change the number of steps. I'm looking to set it using graphical user interface.

**Comment by jeremysanders** [comment]
![image](https://user-images.githubusercontent.com/274711/161427860-52f68275-cbcf-44de-8a51-8d1e6911e4ac.png)

**Comment by shticktical** [comment]
That button wasn't there a moment ago, promise :)
Thank you.
