### ISSUE TITLE
Multi-monitor issues

### ISSUE THREAD

**Issue by ckuhlmann** [veusz/veusz#59]
I have a multi-monitor setup with two screens that don't have the same size.
My primary monitor is on the left and has 1280x1024px, my second is on the right and has 1920x1080px. Both screens are top aligned.
If I maximize Veusz on the second screen, the position is not remembered and it starts aligned to the left top corner of my first screen. However, the size of the window seems to be correct. This behavior started with 1.20.1.

Another longstanding problem I have is on a setup where the right monitor is the primary screen and the left one is the secondary (same resolutions). On the right monitor, the menus of the properties panel's [,,] button open to the right, outside the screen area. Interestingly, this behavior is not present on the aforementioned setup. It seems that Veusz assumes that the 2nd monitor is always on the right.

Both Systems are Win7 x64.

**Comment by jeremysanders** [comment]
I'm closing this as Veusz moved to Qt5 some time ago. I hope things are better.
