### ISSUE TITLE
Ubuntu PPA: package is missing for focal (Ubuntu 22.04 LTS "Jammy Jellyfish")

### ISSUE THREAD

**Issue by ecdlguy** [veusz/veusz#596]
Hi,

can you please update the PPA to support the recently released Ubuntu LTS version?
There's also version 3.3.1-3build1 in the official 22.04 repos, however it is outdated an also crahes at start.

cheers,
Thorsten

**Comment by jeremysanders** [comment]
I've built it. Does it work for you?

**Comment by ecdlguy** [comment]
Looks good, thanks Jeremy!
