### ISSUE TITLE
+ and - for adding/removing sections in bar plots invisible on Macbook

### ISSUE THREAD

**Issue by schoggi** [veusz/veusz#602]
Hi,
on my Macbook, the + and - for adding sections in bar plots are either hardly visible (yellow emphasis) or invisible (red emphasis):

<img width="470" alt="image" src="https://user-images.githubusercontent.com/48128877/175771224-f162f1c5-d3c8-4e15-a85b-9cfef71c29ec.png">

On my Windows laptop, they appear as they are meant to be (green emphasis):

<img width="485" alt="image" src="https://user-images.githubusercontent.com/48128877/175771251-06e13b03-2e07-4824-9fee-971afd02a01d.png">

It may have to do with screen resolution? Or with Mac?

Regards,

Pietro

**Comment by jeremysanders** [comment]
Thanks to @korintje, this should be fixed now
