### ISSUE TITLE
Import of Dataset from CSV, cannot import multiple files grouping by filename, import multiple files at once

### ISSUE THREAD

**Issue by Braveheart53** [veusz/veusz#605]
It would be very beneficial to import multiple CSV (or other pre-defined file types) with a single interface. Assuming the data and header rows are in the same location or keying off a string for data location this would be immensely beneficial.

Currently, when importing and grouping by file name, if one points to another file, the imported data is overwritten unless prefix or suffix is utilized. Binding the data to the parent file and allowing multiple file imports would be extremely nice to have.

Utilizing python 3.9 in anaconda, with Vuesz installed through anaconda / conda-forge interface.

**Comment by kaugummiheld** [comment]
Hello! 

As a workaround for you, for importing multiple I'm actually using that .vsz files are basically scripts to recreate a document state. That means I import a single .csv file via the GUI, save the file and open it in a text editor. It should contain a line like:
`ImportFileCSV('<filename>.csv', dateformat='YYYY-MM-DD| |hh:mm', headermode='1st', linked=True, numericlocale='C', dssuffix='_XYZ')`. 
I then go ahead and copy that line as many times I need, change the filenames and prefixes/suffixes; save the file and open it again in Veusz. 

In the GUI you can append/attach the filename automatically to your datasets by choosing `$FILENAME`.

**Comment by Braveheart53** [comment]
If I do this, and have lines as follows:
`ImportFileCSV('20220701_0003_1C-5D_K6.csv', headermode='1st', linked=True, rowsignore=6)
ImportFileCSV('20220701_0003_1C-6C_K1.csv', headermode='1st', linked=True, rowsignore=6)
ImportFileCSV('20220701_0003_1C-6C_K5.csv', headermode='1st', linked=True, rowsignore=6)`

Without setting prefix or suffix it overwrites all previous file links and data, and only displays the last data set.

Are you saying this is on purpose and one must utilize suffix and prefix if all files contain same headers?

**Comment by Braveheart53** [comment]
> If I do this, and have lines as follows: `ImportFileCSV('20220701_0003_1C-5D_K6.csv', headermode='1st', linked=True, rowsignore=6) ImportFileCSV('20220701_0003_1C-6C_K1.csv', headermode='1st', linked=True, rowsignore=6) ImportFileCSV('20220701_0003_1C-6C_K5.csv', headermode='1st', linked=True, rowsignore=6)`
> 
> Without setting prefix or suffix it overwrites all previous file links and data, and only displays the last data set.
> 
> Are you saying this is on purpose and one must utilize suffix and prefix if all files contain same headers?

If you include 'dssuffix' values, then it works well. Thank you.

**Comment by kaugummiheld** [comment]
> Without setting prefix or suffix it overwrites all previous file links and data, and only displays the last data set.  

Yeah, I see you figured that already out. This is the intended behavior. I think the thought is to make it easier to mix data which is split across multiple files.  
I also typically use a `<file identifier>_<column>` nomenclature for my datasets. E.g. I measured multiple power dependencies in file `2022-07-08_{1...3}.csv` I simply use `angle20_I`[ntensity] or `7d_power`(7th day of measurement) etc. Depending of course on the complexity of your file structure and hypotheses you want to check.

> In the vsz file, is there a command that does the same as $FILENAME ?

I hadn't checked before, but it seems you're right, `$FILENAME` is a function of the Veusz GUI and not the saved file. In the file just the full filename is denoted as prefix/suffix. 
Although I have to say, I feel I'm faster in doing it my way of manipulating the .vsz file with a normal text editor, i.e. copy an import line multiple times and use the replace function of the editor. Faster than scripting all of that in the Veusz commandline. :shrug:
