### ISSUE TITLE
Adding major and minor grid lines in GUI or Command Line

### ISSUE THREAD

**Issue by Braveheart53** [veusz/veusz#608]
I could not easily find in the GUI or the Manual where one may set to display grid lines (major and or minor) and their linespecs. Where is this in both the GUI and the API or console command line?

**Comment by Braveheart53** [comment]
![Clipboard01](https://user-images.githubusercontent.com/30416052/179090659-e3f9ccc3-66a0-4fe7-9467-a5894c2dd7bd.jpg)

Its in the GUI under the x or y axis for 2D plots

**Comment by korintje** [comment]
For a console command, you can use `Set` command `hide` properties like below:
```Set('page1/graph1/x/MajorTicks/hide', False)```
```Set('page1/graph1/x/MinorTicks/hide', True)```

Did you solve the problem? If resolved, close the issue.

**Comment by jeremysanders** [comment]
You need to uncheck the "hide" option on the grid lines

**Comment by jeremysanders** [comment]
Closing now. Please reopen if still a problem.
