### ISSUE TITLE
How can I change the label positionof vertical colorbar from left to right?

### ISSUE THREAD

**Issue by xichaoqiang** [veusz/veusz#616]
The label and ticks position of colorbar  in Matlab or Matplotlib is usually right.

https://matplotlib.org/stable/gallery/axes_grid1/simple_colorbar.html#sphx-glr-gallery-axes-grid1-simple-colorbar-py

![image](https://user-images.githubusercontent.com/30900789/187691647-44d49cdb-374a-4d5b-915e-b213b4a9802a.png)

However in the veusz is left. How can I set the label position?

**Comment by korintje** [comment]
Change axis position from 0 to 1 in `Properties` window of a colorbar.

**Comment by xichaoqiang** [comment]
![image](https://user-images.githubusercontent.com/30900789/187818881-9539636d-9112-4862-aa62-e7176740b5b2.png)
Sorry for my unclear description. I want change label and ticks' position from left to right.

**Comment by korintje** [comment]
Yes, so you can do that by changing "Axis position" parameter like below:

![図1](https://user-images.githubusercontent.com/30950088/187819918-e2dd92b0-11b5-462d-bbe5-360b1a14b201.png)

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply. It works.

**Comment by quanliden** [comment]
I have a problem about the colorbar. How can I make the colorbar outside of the image? I have tried to change its position, however, it can only varies inside the figure.
![image](https://github.com/user-attachments/assets/552910f4-f28d-4d34-907a-2ff34e7c8797)

**Comment by jeremysanders** [comment]
It's possible to change the position to manual, then change the position to be outside the range 0-1. This isn't very nice, unfortunately.
