### ISSUE TITLE
Can I cut image with custom path (polygon)?

### ISSUE THREAD

**Issue by xichaoqiang** [veusz/veusz#619]
How can I cut image in the custom path  (polygon)? 
As shown is the red circle in the below figure.
![image](https://user-images.githubusercontent.com/30900789/187846299-c1e92429-a6cb-4f71-a142-97d6c784b2e3.png)

Here is how matplotlib do it.
![image](https://user-images.githubusercontent.com/30900789/187846206-85ec23af-5800-4cf5-85cb-f2f8424dd9d7.png)

**Comment by korintje** [comment]
For rectangular clipping of photos and polygons, there is "clip" function.
But as far as I know, there is no direct feature to clip something by polygon.

Although somewhat tricky, there are several ways to accomplish the purpose itself.
1) Use "fill above" and "fill below" properties
![1](https://user-images.githubusercontent.com/30950088/187910175-c101bd21-86ec-4f8c-8090-9558a6cd5446.png)

2) Use VERY thick background-colored boarder of the polygon 
![2](https://user-images.githubusercontent.com/30950088/187910201-7e3cb14c-482e-4f07-8652-c1dd97068a84.png)

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply.

**Comment by xichaoqiang** [comment]
@korintje Yes, If we can backfill polygon object, it will be a good choice.
