### ISSUE TITLE
Veusz freezes when I save a project with large datasets

### ISSUE THREAD

**Issue by rs1-es** [veusz/veusz#629]
Hi, I imported a CSV with around 37000 lines and it imported well (and I can create plots), but when I want to save the project, Veusz freezes indefinitely and the project file is not created. I use Veusz 3.4 (Flatpak) on Arch Linux.

**Comment by jeremysanders** [comment]
Sorry for the delay in replying. I tried to reproduce this with a 40000 line file and couldn't. It saved within a second.

If you still have an example file, please feel free to send it.

**Comment by rs1-es** [comment]
I've tested it again with v3.5.3 (Flatpak), and the project saves correctly (and I can open it with no issues). I think I can close this issue.
