### ISSUE TITLE
Veusz does not open on Elementary OS

### ISSUE THREAD

**Issue by hajrudin10** [veusz/veusz#636]
when I tra to install veusz over the terminal this error mesage pops up:

    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:
    
    The following packages have unmet dependencies:
     veusz : Depends: python3-veusz (>= 3.5.3-0~ppa1~focal4) but it is not going to be installed
    E: Unable to correct problems, you have held broken packages.

i can install it over the app store but when I click on the icon the start window just flashes and the application does not open.

when I run the binary file it works badly the fonts are really strange and the plot aligment is not right and I got this mesage in the terminal:

    Qt: Session management error: None of the authentication protocols specified are supported
    QApplication: invalid style override 'adwaita' passed, ignoring it.
	    Available styles: Windows, Fusion
    Fontconfig error: Cannot load default config file
    VO table import: astropy module not available
    SAMP: sampy module not available

**Comment by jeremysanders** [comment]
I don't use elementary, but there are three packages required for veusz in the PPA: veusz, python3-veusz and python3-veusz.helpers. It sounds like you've not installed python3-veusz.

**Comment by jsgadas** [comment]
Which version of elementary os you are using @hajrudin10 ? 

I'm not sure if I should open another issue, but in any case, elementary os 6.1 app center provides the [Flatpak](https://flathub.org/apps/details/io.github.veusz.Veusz) 3.4 version of Veusz 

I tried to run this version on both Elementary OS 6.1 and Fedora 36, it seems to have some driver version incompatibility issues.

```
~$ flatpak run io.github.veusz.Veusz
QIBusPlatformInputContext: invalid portal bus.
Qt: Session management error: None of the authentication protocols specified are supported
QApplication: invalid style override 'adwaita' passed, ignoring it.
	Available styles: Breeze, Windows, Fusion
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/veusz/veusz_main.py", line 149, in run
    from veusz import widgets
  File "/app/lib/python3.9/site-packages/veusz/widgets/__init__.py", line 21, in <module>
    from .widget import Widget, Action
  File "/app/lib/python3.9/site-packages/veusz/widgets/widget.py", line 24, in <module>
    from .. import document
  File "/app/lib/python3.9/site-packages/veusz/document/__init__.py", line 22, in <module>
    from .doc import *
  File "/app/lib/python3.9/site-packages/veusz/document/doc.py", line 32, in <module>
    import h5py
  File "/app/lib/python3.9/site-packages/h5py/__init__.py", line 56, in <module>
    from . import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z, h5pl
  File "h5py/h5fd.pyx", line 220, in init h5py.h5fd
RuntimeError: Wrong file driver version # (wrong file driver version #)
```

**Comment by jeremysanders** [comment]
@jsgadas I think there's an incompatibility between the hdf5 library and h5py for the latest hdf5 version. hdf5 probably needs reverting to an old version for the moment in the flatpak repository.

**Comment by hajrudin10** [comment]
@jsgadas I managed to make the 3.0 version running with sudo apt install. But I have the same issue as you with the flatpack version. On my other windows PC I have veusz 3.5 and it is not compatible with the older version. The PPA has also a similar error as the flatpack version if I install a third party pyqt5.15 package. @jeremysanders  what method to use in order to revert the hdf5?

**Comment by jsgadas** [comment]
@hajrudin10 a temporary workaround is [downgrade](https://unix.stackexchange.com/questions/552688/is-it-possible-to-roll-back-a-flatpak-update) the Veusz version (Flatpak installed) to the last commit until the hdf5 rollback is performed :

```
flatpak update --commit=35473a41220ea49a7de71660b67a2490cbf4719d83433eaad234de18c057be45 io.github.veusz.Veusz
```

**Comment by jeremysanders** [comment]
I think the PPA should be fixed now. There was a problem with the dependencies.
