### ISSUE TITLE
I cannot install Veusz 3.5.3 on Ubuntu MATE 20.04.05.

### ISSUE THREAD

**Issue by tsumutsumu7** [veusz/veusz#638]
Dear developer

I cannot install Veusz 3.5.3 on Ubuntu MATE 20.04.05.

It seems to be because it requires PyQt5 5.15.x where PyQt5 available for Python 3.8 on the system is 5.14.x.

I installed PyQt5 5.15.2 from a 3rd party PPA, but
"ValueError: PyCapsule_GetPointer called with incorrect name"
and cannot start it.

When I remove the PyQt5 3rd party PPA and put PyQt5 back in, Veusz is now 3.0, far past the 3.4 I had been using, and I cannot open the files I was using yesterday.

**Comment by jeremysanders** [comment]
There was a bug in the PPA version of Veusz. Can you try installing again? It should be version 3.5.3-0~ppa1~focal5.

**Comment by jeremysanders** [comment]
Closing now. Please reopen if there's still a problem.
