### ISSUE TITLE
Cannot install Veusz 3.5.3 on Win 7Pro 64bit

### ISSUE THREAD

**Issue by artrogachev** [veusz/veusz#639]
Hi,
I cannot install Veusz 3.5.3 on Windows 7Pro 64 bit. After completing installation I get two error messages.
Installation of 3.4 helps creating best illustrations ever, so, I hope that it would be possible to use the latest version.
![2022-11-23_11-18-08](https://user-images.githubusercontent.com/118871435/203468894-69452544-781c-4380-ab5a-374e6fe04252.png)
![2022-11-23_11-23-42](https://user-images.githubusercontent.com/118871435/203468887-36744956-c19c-4fdd-a403-d79bd0458006.png)

**Comment by jeremysanders** [comment]
Unfortunately we're not supporting Windows 7 any more. Someone would have to try to get it to build on Windows 7, which is likely difficult.

**Comment by artrogachev** [comment]
Hu Jeremy,
Thanks for your comment. I have another issue which is likely a consequence of the previous: a file created in V3.5.3 cannot be opened in V3.4?
Is this due to incompatibility of the versions? Is there any chance to solve this issue?

**Comment by jeremysanders** [comment]
Sorry didn't reply earlier. Sometimes files created from newer versions don't open in older ones. If you can often remove the offending command with a text editor and the vsz file.

**Comment by Silverliu2023** [comment]
Veusz 3.4 are highest version work fine with windows 7 x64!

Please notice it on web page this would help people save times.

Veusz creat at Oct 17,2021.

Win 7 old PC are world running basic platform.

There still have above 30 hundred million people still run with win 7 , there living standard under Unit Nation poverty levels.

Just explain why german subway still use win 3.1 in 2024?

https://windowsreport.com/windows-3-1-german-railway/
