### ISSUE TITLE
Axis function range issue

### ISSUE THREAD

**Issue by MarkDurre** [veusz/veusz#643]
I have found an issue with axis functions setting the range of "t". I attach an example where I have the same formula linked to the y axis; the only difference between them is the min/max t values. In the right-hand one (black) I have the range 0-3 (which produces correct values) in the left-hand one (red) I restrict the range to 0.5-2 - the end calculated values are incorrect (i.e. 500 and 3000).
[AxisFunctionIssue.vsz.zip](https://github.com/veusz/veusz/files/10504890/AxisFunctionIssue.vsz.zip)

**Comment by jeremysanders** [comment]
Your function has log(t) and log(0) is not valid. I don't think this can work. It does print out `Warning: values exceed bounds in axis-function`.

**Comment by MarkDurre** [comment]
Yes, I get those warnings, but I was careful to set minimum t as 0.01, which is still valid. It also happens when I set the minimum y axis value to 0.01. 

This problem still happens if I use a simpler function, e.g. t**2, and I restrict the range of t. I still get the warnings - I'm not sure which values and bounds it means. In the attached example, the same problem is still there.
[AxisFunctionIssue2.vsz.zip](https://github.com/veusz/veusz/files/10531165/AxisFunctionIssue2.vsz.zip)

**Comment by MarkDurre** [comment]
i.e. the displaement of the tick-mark values
