### ISSUE TITLE
Numpy dtype bool wrt datasetplugin.py

### ISSUE THREAD

**Issue by Braveheart53** [veusz/veusz#644]
Where you use numpy `dtype=bool`, this needs to be changed to `dtype=bool_ `per the updated numpy.

Changes implemented and a recent bug submission seems solved. Replaced all occurrences of `dtype=bool)` with `dtype=bool_)`

**Comment by jeremysanders** [comment]
This should already be fixed here:
https://github.com/veusz/veusz/commit/f93cf7ac0a1d93902524f38efbb58c4f0d016caa

**Comment by Braveheart53** [comment]
Is this fix in a beta release? I am using version 3.5.3
I was just about to downgrade numpy for int issue....

**Comment by jeremysanders** [comment]
No, there's no release yet. Thanks for the report, by the way.

**Comment by Braveheart53** [comment]
AMAZING work on this GUI btw, thank you VERY much for this software, IMHO, this is the best GUI for data processing and reduction to replace matlab for non-technical users. Looking forward to the new release, implemented the fixes in the my code locally as you shown in your bug, please close.
