### ISSUE TITLE
Veusz 3.5.3 display broken on Ubuntu MATE 22.04 LTS

### ISSUE THREAD

**Issue by BKFCAW** [veusz/veusz#645]
I recently upgraded an AMD Ryzen 7 2700x from Ubuntu MATE 20.04 to 22.04.  Veusz worked properly under the previous OS.  Now, after upgrading Veusz to version 3.5.3, the GUI display has pieces missing.  Screenshot attached.  The menu is visible but parts of the plot area and the left-hand panel are missing, and the application does not function.  Is there a fix for this?

![screenshot](https://user-images.githubusercontent.com/102564515/215291932-fe244cd6-f09f-440e-a226-7037de0d4a73.jpg)

**Comment by jeremysanders** [comment]
This looks like a screen driver issue, rather than a Veusz bug. Do you have a problem with other Qt applications (e.g. KDE, Kate, Calibre, Krita)? Which version is this - package, binary, source?

**Comment by BKFCAW** [comment]
I honestly don't know what applications use Qt, but just as a test, I installed Krita.  It installed without a problem, and the GUI interface looks OK.  

Here is the list of ppa files I used for apt install:
```
jeremysanders-ubuntu-ppa-bionic.list
jeremysanders-ubuntu-ppa-bionic.list.distUpgrade
jeremysanders-ubuntu-ppa-bionic.list.save
jeremysanders-ubuntu-ppa-jammy.list
```

...and here is the output of "apt list"
```
python3-veusz.helpers/jammy,now 3.5.3-0~ppa1~jammy1 amd64 [installed,automatic]
python3-veusz/jammy,jammy,now 3.5.3-0~ppa1~jammy1 all [installed,automatic]
veusz/jammy,jammy,now 3.5.3-0~ppa1~jammy1 all [installed]
```

Since upgrading to 22.04 LTE, the only other trouble I've had is with browsers Firefox and Chrome: they don't load at all, which I'm quite sure is related to the switch to snap.  Microsoft Edge works fine, as do image and movie viewers.

**Comment by jeremysanders** [comment]
I'm using jammy, and the PPA version is fine on my computer.

You could try:
1. Delete the directory `${HOME}/.config/veusz.org` to reset your settings.
2. Run in a terminal and see whether any warnings are printed

**Comment by BKFCAW** [comment]
Done.  Here is the output from invoking veusz in a terminal window:

```
/% veusz
qt.qpa.xcb: XKeyboard extension not present on the X server
VO table import: astropy module not available
SAMP: sampy module not available
```

**Comment by jeremysanders** [comment]
The only thing I can suggest is that you have some old installation of veusz, Qt or PyQt somewhere on your computer which is being used instead of the one from the packages.

**Comment by BKFCAW** [comment]
It took some doing, but it turns out that it was a VNC server issue.  I don't run it from the console, but connect to the Unix box running headless from a Mac.  Instead of tightvncserver, I had to install tigervnc-standalone-server, which resolved the missing keyboard problem as well.

**Comment by jeremysanders** [comment]
Thanks for letting me know.
