### ISSUE TITLE
Cancelling eraseing user's code in *.vsz

### ISSUE THREAD

**Issue by tamaswells** [veusz/veusz#646]
Supposed that I have added a piece of code in a Veusz file. Once I opened this file in the Veusz GUI, made a tiny of changes and saved the file, my code would disappear in the new file. I am wondering if there is a way to make my own code survive.

**Comment by jeremysanders** [comment]
You can define constants and one-line functions in the Custom Definitions dialog box. You can also import code there from other Python modules.

There's also the plugin system, which allows you to add code to manipulate documents, import data or manipulate datasets, but that is attached to the user interface.

I'm thinking of adding a way to embed code within a document, but that's planned for the release after next (as the next release should be soon).

**Comment by tamaswells** [comment]
I got it.
