### ISSUE TITLE
colorbar with 2D image plot?

### ISSUE THREAD

**Issue by BKFCAW** [veusz/veusz#657]
I have a matrix of numbers for which I'd like to make a heat map.  I can make the color plot using the 2D image widget, but I'd like a colorbar to go with it so that viewers can understand the quantitative range that the colors mean.  I can see a colorbar widget, but it does not seem to go with the 2D image viewer.  Am I missing something?

**Comment by jeremysanders** [comment]
You need to choose which image widget it applies to by choosing that in the "widget" option.
