### ISSUE TITLE
Question: What if the bins of a histogram are _not_ equally wide?

### ISSUE THREAD

**Issue by StSav012** [veusz/veusz#670]
Trying to implement a histogram calculation for my data, I've looked the error estimation up in your code. There, I've found the following line:

https://github.com/veusz/veusz/blob/b115a96caf7aae0195cb599527c14c504ad745ca/veusz/datasets/histo.py#L127

As the bin scaling might be non-linear, shouldn't it be reflected there in any way? Or the bins are guaranteed to be equal there?

I fancy it may be something like this:
```python
if self.method == 'density':
    ratio = 1.0 / (hist.size * (bin_edges[1:] - bin_edges[:-1]))  # type: N.typing.NDArray[N.float64]
...
return -N.dot(nerr, ratio), N.dot(perr, ratio)
```

My knowledge of math is not enough here.

**Comment by jeremysanders** [comment]
Thanks for spotting this. I think you're correct that this is a bug and your fix looks good.

I realise that I probably should have referenced your name in the commit message.
