### ISSUE TITLE
Does not work without display

### ISSUE THREAD

**Issue by 5nizza** [veusz/veusz#687]
I run `veusz` on a cluster from a command line to export a diagram into a PDF file. On my local machine, this is done without opening GUI. On the cluster, even `veusz.exe --help` fails:
```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, vnc, xcb.

Aborted (core dumped)
```

Does `veusz` work without display? Thanks.

Veusz 3.6.2.

**Comment by 5nizza** [comment]
many many thanks for quick answer! it worked!

**Comment by 5nizza** [comment]
argh, was to quick to conclusion: here are two graphs:
the left one is correct, the right one has black boxes instead of letters.
The right one uses `QT_QPA_PLATFORM=minimal`. Ideas? Thanks.
![Screenshot from 2023-12-28 04-40-55](https://github.com/veusz/veusz/assets/928552/7ead1a3f-d472-43fe-b45a-52961f2cd644)

**Comment by jeremysanders** [comment]
Yes, thinking about it, with the minimal handler Qt doesn't have access to the fonts, etc, as these are obtained from X11.

You'll need to go to the second option to get correct fonts.

**Comment by 5nizza** [comment]
The second option also requires installing the package `libdbus-1-dev`. So overall, in my singularity image I install two packages:
```
    apt -y install xvfb
    apt -y install libdbus-1-dev
```
And now it works. Thanks, happy NY.
