### ISSUE TITLE
NaN handling on/off results in Veusz crash

### ISSUE THREAD

**Issue by ViktoriaSteck** [veusz/veusz#713]
Trying to set NaN handling from "break-on" to "ignore" results in Error message and my plot disappearing. Here is the message:

Traceback (most recent call last):
  File "veusz/windows/plotwindow.py", line 1088, in checkPlotUpdate
  File "veusz/document/doc.py", line 369, in paintTo
  File "veusz/widgets/root.py", line 144, in draw
  File "veusz/widgets/page.py", line 371, in draw
  File "veusz/widgets/widget.py", line 298, in draw
  File "veusz/widgets/graph.py", line 307, in draw
  File "veusz/widgets/plotters.py", line 175, in draw
  File "veusz/widgets/point.py", line 912, in dataDraw
  File "veusz/datasets/helpers.py", line 111, in generateValidDatasetParts
  File "veusz/datasets/base.py", line 149, in __getitem__
  File "veusz/datasets/base.py", line 141, in _getItemHelper
IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 8

Frame checkPlotUpdate (File veusz/windows/plotwindow.py, line 1092)
 self = <veusz.windows.plotwindow.PlotWindow object at 0x1224ff910>
  self.AdjustIgnored = 0
  self.AdjustToContents = 2
  self.AdjustToContentsOnFirstShow = 1
  self.AnchorUnderMouse = 2
  self.AnchorViewCenter = 1
  self.BoundingRectViewportUpdate = 4
  self.Box = 1
  self.CacheBackground = 1
  self.CacheNone = 0
  self.DontAdjustForAntialiasing = 4
  self.DontClipPainter = 1
  self.DontSavePainterState = 2
  self.DrawChildren = 2
  self.DrawWindowBackground = 1
  self.FullViewportUpdate = 0
  self.HLine = 4
  self.IgnoreMask = 4
  self.MinimalViewportUpdate = 1
  self.NoAnchor = 0
  self.NoDrag = 0
  self.NoFrame = 0
  self.NoViewportUpdate = 3
  self.Panel = 2
  self.PdmDepth = 6
  self.PdmDevicePixelRatio = 11
  self.PdmDevicePixelRatioScaled = 12
  self.PdmDpiX = 7
  self.PdmDpiY = 8
  self.PdmHeight = 2
  self.PdmHeightMM = 4
  self.PdmNumColors = 5
  self.PdmPhysicalDpiX = 9
  self.PdmPhysicalDpiY = 10
  self.PdmWidth = 1
  self.PdmWidthMM = 3
  self.Plain = 16
  self.Raised = 32
  self.RubberBandDrag = 2
  self.ScrollHandDrag = 1
  self.Shadow_Mask = 240
  self.Shape_Mask = 15
  self.SmartViewportUpdate = 2
  self.StyledPanel = 6
  self.Sunken = 48
  self.VLine = 5
  self.WinPanel = 3
  self.__dict__ = {'scene': <PyQt5.QtWidgets.QGraphicsScene object at 0x1224ff9a0>, 'dpi': (72, 72), 'pixmapitem': <PyQt5.QtWidgets.QGraph...
  self.__doc__ = 'Class to show the plot(s) in a scrollable window.'
  self.__module__ = 'veusz.windows.plotwindow'
  self.antialias = True
  self.clickmode = 'select'
  self.controlgraphroot = <veusz.windows.plotwindow.ControlGraphRoot object at 0x1224ffac0>
  self.currentclickmode = 'select'
  self.docchangeset = 1021
  self.document = <veusz.document.doc.Document object at 0x1a330af80>
  self.dpi = (72, 72)
  self.grabpos = PyQt5.QtCore.QPointF(118.0, 108.0)
  self.ignoreclick = False
  self.interval = -1
  self.isfullscreen = False
  self.lastwidgetsselected = [<veusz.widgets.point.PointPlotter object at 0x11b60fb50>]
  self.oldpagenumber = 0
  self.oldzoom = 1.0
  self.pagenumber = 0
  self.painthelper = <veusz.document.painthelper.PaintHelper object at 0x125597f90>
  self.pickerinfo = <veusz.widgets.pickable.PickInfo object at 0x1224f97d0>
  self.pickeritem = <veusz.windows.plotwindow.PickerCrosshairItem object at 0x1224ffbe0>
  self.pickerwidgets = []
  self.pixmapitem = <PyQt5.QtWidgets.QGraphicsPixmapItem object at 0x1224ffa30>
  self.rendercontrol = <veusz.windows.plotwindow.RenderControl object at 0x1224ffc70>
  self.scene = <PyQt5.QtWidgets.QGraphicsScene object at 0x1224ff9a0>
  self.scrolltimer = <PyQt5.QtCore.QTimer object at 0x1224ffeb0>
  self.selectactiongrp = <PyQt5.QtWidgets.QActionGroup object at 0x122504c10>
  self.staticMetaObject = <PyQt5.QtCore.QMetaObject object at 0x11b5bccf0>
  self.sumwheeldelta = 0
  self.timer = <PyQt5.QtCore.QTimer object at 0x1224ffe20>
  self.updateintervals = ((0, 'Disable'), (-1, 'On document change'), (100, 'Every 0.1s'), (250, 'Every 0.25s'), (500, 'Every 0.5s'), (1000, 'Eve...
  self.viewtoolbar = <PyQt5.QtWidgets.QToolBar object at 0x1224fff40>
  self.vzactions = {'file.new.menu': <PyQt5.QtWidgets.QAction object at 0x1a32f4430>, 'file.new.graph': <PyQt5.QtWidgets.QAction object at ...
  self.winpos = PyQt5.QtCore.QPoint(564, 282)
  self.zoomfactor = 1.0
  self.zoomrect = <PyQt5.QtWidgets.QGraphicsRectItem object at 0x1224ffb50>
 devicepixelratio = 2.0
 scaling = 2.0
 size = (623.6220472440946, 935.4330708661419)
 phelper = <veusz.document.painthelper.PaintHelper object at 0x1255df510>

Frame paintTo (File veusz/document/doc.py, line 369)
 self = <veusz.document.doc.Document object at 0x1a330af80>
  self.__dict__ = {'changeset': 1024, 'compatlevel': 1, 'datasettags': defaultdict(<class 'list'>, {}), 'suspendupdates': [], 'locale': <P...
  self.__doc__ = 'Document class for holding the graph data.\n    '
  self.__module__ = 'veusz.document.doc'
  self.__weakref__ = None
  self.basewidget = <veusz.widgets.root.Root object at 0x1a31e1750>
  self.changeset = 1024
  self.compatlevel = 1
  self.data = {'\ufeffdepth_UP': <veusz.datasets.oned.Dataset object at 0x1255f3150>, 'dFe_UP': <veusz.datasets.oned.Dataset object at...
  self.datasettags = defaultdict(<class 'list'>, {})
  self.evaluate = <veusz.document.evaluate.Evaluate object at 0x1a32e0dd0>
  self.filename = '/Users/viktoria/Documents/[ Scripps ]/Research/Field experiments/P2107 - CCE-LTER process cruise/Trace Metals/Trace_metals.vsz'
  self.historybatch = []
  self.historyredo = []
  self.historyundo = [<veusz.document.operations.OperationSettingSet object at 0x1255a1a90>, <veusz.document.operations.OperationSettingSet o...
  self.locale = <PyQt5.QtCore.QLocale object at 0x11b67ece0>
  self.maxcompatlevel = 1
  self.modified = True
  self.pluginsloaded = True
  self.staticMetaObject = <PyQt5.QtCore.QMetaObject object at 0x11b5bfbc0>
  self.suspendupdates = []
 painthelper = <veusz.document.painthelper.PaintHelper object at 0x1255df510>
 page = 0

Frame draw (File veusz/widgets/root.py, line 144)
 self = <veusz.widgets.root.Root object at 0x1a31e1750>
  self.__dict__ = {'parent': None, 'document': <veusz.document.doc.Document object at 0x1a330af80>, 'name': '/', 'children': [<veusz.widge...
  self.__doc__ = 'Root widget class for plotting the document.'
  self.__module__ = 'veusz.widgets.root'
  self.actions = []
  self.allowusercreation = False
  self.childnames = ['page1']
  self.children = [<veusz.widgets.page.Page object at 0x11b6b7410>]
  self.document = <veusz.document.doc.Document object at 0x1a330af80>
  self.isaxis = False
  self.isplotter = False
  self.issetting = False
  self.issettings = False
  self.iswidget = True
  self.name = '/'
  self.nodetype = 'widget'
  self.parent = None
  self.path = '/'
  self.settings = <veusz.setting.settings.Settings object at 0x1a31e0b50>
  self.typename = 'document'
  self.userdescription = ''
 painthelper = <veusz.document.painthelper.PaintHelper object at 0x1255df510>
 pagenum = 0
 xw = 311.8110236220473
 yw = 467.71653543307093
 posn = [0, 0, 311.8110236220473, 467.71653543307093]
 painter = <veusz.document.painthelper.RecordPainter object at 0x121eb0120>
 page = <veusz.widgets.page.Page object at 0x11b6b7410>

Frame draw (File veusz/widgets/page.py, line 371)
 self = <veusz.widgets.page.Page object at 0x11b6b7410>
  self.__dict__ = {'parent': <veusz.widgets.root.Root object at 0x1a31e1750>, 'document': <veusz.document.doc.Document object at 0x1a330af...
  self.__doc__ = 'A class for representing a page of plotting.'
  self.__module__ = 'veusz.widgets.page'
  self.__weakref__ = None
  self.actions = []
  self.allowusercreation = True
  self.childnames = ['AGE']
  self.children = [<veusz.widgets.graph.Graph object at 0x11b7a32d0>]
  self.description = 'Blank page'
  self.document = <veusz.document.doc.Document object at 0x1a330af80>
  self.isaxis = False
  self.isplotter = False
  self.issetting = False
  self.issettings = False
  self.iswidget = True
  self.name = 'page1'
  self.nodetype = 'widget'
  self.parent = <veusz.widgets.root.Root object at 0x1a31e1750>
  self.path = '/page1'
  self.settings = <veusz.setting.settings.Settings object at 0x11b6b41d0>
  self.typename = 'page'
  self.userdescription = ''
 parentposn = [0, 0, 311.8110236220473, 467.71653543307093]
 painthelper = <veusz.document.painthelper.PaintHelper object at 0x1255df510>
 outerbounds = None
 s = <veusz.setting.settings.Settings object at 0x11b6b41d0>
 x1 = 0
 y1 = 0
 x2 = 311.8110236220473
 y2 = 467.71653543307093
 axisdependhelper = <veusz.widgets.page.AxisDependHelper object at 0x1255dd890>
 pamap = defaultdict(<class 'list'>, {<veusz.widgets.point.PointPlotter object at 0x11b60fb90>: [<veusz.widgets.axis.Axis object ...
 axis = <veusz.widgets.axis.Axis object at 0x122a040d0>
 plotters = [<veusz.widgets.point.PointPlotter object at 0x11b7a2750>]
 plot = <veusz.widgets.point.PointPlotter object at 0x11b7a2750>
 painter = <veusz.document.painthelper.RecordPainter object at 0x11b78e5e0>
 w = 311.8110236220473
 h = 467.71653543307093

Frame draw (File veusz/widgets/widget.py, line 298)
 self = <veusz.widgets.page.Page object at 0x11b6b7410>
 parentposn = [0, 0, 311.8110236220473, 467.71653543307093]
 painthelper = <veusz.document.painthelper.PaintHelper object at 0x1255df510>
 outerbounds = [0, 0, 311.8110236220473, 467.71653543307093]
 bounds = [0.0, 0.0, 311.8110236220473, 467.71653543307093]
 c = <veusz.widgets.graph.Graph object at 0x11b7a32d0>

Frame draw (File veusz/widgets/graph.py, line 307)
 self = <veusz.widgets.graph.Graph object at 0x11b7a32d0>
  self.__dict__ = {'parent': <veusz.widgets.page.Page object at 0x11b6b7410>, 'document': <veusz.document.doc.Document object at 0x1a330af...
  self.__doc__ = 'Graph for containing other sorts of widgets'
  self.__module__ = 'veusz.widgets.graph'
  self.__weakref__ = None
  self.actions = []
  self.allowusercreation = True
  self.childnames = ['Depth', 'dFe', 'xy1', 'dMn', 'xy2', 'dZn', 'xy3', 'MnZn', 'xy4']
  self.children = [<veusz.widgets.axis.Axis object at 0x121f2fe90>, <veusz.widgets.axis.Axis object at 0x121f2fdd0>, <veusz.widgets.point....
  self.description = 'Base graph'
  self.document = <veusz.document.doc.Document object at 0x1a330af80>
  self.isaxis = False
  self.isplotter = False
  self.issetting = False
  self.issettings = False
  self.iswidget = True
  self.name = 'AGE'
  self.nodetype = 'widget'
  self.parent = <veusz.widgets.page.Page object at 0x11b6b7410>
  self.path = '/page1/AGE'
  self.settings = <veusz.setting.settings.Settings object at 0x11b7a33d0>
  self.typename = 'graph'
  self.userdescription = ''
 parentposn = [0.0, 0.0, 311.8110236220473, 467.71653543307093]
 painthelper = <veusz.document.painthelper.PaintHelper object at 0x1255df510>
 outerbounds = [0, 0, 311.8110236220473, 467.71653543307093]
 axisbroken = <module 'veusz.widgets.axisbroken' from '/Applications/Veusz.app/Contents/MacOS/veusz/widgets/axisbroken.pyc'>
 s = <veusz.setting.settings.Settings object at 0x11b7a33d0>
 maxbounds = [0.0, 0.0, 311.8110236220473, 467.71653543307093]
 painter = <veusz.document.painthelper.RecordPainter object at 0x11b5bd230>
 path = <PyQt5.QtGui.QPainterPath object at 0x11b5bce40>
 axestodraw = {'Depth': <veusz.widgets.axis.Axis object at 0x121f2fe90>, 'dFe': <veusz.widgets.axis.Axis object at 0x121f2fdd0>, 'dMn'...
 axesofwidget = {<veusz.widgets.point.PointPlotter object at 0x11b60fb90>: [<veusz.widgets.axis.Axis object at 0x121f2fdd0>, <veusz.widg...
 a = <veusz.widgets.axis.Axis object at 0x122a040d0>
 axisdrawlist = [('dZn', <veusz.widgets.axis.Axis object at 0x121ebb050>), ('dMn', <veusz.widgets.axis.Axis object at 0x11b6b5a10>), ('d...
 aname = 'Depth'
 awidget = <veusz.widgets.axis.Axis object at 0x121f2fe90>
 axiswidgets = [<veusz.widgets.axis.Axis object at 0x121ebb050>, <veusz.widgets.axis.Axis object at 0x11b6b5a10>, <veusz.widgets.axis.A...
 axis = <veusz.widgets.axis.Axis object at 0x122a040d0>
 axesdrawn = {<veusz.widgets.axis.Axis object at 0x122a040d0>}
 axes = [<veusz.widgets.axis.Axis object at 0x121f2fe90>, <veusz.widgets.axis.Axis object at 0x121ebb050>]
 bounds = [63.779527559055126, 5.669291338582678, 306.1417322834646, 269.2913385826772]
 brokenaxes = set()
 c = <veusz.widgets.point.PointPlotter object at 0x11b60fb50>

Frame draw (File veusz/widgets/plotters.py, line 175)
 self = <veusz.widgets.point.PointPlotter object at 0x11b60fb50>
  self.__dict__ = {'parent': <veusz.widgets.graph.Graph object at 0x11b7a32d0>, 'document': <veusz.document.doc.Document object at 0x1a330...
  self.__doc__ = 'A class for plotting points and their errors.'
  self.__module__ = 'veusz.widgets.point'
  self.__weakref__ = None
  self.actions = []
  self.allowusercreation = True
  self.childnames = []
  self.children = []
  self.description = 'Plot points with lines and errorbars'
  self.document = <veusz.document.doc.Document object at 0x1a330af80>
  self.isaxis = False
  self.isplotter = True
  self.issetting = False
  self.issettings = False
  self.iswidget = True
  self.name = 'xy3'
  self.nodetype = 'widget'
  self.parent = <veusz.widgets.graph.Graph object at 0x11b7a32d0>
  self.path = '/page1/AGE/xy3'
  self.settings = <veusz.setting.settings.Settings object at 0x121f88ad0>
  self.typename = 'xy'
  self.userdescription = "x='dZn_AGE', y='depth_AGE', marker='circle'"
 parentposn = [63.779527559055126, 5.669291338582678, 306.1417322834646, 269.2913385826772]
 painthelper = <veusz.document.painthelper.PaintHelper object at 0x1255df510>
 outerbounds = [0, 0, 311.8110236220473, 467.71653543307093]
 posn = [63.779527559055126, 5.669291338582678, 306.1417322834646, 269.2913385826772]
 axes = [<veusz.widgets.axis.Axis object at 0x121ebb050>, <veusz.widgets.axis.Axis object at 0x121f2fe90>]
 cliprect = PyQt5.QtCore.QRectF(63.779527559055126, 5.6692913385826955, 242.36220472440948, 263.6220472440945)
 painter = <veusz.document.painthelper.RecordPainter object at 0x11b5bcac0>

Frame dataDraw (File veusz/widgets/point.py, line 912)
 self = <veusz.widgets.point.PointPlotter object at 0x11b60fb50>
 painter = <veusz.document.painthelper.RecordPainter object at 0x11b5bcac0>
 axes = [<veusz.widgets.axis.Axis object at 0x121ebb050>, <veusz.widgets.axis.Axis object at 0x121f2fe90>]
 posn = [63.779527559055126, 5.669291338582678, 306.1417322834646, 269.2913385826772]
 cliprect = PyQt5.QtCore.QRectF(63.779527559055126, 5.6692913385826955, 242.36220472440948, 263.6220472440945)
 s = <veusz.setting.settings.Settings object at 0x121f88ad0>
 doc = <veusz.document.doc.Document object at 0x1a330af80>
 xv = <veusz.datasets.oned.Dataset object at 0x12558a750>
 yv = <veusz.datasets.oned.Dataset object at 0x1255deb50>
 text = None
 scalepoints = <veusz.datasets.oned.Dataset object at 0x1255dc4d0>
 colorpoints = <veusz.datasets.oned.Dataset object at 0x1255de590>
 nanbreak = False

Frame generateValidDatasetParts (File veusz/datasets/helpers.py, line 111)
 datasets = [<veusz.datasets.oned.Dataset object at 0x12558a750>, <veusz.datasets.oned.Dataset object at 0x1255deb50>, None, <veusz....
 breakds = False
 invalid = array([False, False, False, False,  True, False, False, False])
 minlen = 8
 ds = <veusz.datasets.oned.Dataset object at 0x1255dc4d0>
 nextinvalid = array([False, False, False, False, False, False, False, False])
 retn = [<veusz.datasets.oned.Dataset object at 0x1255de310>, <veusz.datasets.oned.Dataset object at 0x1255de390>, None]
 valid = array([ True,  True,  True,  True, False,  True,  True,  True])

Frame __getitem__ (File veusz/datasets/base.py, line 149)
 self = <veusz.datasets.oned.Dataset object at 0x1255dc4d0>
  self.__dict__ = {'document': None, 'linked': None, 'tags': set(), 'data': array([], dtype=float64), 'serr': None, 'perr': None, 'nerr': None}
  self.__doc__ = 'Represents a dataset.'
  self.__module__ = 'veusz.datasets.oned'
  self.__weakref__ = None
  self.column_descriptions = ('Data', 'Sym. errors', 'Neg. errors', 'Pos. errors')
  self.columns = ('data', 'serr', 'nerr', 'perr')
  self.data = array([], dtype=float64)
  self.datatype = 'numeric'
  self.dimensions = 1
  self.displaytype = 'numeric'
  self.document = None
  self.dstype = '1D'
  self.editable = True
  self.linked = None
  self.nerr = None
  self.perr = None
  self.serr = None
  self.subsetclass = None
  self.tags = set()
 key = array([ True,  True,  True,  True, False,  True,  True,  True])

Frame _getItemHelper (File veusz/datasets/base.py, line 141)
 self = <veusz.datasets.oned.Dataset object at 0x1255dc4d0>
 key = array([ True,  True,  True,  True, False,  True,  True,  True])
 args = {}
 col = 'data'
 array = array([], dtype=float64)

**Comment by jeremysanders** [comment]
Thanks for the report. A fix will be in the next release.
