### ISSUE TITLE
Suggestion, significant digits/figures

### ISSUE THREAD

**Issue by kissbp** [veusz/veusz#714]
Hi,
It would be a nice feature to able to set the sig figs to the axes. (https://en.wikipedia.org/wiki/Significant_figures)
I try to use 3 sig figs, but I cant do that properly. At the top 100.0 should be 100.
![image](https://github.com/user-attachments/assets/9b7f58e4-452e-457b-800a-376091c792c3)

It is not crucial, but would be a great feature. Thx

**Comment by jeremysanders** [comment]
Thanks for the report. I've never encountered it putting decimal places automatically after 100. I don't know how you got the strange axis scale. Maybe a full example would help.

There already is a formatting option for controlling the formatting of axis numbers. See https://veusz.github.io/docs/manual/introduction.html, section Axis Numeric Scales. %.3g or %.3Vg should do what you want.

**Comment by devindowning** [comment]
Regarding decimals/formatting, I would love the option to add commas, which I think cannot be done. For example: 1,000.00

Thanks - Devin Downing

Sent from my iPhone

On Aug 13, 2024, at 1:06 PM, Jeremy Sanders ***@***.***> wrote:

﻿

Thanks for the report. I've never encountered it putting decimal places automatically after 100. I don't know how you got the strange axis scale. Maybe a full example would help.

There already is a formatting option for controlling the formatting of axis numbers. See https://veusz.github.io/docs/manual/introduction.html, section Axis Numeric Scales. %.3g or %.3Vg should do what you want.

**Comment by kissbp** [comment]
Thank you Jeremy, the %.3g option somehow escaped my notice. I used %.1f, now it works correctly.
