### ISSUE TITLE
"Click to reset graph axes" should immediately reset axes

### ISSUE THREAD

**Issue by splendiduser** [veusz/veusz#719]
It feels unnecessary that in order to reset the data zoom one has to select the "reset axes" button and then again click into the graph. Is it possible to immediately reset the zoom once the button is clicked?

**Comment by jeremysanders** [comment]
There can be more than one graph on a page, so that's why there's a click.

**Comment by splendiduser** [comment]
I see. That makes sense. Although one could argue that the GUI could keep track of the last graph that was interacted with and immediately reset it. Or distinguish whether there is only one graph or multiple. But feel free to close the issue. Thank you.
