### ISSUE TITLE
Export multipage graphics on Windows

### ISSUE THREAD

**Issue by jat255** [veusz/veusz#95]
Using the most recent git version (commit 37f1936d05), it appears that the new export dialog is not working. I'm running this by calling veusz_main.py from a Spyder console, as suggested in the wiki. Running from this version on Arch linux works as expected (veusz-git package from AUR). Is this just not implemented yet in Windows, or is there something specific that I'm missing?

**Comment by jeremysanders** [comment]
This is old and there is now a new export dialog
